// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef aboutWindow_h
#define aboutWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
extern void controlBarCB(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
#include <FL/Fl_Output.H>

class AboutWindow {
public:
  AboutWindow(int x, int y, int wi, int height, const char* l); 
  Fl_Double_Window* make_window();
  Fl_Double_Window *aboutWindow;
  Fl_Box *versionLabel;
  Fl_Box *whiteBG;
  Fl_Box *whiteB2;
  Fl_Box *whiteB3;
  Fl_Box *whiteB4;
  Fl_Button *closeButton;
  Fl_Box *compileDate;
  Fl_Box *compileTime;
  Fl_Browser *textBrowser;
  Fl_Output *status;
};
#endif
