// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef activatorWindow_h
#define activatorWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Wizard.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include "Fl_Button_gfc.h"
extern void createActivationCB(Fl_Button_gfc*, void*);
#include <FL/Fl_Text_Display.H>
extern void createActivationCB(Fl_Box*, void*);


class ActivatorWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *activatorWindow;
  Fl_Group *controlsGroup;
  Fl_Box *checkmark;
  Fl_Wizard *wizard;
  Fl_Group *pageStart;
  Fl_Input *requesterName;
  Fl_Input *clientName;
  Fl_Input *companyName;
  Fl_Choice *osName;
  static Fl_Menu_Item menu_osName[];
  Fl_Input *email;
  Fl_Input *purchaseConfirmationNumber;
  Fl_Button_gfc *sendButton;
  Fl_Text_Display *message;
  Fl_Box *needToPurchase;
  Fl_Button_gfc *buyButton;
  Fl_Button_gfc *saveButtonMainPage;
  Fl_Group *pageWaiting;
  Fl_Text_Display *waitingMessage;
  Fl_Button_gfc *cancelButton;
  Fl_Group *pageFailure;
  Fl_Text_Display *failureMessage;
  Fl_Button_gfc *saveButton;
  Fl_Button_gfc *tryAgainButton;
  Fl_Group *pageSuccess;
  Fl_Text_Display *successMessage;
  Fl_Group *pageSuccessSave;
  Fl_Text_Display *successMessageSave;
private:
  int x; 
};
#endif
