// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef drawingToolsWindow_h
#define drawingToolsWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Scroll.H>
#include <FLU/Flu_Tree_Browser.h>
extern void reviewToolsCB(Flu_Tree_Browser*, void*);
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Choice.H>

class DrawingToolsWindow : public Fl_Double_Window {
public:
  DrawingToolsWindow(int x, int y, int wi, int height,const char* l) ;
  Fl_Double_Window *drawingToolsWindow;
  Fl_Group *toolsGroup;
  Fl_Button *textButton;
  Fl_Button *drawButton;
  Fl_Button *aniLineButton;
  Fl_Text_Display *toolHelp;
  Fl_Scroll *bigScroll;
  Flu_Tree_Browser *revisionsTree;
  Flu_Tree_Browser *notesTree;
  Fl_Input *name;
  Fl_Value_Input *rangeStart;
  Fl_Value_Input *rangeEnd;
  Fl_Check_Button *alwaysOn;
  Fl_Box *color;
  Fl_Choice *quadrant;
  static Fl_Menu_Item menu_quadrant[];
  Fl_Input *size;
  Fl_Scroll *specificScroll;
};
#endif
