// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "drawingToolsWindow.h"
#include <FLU/Flu_Tree_Browser.h>

Fl_Menu_Item DrawingToolsWindow::menu_quadrant[] = {
 {"1", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"2", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"3", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"4", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
#include "UIConstants.h"
#include "UICallbacks.h"
#include <FLU/Flu_Tree_Browser.h>

DrawingToolsWindow::DrawingToolsWindow(int x, int y, int wi, int height,const char* l) : Fl_Double_Window(300, 300, 300, 300, "Load Window") {
  /*Fl_Double_Window* w;
  { Fl_Double_Window* o = drawingToolsWindow = new Fl_Double_Window(220, 720, "Review");
    w = o;
    o->box(FL_NO_BOX);
    o->color(FL_BLACK);
    o->labelcolor((Fl_Color)17);
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(-300, -10, 725, 787, "label");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
    }
    { Fl_Group* o = toolsGroup = new Fl_Group(11, 15, 195, 28, "Tools");
      o->box(FL_THIN_UP_FRAME);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      { Fl_Button* o = textButton = new Fl_Button(21, 21, 45, 16, "Text");
        o->type(1);
        o->box(FL_PLASTIC_DOWN_BOX);
        o->down_box(FL_PLASTIC_UP_BOX);
      }
      { Fl_Button* o = drawButton = new Fl_Button(71, 21, 55, 16, "Draw");
        o->type(1);
        o->box(FL_PLASTIC_DOWN_BOX);
        o->down_box(FL_PLASTIC_UP_BOX);
      }
      { Fl_Button* o = aniLineButton = new Fl_Button(131, 22, 60, 16, "AniLine");
        o->type(1);
        o->box(FL_PLASTIC_DOWN_BOX);
        o->down_box(FL_PLASTIC_UP_BOX);
      }
      o->end();
    }
    toolHelp = new Fl_Text_Display(11, 46, 195, 19);
    { Fl_Scroll* o = bigScroll = new Fl_Scroll(-15, 66, 236, 654);
      o->type(2);
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      { Fl_Group* o = new Fl_Group(10, 77, 190, 138, "Revisions");
        o->box(FL_THIN_DOWN_FRAME);
        o->color((Fl_Color)48);
        o->labelsize(10);
        o->labelcolor(FL_BACKGROUND2_COLOR);
        { Flu_Tree_Browser* o = revisionsTree = new Flu_Tree_Browser(16, 87, 180, 45, "Revisions");
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->callback((Fl_Callback*)reviewToolsCB, (void*)(REVIEWTOOLSREVIEWTREE_ID));
          o->align(FL_ALIGN_CENTER);
          o->when(FL_WHEN_RELEASE_ALWAYS);
        }
        { Fl_Button* o = new Fl_Button(160, 135, 35, 12, "Delete");
          o->labelsize(11);
        }
        { Fl_Button* o = new Fl_Button(17, 135, 35, 12, "New");
          o->labelsize(11);
        }
        { Fl_Button* o = new Fl_Button(56, 135, 39, 12, "Unlock");
          o->labelsize(11);
        }
        { Fl_Input* o = new Fl_Input(54, 152, 140, 17, "Author");
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(10);
        }
        { Fl_Output* o = new Fl_Output(84, 174, 110, 15, "Created");
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(10);
        }
        { Fl_Output* o = new Fl_Output(84, 195, 110, 15, "Last modified");
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(10);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(10, 232, 190, 117, "Notes");
        o->box(FL_THIN_DOWN_FRAME);
        o->color((Fl_Color)48);
        o->labelsize(10);
        o->labelcolor(FL_BACKGROUND2_COLOR);
        { Flu_Tree_Browser* o = notesTree = new Flu_Tree_Browser(11, 236, 186, 87);
          o->type(2);
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_FOREGROUND_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(1);
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->align(FL_ALIGN_TOP);
          o->when(FL_WHEN_RELEASE_ALWAYS);
        }
        { Fl_Button* o = new Fl_Button(161, 327, 35, 12, "Delete");
          o->labelsize(11);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(10, 368, 190, 192, "Common Attributes");
        o->box(FL_THIN_DOWN_FRAME);
        o->color((Fl_Color)48);
        o->labelsize(10);
        o->labelcolor(FL_BACKGROUND2_COLOR);
        { Fl_Input* o = name = new Fl_Input(55, 376, 120, 17, "Name");
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
        }
        { Fl_Value_Input* o = rangeStart = new Fl_Value_Input(15, 449, 35, 16);
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
        }
        { Fl_Value_Input* o = rangeEnd = new Fl_Value_Input(70, 449, 35, 16, ">");
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
        }
        { Fl_Check_Button* o = alwaysOn = new Fl_Check_Button(120, 449, 60, 16, "Always");
          o->down_box(FL_DOWN_BOX);
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
        }
        { Fl_Button* o = new Fl_Button(50, 449, 10, 17, "@8<");
          o->labelsize(9);
        }
        { Fl_Button* o = new Fl_Button(105, 449, 10, 18, "@8<");
          o->labelsize(9);
        }
        { Fl_Box* o = color = new Fl_Box(50, 474, 20, 16, "Color");
          o->box(FL_FLAT_BOX);
          o->color((Fl_Color)3);
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->align(FL_ALIGN_LEFT);
        }
        { Fl_Choice* o = quadrant = new Fl_Choice(50, 425, 27, 15, "Quad");
          o->down_box(FL_BORDER_BOX);
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->menu(menu_quadrant);
        }
        { Fl_Input* o = size = new Fl_Input(110, 423, 25, 18, "Size");
          o->type(2);
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
        }
        new Fl_Text_Display(15, 500, 165, 50);
        { Fl_Value_Input* o = new Fl_Value_Input(60, 401, 30, 13, "Position");
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(10);
        }
        { Fl_Value_Input* o = new Fl_Value_Input(100, 401, 30, 13);
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(10);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(10, 576, 190, 124, "Tool Specifics");
        o->box(FL_THIN_DOWN_FRAME);
        o->color((Fl_Color)48);
        o->labelsize(10);
        o->labelcolor(FL_BACKGROUND2_COLOR);
        { Fl_Scroll* o = specificScroll = new Fl_Scroll(12, 578, 186, 121);
          o->type(2);
          o->box(FL_FLAT_BOX);
          o->color(FL_FOREGROUND_COLOR);
          o->labelsize(10);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->end();
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->set_non_modal();
    o->size_range(220, 300, 220, 720);
    o->end();
  }*/
}
