// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "exrWindow.h"
#include "UIConstants.h"
#include "UICallbacks.h"

ExrWindow::ExrWindow(int x, int y, int wi, int height,const char* l) : Fl_Double_Window(300, 300, 300, 300, "Load Window") {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = exrWindow = new Fl_Double_Window(315, 280, "OpenEXR Parameters");
    w = o;
    o->color(FL_BLACK);
    o->labelcolor((Fl_Color)17);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    { Fl_Group* o = new Fl_Group(0, 1, 310, 271);
      o->labelcolor((Fl_Color)19);
      { Fl_Value_Slider* o = exposureSlider = new Fl_Value_Slider(68, 10, 204, 20, "Exposure");
        o->type(1);
        o->labelsize(12);
        o->labelcolor((Fl_Color)19);
        o->minimum(-10);
        o->maximum(10);
        o->step(0.1);
        o->value(1);
        o->textsize(14);
        o->callback((Fl_Callback*)loadCB, (void*)(LOADEXR_ID));
        o->align(FL_ALIGN_LEFT);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Value_Slider* o = defogSlider = new Fl_Value_Slider(68, 34, 204, 21, "Defog");
        o->type(1);
        o->labelsize(12);
        o->labelcolor((Fl_Color)19);
        o->maximum(0.001);
        o->step(0.0001);
        o->textsize(11);
        o->callback((Fl_Callback*)loadCB, (void*)(LOADEXR_ID));
        o->align(FL_ALIGN_LEFT);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Value_Slider* o = kneeLowSlider = new Fl_Value_Slider(68, 60, 204, 21, "Knee low");
        o->type(1);
        o->labelsize(12);
        o->labelcolor((Fl_Color)19);
        o->minimum(-3);
        o->maximum(3);
        o->step(0.01);
        o->textsize(14);
        o->callback((Fl_Callback*)loadCB, (void*)(LOADEXR_ID));
        o->align(FL_ALIGN_LEFT);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Value_Slider* o = kneeHighSlider = new Fl_Value_Slider(68, 85, 204, 21, "Knee high");
        o->type(1);
        o->labelsize(12);
        o->labelcolor((Fl_Color)19);
        o->minimum(-3);
        o->maximum(3);
        o->step(0.01);
        o->textsize(14);
        o->callback((Fl_Callback*)loadCB, (void*)(LOADEXR_ID));
        o->align(FL_ALIGN_LEFT);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Group* o = new Fl_Group(13, 148, 287, 108, "Channels");
        o->box(FL_UP_FRAME);
        o->labelcolor((Fl_Color)28);
        { Fl_Choice* o = exrTrackA = new Fl_Choice(76, 158, 200, 20, "Track A");
          o->down_box(FL_BORDER_BOX);
          o->labelcolor((Fl_Color)36);
          o->callback((Fl_Callback*)loadCB, (void*)(EXRTRACKA_ID));
        }
        { Fl_Choice* o = exrTrackB = new Fl_Choice(76, 180, 200, 20, "Track B");
          o->down_box(FL_BORDER_BOX);
          o->labelcolor((Fl_Color)36);
          o->callback((Fl_Callback*)loadCB, (void*)(EXRTRACKB_ID));
        }
        { Fl_Choice* o = exrTrackC = new Fl_Choice(76, 201, 200, 20, "Track C");
          o->down_box(FL_BORDER_BOX);
          o->labelcolor((Fl_Color)36);
          o->callback((Fl_Callback*)loadCB, (void*)(EXRTRACKC_ID));
        }
        { Fl_Choice* o = exrTrackD = new Fl_Choice(76, 222, 200, 20, "Track D");
          o->down_box(FL_BORDER_BOX);
          o->labelcolor((Fl_Color)36);
          o->callback((Fl_Callback*)loadCB, (void*)(EXRTRACKD_ID));
        }
        o->end();
      }
      { Fl_Choice* o = exrPreview = new Fl_Choice(68, 110, 204, 20, "Preview");
        o->down_box(FL_BORDER_BOX);
        o->labelcolor((Fl_Color)36);
        o->callback((Fl_Callback*)loadCB, (void*)(EXRPREVIEW_ID));
      }
      o->end();
    }
    o->set_non_modal();
    o->size_range(300, 265, 300, 265);
    o->end();
  }
}
