// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef exrWindow_h
#define exrWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>
extern void loadCB(Fl_Value_Slider*, void*);
#include <FL/Fl_Choice.H>
extern void loadCB(Fl_Choice*, void*);

class ExrWindow : public Fl_Double_Window {
public:
  ExrWindow(int x, int y, int wi, int height,const char* l) ;
  Fl_Double_Window *exrWindow;
  Fl_Value_Slider *exposureSlider;
  Fl_Value_Slider *defogSlider;
  Fl_Value_Slider *kneeLowSlider;
  Fl_Value_Slider *kneeHighSlider;
  Fl_Choice *exrTrackA;
  Fl_Choice *exrTrackB;
  Fl_Choice *exrTrackC;
  Fl_Choice *exrTrackD;
  Fl_Choice *exrPreview;
};
#endif
