// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "fxWindow.h"
#include "UIConstants.h"
#include "UICallbacks.h"

FXWindow::FXWindow(int x, int y, int wi, int height,const char* l) : Fl_Double_Window(300, 300, 300, 300, "Load Window") {
  { fxWindow = new Fl_Double_Window(515, 430, "FX Manager");
    fxWindow->box(FL_NO_BOX);
    fxWindow->color(FL_BLACK);
    fxWindow->labelcolor((Fl_Color)17);
    fxWindow->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, -4, 1675, 982, "label");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)30);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(0, -16, 1542, 1121);
      o->labelcolor((Fl_Color)19);
      { Fl_Group* o = new Fl_Group(5, 27, 505, 39, "Load");
        o->box(FL_BORDER_FRAME);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(18);
        o->labelcolor((Fl_Color)31);
        o->callback((Fl_Callback*)loadCB);
        o->align(FL_ALIGN_TOP_LEFT);
        { fileNameInput = new Fl_File_Input(40, 37, 403, 27, "File");
          fileNameInput->color(FL_FOREGROUND_COLOR);
          fileNameInput->labelsize(12);
          fileNameInput->labelcolor((Fl_Color)19);
          fileNameInput->user_data((void*)(LOADFILENAME_ID));
          fileNameInput->when(FL_WHEN_CHANGED);
          fileNameInput->hide();
          fileNameInput->deactivate();
        } // Fl_File_Input* fileNameInput
        { browseButton = new Fl_Button_gfc(447, 32, 58, 27, "Browse");
          browseButton->box(FL_FLAT_BOX);
          browseButton->down_box(FL_FLAT_BOX);
          browseButton->color(FL_INACTIVE_COLOR);
          browseButton->selection_color(FL_BACKGROUND_COLOR);
          browseButton->labeltype(FL_NORMAL_LABEL);
          browseButton->labelfont(0);
          browseButton->labelsize(12);
          browseButton->labelcolor((Fl_Color)31);
          browseButton->callback((Fl_Callback*)fxManagerCB_OTHERS, (void*)(FXBROWSE_ID));
          browseButton->align(FL_ALIGN_CENTER);
          browseButton->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* browseButton
        { progress = new Fl_Progress(11, 34, 430, 25);
          progress->box(FL_FLAT_BOX);
          progress->color(FL_FOREGROUND_COLOR);
          progress->selection_color((Fl_Color)59);
          progress->labelcolor((Fl_Color)31);
        } // Fl_Progress* progress
        o->end();
      } // Fl_Group* o
      { doneButton = new Fl_Button_gfc(405, 388, 95, 27, "Done");
        doneButton->tooltip("Start Loading!");
        doneButton->box(FL_FLAT_BOX);
        doneButton->down_box(FL_FLAT_BOX);
        doneButton->color(FL_INACTIVE_COLOR);
        doneButton->selection_color(FL_BACKGROUND_COLOR);
        doneButton->labeltype(FL_NORMAL_LABEL);
        doneButton->labelfont(1);
        doneButton->labelsize(21);
        doneButton->labelcolor((Fl_Color)31);
        doneButton->callback((Fl_Callback*)fxManagerCB_OTHERS, (void*)(FXDONE_ID));
        doneButton->align(FL_ALIGN_CENTER);
        doneButton->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* doneButton
      { Fl_Group* o = new Fl_Group(26, 414, 80, 80);
        o->align(FL_ALIGN_CENTER);
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(9, 108, 493, 272);
        { Fl_Scroll* o = scrollLoaded = new Fl_Scroll(9, 108, 493, 272, "Loaded");
          scrollLoaded->type(2);
          scrollLoaded->box(FL_FLAT_BOX);
          scrollLoaded->color(FL_INACTIVE_COLOR);
          scrollLoaded->selection_color((Fl_Color)79);
          scrollLoaded->labelfont(1);
          scrollLoaded->labelsize(18);
          scrollLoaded->labelcolor((Fl_Color)31);
          scrollLoaded->align(FL_ALIGN_TOP_LEFT);
          o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
          scrollLoaded->end();
        } // Fl_Scroll* scrollLoaded
        o->end();
      } // Fl_Group* o
      { autoLoadAllButton = new Fl_Check_Button(370, 88, 15, 15, "Auto-Load All");
        autoLoadAllButton->down_box(FL_FLAT_BOX);
        autoLoadAllButton->color(FL_INACTIVE_COLOR);
        autoLoadAllButton->selection_color((Fl_Color)31);
        autoLoadAllButton->labelcolor(FL_LIGHT1);
        autoLoadAllButton->callback((Fl_Callback*)fxManagerCB_OTHERS, (void*)(FXAUTOLOADALL_ID));
        autoLoadAllButton->align(FL_ALIGN_RIGHT);
      } // Fl_Check_Button* autoLoadAllButton
      { Fl_Button_gfc* o = new Fl_Button_gfc(287, 85, 78, 20, "Unload All");
        o->box(FL_FLAT_BOX);
        o->down_box(FL_FLAT_BOX);
        o->color(FL_INACTIVE_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor((Fl_Color)31);
        o->callback((Fl_Callback*)fxManagerCB_OTHERS, (void*)(FXUNLOADALL_ID));
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* o
      o->end();
    } // Fl_Group* o
    fxWindow->set_non_modal();
    fxWindow->size_range(515, 430, 515, 430);
    fxWindow->end();
  } // Fl_Double_Window* fxWindow
}
