// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef fxWindow_h
#define fxWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
extern void loadCB(Fl_Group*, void*);
#include <FL/Fl_File_Input.H>
#include "gfcfxmanager.h"
#include "Fl_Button_gfc.h"
extern void fxManagerCB_OTHERS(Fl_Button_gfc*, long);
#include <FL/Fl_Progress.H>
extern void fxManagerCB_OTHERS(Fl_Button_gfc*, void*);
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Check_Button.H>
extern void fxManagerCB_OTHERS(Fl_Check_Button*, void*);

class FXWindow : public Fl_Double_Window {
public:
  FXWindow(int x, int y, int wi, int height,const char* l) ;
  Fl_Double_Window *fxWindow;
  Fl_File_Input *fileNameInput;
  Fl_Button_gfc *browseButton;
  Fl_Progress *progress;
  Fl_Button_gfc *doneButton;
  Fl_Scroll *scrollLoaded;
  Fl_Check_Button *autoLoadAllButton;
};
#endif
