// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef gammaWindow_h
#define gammaWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern void loadCB(Fl_Double_Window*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
extern void gammaCB(Fl_Button*, void*);
#include <FL/Fl_Value_Slider.H>
extern void gammaCB(Fl_Value_Slider*, void*);
#include <FL/Fl_Check_Button.H>
extern void gammaCB(Fl_Check_Button*, void*);

class GammaWindow : public Fl_Double_Window {
public:
  GammaWindow(int x, int y, int wi, int height,const char* l) ;
  Fl_Double_Window *gammaWindow;
  Fl_Button *doneButton;
  Fl_Value_Slider *gammaBar;
  Fl_Value_Slider *gammaRBar;
  Fl_Value_Slider *gammaGBar;
  Fl_Value_Slider *gammaBBar;
  Fl_Check_Button *byColorCheckBox;
};
#endif
