// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "gammaWindow.h"
#include "UIConstants.h"
#include "UICallbacks.h"

GammaWindow::GammaWindow(int x, int y, int wi, int height,const char* l) : Fl_Double_Window(300, 300, 300, 300, "Load Window") {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = gammaWindow = new Fl_Double_Window(840, 610, "Gamma Adjustment");
    w = o;
    o->box(FL_NO_BOX);
    o->color(FL_BLACK);
    o->labelcolor((Fl_Color)17);
    o->callback((Fl_Callback*)loadCB, (void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 1025, 778, "label");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
    }
    new Fl_Box(175, 53, 540, 362, "Gamma Chart");
    { Fl_Button* o = doneButton = new Fl_Button(744, 578, 64, 17, "Done");
      o->color(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)gammaCB, (void*)(GAMMADONE_ID));
    }
    { Fl_Value_Slider* o = gammaBar = new Fl_Value_Slider(195, 472, 617, 20, "Gamma:");
      o->type(1);
      o->labelcolor((Fl_Color)31);
      o->maximum(2);
      o->step(0.01);
      o->value(1);
      o->textsize(14);
      o->callback((Fl_Callback*)gammaCB, (void*)(GAMMAGLOBAL_ID));
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Value_Slider* o = gammaRBar = new Fl_Value_Slider(197, 512, 614, 20, "Red Gamma");
      o->type(1);
      o->labelcolor((Fl_Color)31);
      o->maximum(2);
      o->step(0.01);
      o->value(1);
      o->textsize(14);
      o->callback((Fl_Callback*)gammaCB, (void*)(GAMMAGLOBAL_ID));
      o->align(FL_ALIGN_LEFT);
      o->deactivate();
    }
    { Fl_Value_Slider* o = gammaGBar = new Fl_Value_Slider(197, 532, 614, 20, "Green Gamma");
      o->type(1);
      o->labelcolor((Fl_Color)31);
      o->maximum(2);
      o->step(0.01);
      o->value(1);
      o->textsize(14);
      o->callback((Fl_Callback*)gammaCB, (void*)(GAMMAGLOBAL_ID));
      o->align(FL_ALIGN_LEFT);
      o->deactivate();
    }
    { Fl_Value_Slider* o = gammaBBar = new Fl_Value_Slider(197, 552, 614, 20, "Blue Gamma");
      o->type(1);
      o->labelcolor((Fl_Color)31);
      o->maximum(2);
      o->step(0.01);
      o->value(1);
      o->textsize(14);
      o->callback((Fl_Callback*)gammaCB, (void*)(GAMMAGLOBAL_ID));
      o->align(FL_ALIGN_LEFT);
      o->deactivate();
    }
    { Fl_Check_Button* o = byColorCheckBox = new Fl_Check_Button(120, 495, 64, 15, "By Color");
      o->down_box(FL_DOWN_BOX);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->callback((Fl_Callback*)gammaCB, (void*)(GAMMABYCOLOR_ID));
    }
    o->size_range(840, 610, 840, 610);
    o->end();
  }
}
