// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "loadWindow.h"

Fl_Menu_Item LoadWindow::menu_filterChooserA[] = {
 {"Linear (Ugly-fastest)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"BiLinear (Better-slower)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_scaleChooserA[] = {
 {"100", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"50", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"25", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_formatA[] = {
 {"8bpc", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"16bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"HALF", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"4bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"S3TC", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_loadModeA[] = {
 {"Replace", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Ignore", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Stream", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_filterChooserB[] = {
 {"Linear (Ugly-fastest)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"BiLinear (Better-slower)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_scaleChooserB[] = {
 {"100", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"50", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"25", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_formatB[] = {
 {"8bpc", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"16bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"HALF", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"4bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"S3TC", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_loadModeB[] = {
 {"Replace", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Ignore", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Stream", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_filterChooserC[] = {
 {"Linear (Ugly-fastest)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"BiLinear (Better-slower)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_scaleChooserC[] = {
 {"100", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"50", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"25", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_formatC[] = {
 {"8bpc", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"16bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"HALF", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"4bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"S3TC", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_loadModeC[] = {
 {"Replace", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Ignore", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Stream", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_filterChooserD[] = {
 {"Linear (Ugly-fastest)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"BiLinear (Better-slower)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_scaleChooserD[] = {
 {"100", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"50", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"25", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_formatD[] = {
 {"8bpc", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"16bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"HALF", 0,  0, 0, 128, FL_NORMAL_LABEL, 0, 12, 0},
 {"4bpc", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {"S3TC", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LoadWindow::menu_loadModeD[] = {
 {"Replace", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Ignore", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"Stream", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

#include <FL/Fl_Image.H>
static unsigned char idata_AddToPlaylistIcon[] =
{255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,
255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,
255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,
255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,255,
255,255,0,255,255,255,0,255,255,255,0,255,255,255,0,154,154,154,6,154,154,154,
19,155,155,155,17,155,155,155,3,155,155,155,9,155,155,155,19,155,155,155,17,
155,155,155,17,155,155,155,17,155,155,155,17,155,155,155,17,155,155,155,17,155,
155,155,18,155,155,155,14,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,
0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,255,255,255,0,154,154,154,83,154,154,154,254,155,155,155,230,155,155,
155,38,155,155,155,127,155,155,155,255,155,155,155,241,155,155,155,241,155,155,
155,241,155,155,155,241,155,155,155,241,155,155,155,241,155,155,155,255,155,155,
155,194,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,255,
255,0,154,154,154,90,155,155,155,255,155,155,155,251,155,155,155,42,155,155,155,
128,155,155,155,255,155,155,155,244,155,155,155,244,155,155,155,244,155,155,155,
244,155,155,155,244,155,155,155,244,155,155,155,255,155,155,155,195,155,155,155,
0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,255,255,0,153,153,153,
13,155,155,155,41,155,155,155,37,155,155,155,6,155,155,155,15,155,155,155,32,
155,155,155,29,155,155,155,29,155,155,155,29,155,155,155,29,155,155,155,29,155,
155,155,29,155,155,155,31,155,155,155,23,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,255,255,255,0,155,155,155,34,155,155,155,105,155,155,
155,95,155,155,155,16,155,155,155,53,155,155,155,110,155,155,155,100,155,155,
155,100,155,155,155,100,155,155,155,100,155,155,155,100,155,155,155,100,155,155,
155,107,155,155,155,80,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,0,255,255,255,0,155,155,155,99,155,155,155,255,155,155,155,255,155,155,155,
45,155,155,155,153,155,155,155,255,155,155,155,255,155,155,155,255,155,155,155,
255,155,155,155,255,155,155,155,255,155,155,155,255,155,155,155,255,155,155,155,
232,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,255,255,0,
155,155,155,50,155,155,155,155,155,155,155,140,155,155,155,25,155,155,155,63,
155,155,155,132,155,155,155,121,155,155,155,121,155,155,155,121,155,155,155,121,
155,155,155,121,155,155,155,121,155,155,155,129,155,155,155,97,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,255,255,0,155,155,155,8,155,
155,155,24,155,155,155,22,155,155,155,4,155,155,155,7,155,155,155,15,155,155,
155,14,155,155,155,14,155,155,155,14,155,155,155,14,155,155,155,14,155,155,155,
14,155,155,155,15,155,155,155,11,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,255,255,255,0,155,155,155,86,155,155,155,255,155,155,155,237,155,
155,155,39,155,155,155,132,155,155,155,255,155,155,155,250,155,155,155,250,155,
155,155,250,155,155,155,250,155,155,155,250,155,155,155,250,155,155,155,255,155,
155,155,201,155,155,155,1,155,155,155,12,155,155,155,15,155,155,155,13,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,
255,255,0,155,155,155,84,155,155,155,255,155,155,155,232,155,155,155,38,155,155,
155,122,155,155,155,254,155,155,155,232,155,155,155,232,155,155,155,232,155,155,
155,232,155,155,155,232,155,155,155,232,155,155,155,248,155,155,155,186,155,155,
155,18,155,155,155,168,155,155,155,212,155,155,155,191,155,155,155,10,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,255,255,0,155,
155,155,11,155,155,155,34,155,155,155,30,155,155,155,5,155,155,155,13,155,155,
155,29,155,155,155,26,155,155,155,26,155,155,155,26,155,155,155,26,155,155,155,
26,155,155,155,26,155,155,155,28,155,155,155,21,155,155,155,25,155,155,155,227,
155,155,155,255,155,155,155,255,155,155,155,13,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,255,255,255,0,155,155,155,37,155,155,155,
112,155,155,155,101,155,155,155,17,155,155,155,56,155,155,155,116,155,155,155,
106,155,155,155,106,155,155,155,106,155,155,155,106,155,155,155,106,155,155,155,
106,155,155,155,113,155,155,155,85,155,155,155,24,155,155,155,216,155,155,155,
255,155,155,155,246,155,155,155,13,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,255,255,255,0,155,155,155,100,155,155,155,255,155,
155,155,255,155,155,155,45,155,155,155,153,155,155,155,255,155,155,155,255,155,
155,155,255,155,155,155,255,155,155,155,255,155,155,155,255,155,155,155,255,155,
155,155,255,155,155,155,232,155,155,155,25,155,155,155,217,155,155,155,255,155,
155,155,247,155,155,155,14,155,155,155,0,155,155,155,1,155,155,155,1,155,155,
155,1,155,155,155,1,255,255,255,0,155,155,155,50,155,155,155,153,155,155,155,
139,155,155,155,23,155,155,155,71,155,155,155,148,155,155,155,135,155,155,155,
135,155,155,155,135,155,155,155,135,155,155,155,135,155,155,155,135,155,155,155,
144,155,155,155,108,155,155,155,16,155,155,155,216,155,155,155,255,155,155,155,
247,155,155,155,4,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,255,255,255,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,27,155,155,155,42,155,155,155,38,155,155,155,38,155,155,155,26,155,155,155,
59,155,155,155,222,155,155,155,255,155,155,155,248,155,155,155,49,155,155,155,
29,155,155,155,38,155,155,155,38,155,155,155,40,155,155,155,28,255,255,255,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,1,155,155,155,0,155,155,155,164,155,155,155,251,
155,155,155,229,155,155,155,229,155,155,155,228,155,155,155,231,155,155,155,251,
155,155,155,255,155,155,155,254,155,155,155,230,155,155,155,228,155,155,155,229,
155,155,155,229,155,155,155,241,155,155,155,172,255,255,255,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,1,155,155,155,0,155,155,155,203,155,155,155,255,155,155,155,255,155,
155,155,255,155,155,155,255,155,155,155,255,155,155,155,255,155,155,155,252,155,
155,155,255,155,155,155,255,155,155,155,255,155,155,155,255,155,155,155,255,155,
155,155,255,155,155,155,213,255,255,255,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,138,155,155,155,211,155,155,155,193,155,155,155,193,155,
155,155,189,155,155,155,199,155,155,155,245,155,155,155,255,155,155,155,253,155,
155,155,196,155,155,155,190,155,155,155,193,155,155,155,193,155,155,155,203,155,
155,155,145,255,255,255,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,
0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,11,155,155,155,17,155,155,155,16,155,155,155,16,155,155,155,3,155,155,
155,38,155,155,155,219,155,155,155,255,155,155,155,247,155,155,155,28,155,155,
155,6,155,155,155,16,155,155,155,16,155,155,155,17,155,155,155,12,255,255,255,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,20,155,155,155,216,155,155,
155,255,155,155,155,247,155,155,155,8,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,255,255,255,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,24,155,155,155,217,155,155,155,255,155,155,155,247,155,155,155,13,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,255,255,
255,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,24,155,155,155,219,155,
155,155,255,155,155,155,249,155,155,155,13,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,255,255,255,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,25,155,155,155,229,155,155,155,255,155,155,155,255,155,155,
155,13,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,
255,255,255,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,
155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,
155,155,0,155,155,155,0,155,155,155,0,155,155,155,0,155,155,155,14,155,155,155,
132,155,155,155,166,155,155,155,150,155,155,155,7,155,155,155,0,155,155,155,0,
155,155,155,0,155,155,155,0,155,155,155,0};
static Fl_RGB_Image image_AddToPlaylistIcon(idata_AddToPlaylistIcon, 25, 25, 4, 0);
#include "UIConstants.h"
#include "Fl_DragBar.H"
#include "UICallbacks.h"
#include "Fl_Button_gfc.h"
#include "gfcSliderInput.h"

LoadWindow::LoadWindow(int x, int y, int wi, int height,const char* l) : Fl_Double_Window(300, 300, 300, 300, "Load Window") {
  { loadWindow = new Fl_Double_Window(750, 335, "Load Window");
    loadWindow->box(FL_NO_BOX);
    loadWindow->color(FL_BLACK);
    loadWindow->labelcolor((Fl_Color)17);
    loadWindow->user_data((void*)(this));
    { Fl_Box* o = bgBOX = new Fl_Box(0, -4, 753, 377);
      bgBOX->box(FL_FLAT_BOX);
      bgBOX->color(FL_FOREGROUND_COLOR);
      o->color(fl_rgb_color(27,27,27));
    } // Fl_Box* bgBOX
    { Fl_DragBar* o = new Fl_DragBar(0, 0, 750, 377, ".");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)38);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      o->type(Fl_DragBar::WINDRAG);
      //o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_DragBar* o
    { frame = new Fl_Group(2, 1, 746, 332);
      frame->box(FL_BORDER_FRAME);
      frame->color(FL_INACTIVE_COLOR);
      frame->labelcolor((Fl_Color)19);
      { groupA = new Fl_Group(7, 16, 365, 130);
        groupA->box(FL_BORDER_FRAME);
        groupA->color(FL_INACTIVE_COLOR);
        groupA->labelcolor(FL_BACKGROUND2_COLOR);
        groupA->callback((Fl_Callback*)loadCB);
        { loadFromSpinnerA = new gfcSliderInput(38, 50, 180, 15, "In");
          loadFromSpinnerA->type(5);
          loadFromSpinnerA->box(FL_DOWN_BOX);
          loadFromSpinnerA->color(FL_FOREGROUND_COLOR);
          loadFromSpinnerA->selection_color(FL_BACKGROUND_COLOR);
          loadFromSpinnerA->labeltype(FL_NORMAL_LABEL);
          loadFromSpinnerA->labelfont(0);
          loadFromSpinnerA->labelsize(12);
          loadFromSpinnerA->labelcolor((Fl_Color)31);
          loadFromSpinnerA->step(1);
          loadFromSpinnerA->textsize(9);
          loadFromSpinnerA->callback((Fl_Callback*)loadCB, (void*)(LOADFROM_ID));
          loadFromSpinnerA->align(FL_ALIGN_LEFT);
          loadFromSpinnerA->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadFromSpinnerA
        { loadToSpinnerA = new gfcSliderInput(38, 66, 180, 15, "Out");
          loadToSpinnerA->type(5);
          loadToSpinnerA->box(FL_DOWN_BOX);
          loadToSpinnerA->color(FL_FOREGROUND_COLOR);
          loadToSpinnerA->selection_color(FL_BACKGROUND_COLOR);
          loadToSpinnerA->labeltype(FL_NORMAL_LABEL);
          loadToSpinnerA->labelfont(0);
          loadToSpinnerA->labelsize(12);
          loadToSpinnerA->labelcolor((Fl_Color)31);
          loadToSpinnerA->step(1);
          loadToSpinnerA->textsize(9);
          loadToSpinnerA->callback((Fl_Callback*)loadCB, (void*)(LOADTO_ID));
          loadToSpinnerA->align(FL_ALIGN_LEFT);
          loadToSpinnerA->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadToSpinnerA
        { filterChooserA = new Fl_Choice_gfc(73, 99, 91, 18, "Filter");
          filterChooserA->tooltip("Filter to apply on the scaled images");
          filterChooserA->box(FL_FLAT_BOX);
          filterChooserA->down_box(FL_BORDER_BOX);
          filterChooserA->color(FL_FOREGROUND_COLOR);
          filterChooserA->selection_color(FL_SELECTION_COLOR);
          filterChooserA->labeltype(FL_NORMAL_LABEL);
          filterChooserA->labelfont(0);
          filterChooserA->labelsize(10);
          filterChooserA->labelcolor(FL_BACKGROUND2_COLOR);
          filterChooserA->textsize(10);
          filterChooserA->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          filterChooserA->align(FL_ALIGN_TOP);
          filterChooserA->when(FL_WHEN_RELEASE);
          filterChooserA->menu(menu_filterChooserA);
        } // Fl_Choice_gfc* filterChooserA
        { browseButtonA = new Fl_Button_gfc(292, 24, 70, 20, "Browse");
          browseButtonA->box(FL_UP_BOX);
          browseButtonA->color(FL_FOREGROUND_COLOR);
          browseButtonA->selection_color(FL_BACKGROUND_COLOR);
          browseButtonA->labeltype(FL_NORMAL_LABEL);
          browseButtonA->labelfont(0);
          browseButtonA->labelsize(11);
          browseButtonA->labelcolor(FL_BACKGROUND2_COLOR);
          browseButtonA->callback((Fl_Callback*)loadCB, (void*)(LOADBROWSE_ID));
          browseButtonA->align(FL_ALIGN_CENTER);
          browseButtonA->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* browseButtonA
        { Fl_Input_Choice_gfc* o = scaleChooserA = new Fl_Input_Choice_gfc(12, 99, 53, 18, "Scale");
          scaleChooserA->tooltip("Loaded images will be scaled down to this percent");
          scaleChooserA->box(FL_DOWN_BOX);
          scaleChooserA->down_box(FL_BORDER_BOX);
          scaleChooserA->color((Fl_Color)37);
          scaleChooserA->selection_color(FL_BACKGROUND_COLOR);
          scaleChooserA->labeltype(FL_NORMAL_LABEL);
          scaleChooserA->labelfont(0);
          scaleChooserA->labelsize(10);
          scaleChooserA->labelcolor(FL_BACKGROUND2_COLOR);
          scaleChooserA->textsize(12);
          scaleChooserA->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          scaleChooserA->align(FL_ALIGN_TOP);
          scaleChooserA->when(FL_WHEN_RELEASE);
          scaleChooserA->menu(menu_scaleChooserA);
          o->value(0);
          o->textcolor(fl_rgb_color(85,85,85));
        } // Fl_Input_Choice_gfc* scaleChooserA
        { reloadButtonA = new Fl_Button(262, 51, 24, 25);
          reloadButtonA->color(FL_FOREGROUND_COLOR);
          reloadButtonA->labelsize(12);
          reloadButtonA->labelcolor(FL_BACKGROUND2_COLOR);
          reloadButtonA->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATE_ID));
          reloadButtonA->hide();
        } // Fl_Button* reloadButtonA
        { Fl_Check_Button* o = cropA = new Fl_Check_Button(200, 87, 18, 18, "Crop");
          cropA->tooltip("Enable cropping the image, once enabled, right click and shift+right click on\
 the preview to select the Area of Interest to load");
          cropA->down_box(FL_FLAT_BOX);
          cropA->color(FL_INACTIVE_COLOR);
          cropA->selection_color((Fl_Color)31);
          cropA->labelsize(10);
          cropA->labelcolor((Fl_Color)31);
          cropA->callback((Fl_Callback*)loadCB);
          cropA->align(FL_ALIGN_LEFT);
          o->labelcolor(fl_rgb_color(160,160,160));
        } // Fl_Check_Button* cropA
        { gammaSliderA = new Fl_Value_Input(222, 58, 27, 20, "Gamma");
          gammaSliderA->labelsize(12);
          gammaSliderA->labelcolor(FL_BACKGROUND2_COLOR);
          gammaSliderA->maximum(3);
          gammaSliderA->step(0.1);
          gammaSliderA->value(1);
          gammaSliderA->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          gammaSliderA->when(FL_WHEN_RELEASE);
          gammaSliderA->hide();
        } // Fl_Value_Input* gammaSliderA
        { formatA = new Fl_Choice_gfc(170, 125, 56, 16, "Bit Depth");
          formatA->tooltip("Special Formats can determine the quality/memory ratio.");
          formatA->box(FL_FLAT_BOX);
          formatA->down_box(FL_BORDER_BOX);
          formatA->color(FL_FOREGROUND_COLOR);
          formatA->selection_color(FL_SELECTION_COLOR);
          formatA->labeltype(FL_NORMAL_LABEL);
          formatA->labelfont(0);
          formatA->labelsize(10);
          formatA->labelcolor(FL_BACKGROUND2_COLOR);
          formatA->textsize(12);
          formatA->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          formatA->align(FL_ALIGN_TOP);
          formatA->when(FL_WHEN_RELEASE);
          formatA->menu(menu_formatA);
        } // Fl_Choice_gfc* formatA
        { Fl_Menu_Button* o = recentButtonA = new Fl_Menu_Button(263, 26, 27, 17, "@2>");
          recentButtonA->box(FL_FLAT_BOX);
          recentButtonA->down_box(FL_FLAT_BOX);
          recentButtonA->color(FL_INACTIVE_COLOR);
          recentButtonA->labelcolor((Fl_Color)31);
          recentButtonA->textcolor(31);
          recentButtonA->callback((Fl_Callback*)loadCB, (void*)(LOADRECENT_ID));
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Menu_Button* recentButtonA
        { Fl_Output* o = new Fl_Output(172, 25, 195, 18, "Sequence");
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
          o->when(FL_WHEN_CHANGED);
          o->hide();
        } // Fl_Output* o
        { Fl_Input* o = fileNameInputA = new Fl_Input(75, 26, 187, 17, "Sequence");
          fileNameInputA->box(FL_FLAT_BOX);
          fileNameInputA->color(FL_INACTIVE_COLOR);
          fileNameInputA->labelsize(12);
          fileNameInputA->labelcolor((Fl_Color)31);
          fileNameInputA->textsize(12);
          fileNameInputA->callback((Fl_Callback*)loadCB, (void*)(LOADFILENAME_ID));
          fileNameInputA->when(FL_WHEN_CHANGED);
          fileNameInputA->deactivate();
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* fileNameInputA
        { Fl_Choice_gfc* o = loadModeA = new Fl_Choice_gfc(170, 126, 64, 15, "Mode");
          loadModeA->tooltip("Specifies how this track will be treated whn you hit the START button. It can\
 replace what was there or it can ignore changes and leave everything the way \
it is");
          loadModeA->box(FL_FLAT_BOX);
          loadModeA->down_box(FL_BORDER_BOX);
          loadModeA->color(FL_FOREGROUND_COLOR);
          loadModeA->selection_color(FL_SELECTION_COLOR);
          loadModeA->labeltype(FL_NORMAL_LABEL);
          loadModeA->labelfont(0);
          loadModeA->labelsize(10);
          loadModeA->labelcolor(FL_BACKGROUND2_COLOR);
          loadModeA->textsize(10);
          loadModeA->align(FL_ALIGN_LEFT);
          loadModeA->when(FL_WHEN_RELEASE);
          loadModeA->hide();
          loadModeA->menu(menu_loadModeA);
          o->value(0);
        } // Fl_Choice_gfc* loadModeA
        { Fl_Output* o = estimatesA = new Fl_Output(225, 48, 140, 55);
          estimatesA->tooltip("Shows information on memory usage and load times");
          estimatesA->type(12);
          estimatesA->box(FL_BORDER_BOX);
          estimatesA->color(FL_INACTIVE_COLOR);
          estimatesA->selection_color(FL_FOREGROUND_COLOR);
          estimatesA->labelsize(10);
          estimatesA->labelcolor(FL_BACKGROUND2_COLOR);
          estimatesA->textsize(10);
          estimatesA->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Output* estimatesA
        { unloadAndClearA = new Fl_Button_gfc(252, 109, 27, 27, "@3+");
          unloadAndClearA->box(FL_UP_BOX);
          unloadAndClearA->color(FL_FOREGROUND_COLOR);
          unloadAndClearA->selection_color(FL_BACKGROUND_COLOR);
          unloadAndClearA->labeltype(FL_NORMAL_LABEL);
          unloadAndClearA->labelfont(0);
          unloadAndClearA->labelsize(12);
          unloadAndClearA->labelcolor((Fl_Color)1);
          unloadAndClearA->callback((Fl_Callback*)loadCB, (void*)(LOADUNLOADANDCLEAR_ID));
          unloadAndClearA->align(FL_ALIGN_CENTER);
          unloadAndClearA->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* unloadAndClearA
        { channelsChoiceA = new Fl_Choice_gfc(60, 125, 100, 15, "Channels");
          channelsChoiceA->tooltip("When working with multi channel images (such as OpenEXR), you can choose what\
 channel to load");
          channelsChoiceA->box(FL_FLAT_BOX);
          channelsChoiceA->down_box(FL_BORDER_BOX);
          channelsChoiceA->color(FL_FOREGROUND_COLOR);
          channelsChoiceA->selection_color(FL_SELECTION_COLOR);
          channelsChoiceA->labeltype(FL_NORMAL_LABEL);
          channelsChoiceA->labelfont(0);
          channelsChoiceA->labelsize(10);
          channelsChoiceA->labelcolor(FL_BACKGROUND2_COLOR);
          channelsChoiceA->textsize(12);
          channelsChoiceA->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          channelsChoiceA->align(FL_ALIGN_LEFT);
          channelsChoiceA->when(FL_WHEN_RELEASE);
        } // Fl_Choice_gfc* channelsChoiceA
        { startA = new Fl_Button_gfc(287, 107, 75, 31, "START");
          startA->box(FL_UP_BOX);
          startA->color(FL_FOREGROUND_COLOR);
          startA->selection_color(FL_BACKGROUND_COLOR);
          startA->labeltype(FL_NORMAL_LABEL);
          startA->labelfont(0);
          startA->labelsize(12);
          startA->labelcolor(FL_BACKGROUND2_COLOR);
          startA->callback((Fl_Callback*)loadCB, (void*)(LOADSTART_ID));
          startA->align(FL_ALIGN_CENTER);
          startA->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* startA
        groupA->end();
      } // Fl_Group* groupA
      { startButton = new Fl_Button_gfc(317, 300, 130, 29, "Start All  @+1>");
        startButton->tooltip("Start Loading!");
        startButton->box(FL_UP_BOX);
        startButton->down_box(FL_DOWN_BOX);
        startButton->color(FL_GRAY0);
        startButton->selection_color(FL_BACKGROUND_COLOR);
        startButton->labeltype(FL_NORMAL_LABEL);
        startButton->labelfont(1);
        startButton->labelsize(14);
        startButton->labelcolor(FL_INACTIVE_COLOR);
        startButton->callback((Fl_Callback*)loadCB, (void*)(LOADLOAD_ID));
        startButton->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        startButton->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* startButton
      { Fl_Button_gfc* o = new Fl_Button_gfc(669, 306, 70, 22, "Done");
        o->box(FL_UP_BOX);
        o->down_box(FL_DOWN_BOX);
        o->color(FL_GRAY0);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(1);
        o->labelsize(14);
        o->labelcolor(FL_INACTIVE_COLOR);
        o->callback((Fl_Callback*)loadCB, (void*)(LOADDONE_ID));
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* o
      { groupB = new Fl_Group(377, 16, 365, 130);
        groupB->box(FL_BORDER_FRAME);
        groupB->color(FL_INACTIVE_COLOR);
        groupB->labelcolor(FL_BACKGROUND2_COLOR);
        groupB->callback((Fl_Callback*)loadCB);
        { loadFromSpinnerB = new gfcSliderInput(408, 50, 180, 15, "In");
          loadFromSpinnerB->type(5);
          loadFromSpinnerB->box(FL_DOWN_BOX);
          loadFromSpinnerB->color(FL_FOREGROUND_COLOR);
          loadFromSpinnerB->selection_color(FL_BACKGROUND_COLOR);
          loadFromSpinnerB->labeltype(FL_NORMAL_LABEL);
          loadFromSpinnerB->labelfont(0);
          loadFromSpinnerB->labelsize(12);
          loadFromSpinnerB->labelcolor((Fl_Color)31);
          loadFromSpinnerB->step(1);
          loadFromSpinnerB->textsize(9);
          loadFromSpinnerB->callback((Fl_Callback*)loadCB, (void*)(LOADFROM_ID));
          loadFromSpinnerB->align(FL_ALIGN_LEFT);
          loadFromSpinnerB->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadFromSpinnerB
        { loadToSpinnerB = new gfcSliderInput(408, 66, 180, 15, "Out");
          loadToSpinnerB->type(5);
          loadToSpinnerB->box(FL_DOWN_BOX);
          loadToSpinnerB->color(FL_FOREGROUND_COLOR);
          loadToSpinnerB->selection_color(FL_BACKGROUND_COLOR);
          loadToSpinnerB->labeltype(FL_NORMAL_LABEL);
          loadToSpinnerB->labelfont(0);
          loadToSpinnerB->labelsize(12);
          loadToSpinnerB->labelcolor((Fl_Color)31);
          loadToSpinnerB->step(1);
          loadToSpinnerB->textsize(9);
          loadToSpinnerB->callback((Fl_Callback*)loadCB, (void*)(LOADTO_ID));
          loadToSpinnerB->align(FL_ALIGN_LEFT);
          loadToSpinnerB->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadToSpinnerB
        { filterChooserB = new Fl_Choice_gfc(443, 99, 91, 18, "Filter");
          filterChooserB->tooltip("Filter to apply on the scaled images");
          filterChooserB->box(FL_FLAT_BOX);
          filterChooserB->down_box(FL_BORDER_BOX);
          filterChooserB->color(FL_FOREGROUND_COLOR);
          filterChooserB->selection_color(FL_SELECTION_COLOR);
          filterChooserB->labeltype(FL_NORMAL_LABEL);
          filterChooserB->labelfont(0);
          filterChooserB->labelsize(10);
          filterChooserB->labelcolor(FL_BACKGROUND2_COLOR);
          filterChooserB->textsize(10);
          filterChooserB->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          filterChooserB->align(FL_ALIGN_TOP);
          filterChooserB->when(FL_WHEN_RELEASE);
          filterChooserB->menu(menu_filterChooserB);
        } // Fl_Choice_gfc* filterChooserB
        { browseButtonB = new Fl_Button_gfc(662, 24, 70, 20, "Browse");
          browseButtonB->box(FL_UP_BOX);
          browseButtonB->color(FL_FOREGROUND_COLOR);
          browseButtonB->selection_color(FL_BACKGROUND_COLOR);
          browseButtonB->labeltype(FL_NORMAL_LABEL);
          browseButtonB->labelfont(0);
          browseButtonB->labelsize(11);
          browseButtonB->labelcolor(FL_BACKGROUND2_COLOR);
          browseButtonB->callback((Fl_Callback*)loadCB, (void*)(LOADBROWSE_ID));
          browseButtonB->align(FL_ALIGN_CENTER);
          browseButtonB->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* browseButtonB
        { Fl_Input_Choice_gfc* o = scaleChooserB = new Fl_Input_Choice_gfc(382, 99, 53, 18, "Scale");
          scaleChooserB->tooltip("Loaded images will be scaled down to this percent");
          scaleChooserB->box(FL_DOWN_BOX);
          scaleChooserB->down_box(FL_BORDER_BOX);
          scaleChooserB->color((Fl_Color)37);
          scaleChooserB->selection_color(FL_BACKGROUND_COLOR);
          scaleChooserB->labeltype(FL_NORMAL_LABEL);
          scaleChooserB->labelfont(0);
          scaleChooserB->labelsize(10);
          scaleChooserB->labelcolor(FL_BACKGROUND2_COLOR);
          scaleChooserB->textsize(12);
          scaleChooserB->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          scaleChooserB->align(FL_ALIGN_TOP);
          scaleChooserB->when(FL_WHEN_RELEASE);
          scaleChooserB->menu(menu_scaleChooserB);
          o->value(0);
          o->textcolor(fl_rgb_color(85,85,85));
        } // Fl_Input_Choice_gfc* scaleChooserB
        { reloadButtonB = new Fl_Button(632, 51, 24, 25);
          reloadButtonB->color(FL_FOREGROUND_COLOR);
          reloadButtonB->labelsize(12);
          reloadButtonB->labelcolor(FL_BACKGROUND2_COLOR);
          reloadButtonB->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATE_ID));
          reloadButtonB->hide();
        } // Fl_Button* reloadButtonB
        { Fl_Check_Button* o = cropB = new Fl_Check_Button(570, 87, 18, 18, "Crop");
          cropB->tooltip("Enable cropping the image, once enabled, right click and shift+right click on\
 the preview to select the Area of Interest to load");
          cropB->down_box(FL_FLAT_BOX);
          cropB->color(FL_INACTIVE_COLOR);
          cropB->selection_color((Fl_Color)31);
          cropB->labelsize(10);
          cropB->labelcolor((Fl_Color)31);
          cropB->callback((Fl_Callback*)loadCB);
          cropB->align(FL_ALIGN_LEFT);
          o->labelcolor(fl_rgb_color(160,160,160));
        } // Fl_Check_Button* cropB
        { gammaSliderB = new Fl_Value_Input(592, 58, 27, 20, "Gamma");
          gammaSliderB->labelsize(12);
          gammaSliderB->labelcolor(FL_BACKGROUND2_COLOR);
          gammaSliderB->maximum(3);
          gammaSliderB->step(0.1);
          gammaSliderB->value(1);
          gammaSliderB->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          gammaSliderB->when(FL_WHEN_RELEASE);
          gammaSliderB->hide();
        } // Fl_Value_Input* gammaSliderB
        { formatB = new Fl_Choice_gfc(542, 125, 54, 16, "Bit Depth");
          formatB->tooltip("Special Formats can determine the quality/memory ratio.");
          formatB->box(FL_FLAT_BOX);
          formatB->down_box(FL_BORDER_BOX);
          formatB->color(FL_FOREGROUND_COLOR);
          formatB->selection_color(FL_SELECTION_COLOR);
          formatB->labeltype(FL_NORMAL_LABEL);
          formatB->labelfont(0);
          formatB->labelsize(10);
          formatB->labelcolor(FL_BACKGROUND2_COLOR);
          formatB->textsize(12);
          formatB->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          formatB->align(FL_ALIGN_TOP);
          formatB->when(FL_WHEN_RELEASE);
          formatB->menu(menu_formatB);
        } // Fl_Choice_gfc* formatB
        { Fl_Menu_Button* o = recentButtonB = new Fl_Menu_Button(633, 26, 27, 17, "@2>");
          recentButtonB->box(FL_FLAT_BOX);
          recentButtonB->down_box(FL_FLAT_BOX);
          recentButtonB->color(FL_INACTIVE_COLOR);
          recentButtonB->labelcolor((Fl_Color)31);
          recentButtonB->textcolor(31);
          recentButtonB->callback((Fl_Callback*)loadCB, (void*)(LOADRECENT_ID));
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Menu_Button* recentButtonB
        { Fl_Output* o = new Fl_Output(542, 25, 195, 18, "Sequence");
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
          o->when(FL_WHEN_CHANGED);
          o->hide();
        } // Fl_Output* o
        { Fl_Input* o = fileNameInputB = new Fl_Input(445, 26, 187, 17, "Sequence");
          fileNameInputB->box(FL_FLAT_BOX);
          fileNameInputB->color(FL_INACTIVE_COLOR);
          fileNameInputB->labelsize(12);
          fileNameInputB->labelcolor((Fl_Color)31);
          fileNameInputB->textsize(12);
          fileNameInputB->callback((Fl_Callback*)loadCB, (void*)(LOADFILENAME_ID));
          fileNameInputB->when(FL_WHEN_CHANGED);
          fileNameInputB->deactivate();
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* fileNameInputB
        { Fl_Choice_gfc* o = loadModeB = new Fl_Choice_gfc(539, 125, 64, 15, "Mode");
          loadModeB->tooltip("Specifies how this track will be treated whn you hit the START button. It can\
 replace what was there or it can ignore changes and leave everything the way \
it is");
          loadModeB->box(FL_FLAT_BOX);
          loadModeB->down_box(FL_BORDER_BOX);
          loadModeB->color(FL_FOREGROUND_COLOR);
          loadModeB->selection_color(FL_SELECTION_COLOR);
          loadModeB->labeltype(FL_NORMAL_LABEL);
          loadModeB->labelfont(0);
          loadModeB->labelsize(10);
          loadModeB->labelcolor(FL_BACKGROUND2_COLOR);
          loadModeB->textsize(10);
          loadModeB->align(FL_ALIGN_LEFT);
          loadModeB->when(FL_WHEN_RELEASE);
          loadModeB->hide();
          loadModeB->menu(menu_loadModeB);
          o->value(0);
        } // Fl_Choice_gfc* loadModeB
        { Fl_Output* o = estimatesB = new Fl_Output(595, 48, 140, 55);
          estimatesB->tooltip("Shows information on memory usage and load times");
          estimatesB->type(12);
          estimatesB->box(FL_BORDER_BOX);
          estimatesB->color(FL_INACTIVE_COLOR);
          estimatesB->selection_color(FL_FOREGROUND_COLOR);
          estimatesB->labelsize(10);
          estimatesB->labelcolor(FL_BACKGROUND2_COLOR);
          estimatesB->textsize(10);
          estimatesB->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Output* estimatesB
        { unloadAndClearB = new Fl_Button_gfc(620, 109, 27, 27, "@3+");
          unloadAndClearB->box(FL_UP_BOX);
          unloadAndClearB->color(FL_FOREGROUND_COLOR);
          unloadAndClearB->selection_color(FL_BACKGROUND_COLOR);
          unloadAndClearB->labeltype(FL_NORMAL_LABEL);
          unloadAndClearB->labelfont(0);
          unloadAndClearB->labelsize(12);
          unloadAndClearB->labelcolor((Fl_Color)1);
          unloadAndClearB->callback((Fl_Callback*)loadCB, (void*)(LOADUNLOADANDCLEAR_ID));
          unloadAndClearB->align(FL_ALIGN_CENTER);
          unloadAndClearB->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* unloadAndClearB
        { channelsChoiceB = new Fl_Choice_gfc(429, 126, 100, 15, "Channels");
          channelsChoiceB->tooltip("When working with multi channel images (such as OpenEXR), you can choose what\
 channel to load");
          channelsChoiceB->box(FL_FLAT_BOX);
          channelsChoiceB->down_box(FL_BORDER_BOX);
          channelsChoiceB->color(FL_FOREGROUND_COLOR);
          channelsChoiceB->selection_color(FL_SELECTION_COLOR);
          channelsChoiceB->labeltype(FL_NORMAL_LABEL);
          channelsChoiceB->labelfont(0);
          channelsChoiceB->labelsize(10);
          channelsChoiceB->labelcolor(FL_BACKGROUND2_COLOR);
          channelsChoiceB->textsize(12);
          channelsChoiceB->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          channelsChoiceB->align(FL_ALIGN_LEFT);
          channelsChoiceB->when(FL_WHEN_RELEASE);
        } // Fl_Choice_gfc* channelsChoiceB
        { startB = new Fl_Button_gfc(655, 107, 75, 31, "START");
          startB->box(FL_UP_BOX);
          startB->color(FL_FOREGROUND_COLOR);
          startB->selection_color(FL_BACKGROUND_COLOR);
          startB->labeltype(FL_NORMAL_LABEL);
          startB->labelfont(0);
          startB->labelsize(12);
          startB->labelcolor(FL_BACKGROUND2_COLOR);
          startB->callback((Fl_Callback*)loadCB, (void*)(LOADSTART_ID));
          startB->align(FL_ALIGN_CENTER);
          startB->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* startB
        groupB->end();
      } // Fl_Group* groupB
      { groupC = new Fl_Group(7, 163, 365, 130);
        groupC->box(FL_BORDER_FRAME);
        groupC->color(FL_INACTIVE_COLOR);
        groupC->labelcolor(FL_BACKGROUND2_COLOR);
        groupC->callback((Fl_Callback*)loadCB);
        { loadFromSpinnerC = new gfcSliderInput(38, 197, 180, 15, "In");
          loadFromSpinnerC->type(5);
          loadFromSpinnerC->box(FL_DOWN_BOX);
          loadFromSpinnerC->color(FL_FOREGROUND_COLOR);
          loadFromSpinnerC->selection_color(FL_BACKGROUND_COLOR);
          loadFromSpinnerC->labeltype(FL_NORMAL_LABEL);
          loadFromSpinnerC->labelfont(0);
          loadFromSpinnerC->labelsize(12);
          loadFromSpinnerC->labelcolor((Fl_Color)31);
          loadFromSpinnerC->step(1);
          loadFromSpinnerC->textsize(9);
          loadFromSpinnerC->callback((Fl_Callback*)loadCB, (void*)(LOADFROM_ID));
          loadFromSpinnerC->align(FL_ALIGN_LEFT);
          loadFromSpinnerC->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadFromSpinnerC
        { loadToSpinnerC = new gfcSliderInput(38, 213, 180, 15, "Out");
          loadToSpinnerC->type(5);
          loadToSpinnerC->box(FL_DOWN_BOX);
          loadToSpinnerC->color(FL_FOREGROUND_COLOR);
          loadToSpinnerC->selection_color(FL_BACKGROUND_COLOR);
          loadToSpinnerC->labeltype(FL_NORMAL_LABEL);
          loadToSpinnerC->labelfont(0);
          loadToSpinnerC->labelsize(12);
          loadToSpinnerC->labelcolor((Fl_Color)31);
          loadToSpinnerC->step(1);
          loadToSpinnerC->textsize(9);
          loadToSpinnerC->callback((Fl_Callback*)loadCB, (void*)(LOADTO_ID));
          loadToSpinnerC->align(FL_ALIGN_LEFT);
          loadToSpinnerC->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadToSpinnerC
        { filterChooserC = new Fl_Choice_gfc(73, 246, 91, 18, "Filter");
          filterChooserC->tooltip("Filter to apply on the scaled images");
          filterChooserC->box(FL_FLAT_BOX);
          filterChooserC->down_box(FL_BORDER_BOX);
          filterChooserC->color(FL_FOREGROUND_COLOR);
          filterChooserC->selection_color(FL_SELECTION_COLOR);
          filterChooserC->labeltype(FL_NORMAL_LABEL);
          filterChooserC->labelfont(0);
          filterChooserC->labelsize(10);
          filterChooserC->labelcolor(FL_BACKGROUND2_COLOR);
          filterChooserC->textsize(10);
          filterChooserC->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          filterChooserC->align(FL_ALIGN_TOP);
          filterChooserC->when(FL_WHEN_RELEASE);
          filterChooserC->menu(menu_filterChooserC);
        } // Fl_Choice_gfc* filterChooserC
        { browseButtonC = new Fl_Button_gfc(292, 171, 70, 20, "Browse");
          browseButtonC->box(FL_UP_BOX);
          browseButtonC->color(FL_FOREGROUND_COLOR);
          browseButtonC->selection_color(FL_BACKGROUND_COLOR);
          browseButtonC->labeltype(FL_NORMAL_LABEL);
          browseButtonC->labelfont(0);
          browseButtonC->labelsize(11);
          browseButtonC->labelcolor(FL_BACKGROUND2_COLOR);
          browseButtonC->callback((Fl_Callback*)loadCB, (void*)(LOADBROWSE_ID));
          browseButtonC->align(FL_ALIGN_CENTER);
          browseButtonC->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* browseButtonC
        { Fl_Input_Choice_gfc* o = scaleChooserC = new Fl_Input_Choice_gfc(12, 246, 53, 18, "Scale");
          scaleChooserC->tooltip("Loaded images will be scaled down to this percent");
          scaleChooserC->box(FL_FLAT_BOX);
          scaleChooserC->down_box(FL_FLAT_BOX);
          scaleChooserC->color((Fl_Color)37);
          scaleChooserC->selection_color(FL_BACKGROUND_COLOR);
          scaleChooserC->labeltype(FL_NORMAL_LABEL);
          scaleChooserC->labelfont(0);
          scaleChooserC->labelsize(10);
          scaleChooserC->labelcolor(FL_BACKGROUND2_COLOR);
          scaleChooserC->textsize(12);
          scaleChooserC->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          scaleChooserC->align(FL_ALIGN_TOP);
          scaleChooserC->when(FL_WHEN_RELEASE);
          scaleChooserC->menu(menu_scaleChooserC);
          o->value(0);
          o->textcolor(fl_rgb_color(85,85,85));
        } // Fl_Input_Choice_gfc* scaleChooserC
        { reloadButtonC = new Fl_Button(262, 198, 24, 25);
          reloadButtonC->color(FL_FOREGROUND_COLOR);
          reloadButtonC->labelsize(12);
          reloadButtonC->labelcolor(FL_BACKGROUND2_COLOR);
          reloadButtonC->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATE_ID));
          reloadButtonC->hide();
        } // Fl_Button* reloadButtonC
        { Fl_Check_Button* o = cropC = new Fl_Check_Button(200, 234, 18, 18, "Crop");
          cropC->tooltip("Enable cropping the image, once enabled, right click and shift+right click on\
 the preview to select the Area of Interest to load");
          cropC->down_box(FL_FLAT_BOX);
          cropC->color(FL_INACTIVE_COLOR);
          cropC->selection_color((Fl_Color)31);
          cropC->labelsize(10);
          cropC->labelcolor((Fl_Color)31);
          cropC->callback((Fl_Callback*)loadCB);
          cropC->align(FL_ALIGN_LEFT);
          o->labelcolor(fl_rgb_color(160,160,160));
        } // Fl_Check_Button* cropC
        { gammaSliderC = new Fl_Value_Input(222, 205, 27, 20, "Gamma");
          gammaSliderC->labelsize(12);
          gammaSliderC->labelcolor(FL_BACKGROUND2_COLOR);
          gammaSliderC->maximum(3);
          gammaSliderC->step(0.1);
          gammaSliderC->value(1);
          gammaSliderC->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          gammaSliderC->when(FL_WHEN_RELEASE);
          gammaSliderC->hide();
        } // Fl_Value_Input* gammaSliderC
        { formatC = new Fl_Choice_gfc(172, 272, 56, 16, "Bit Depth");
          formatC->tooltip("Special Formats can determine the quality/memory ratio.");
          formatC->box(FL_FLAT_BOX);
          formatC->down_box(FL_BORDER_BOX);
          formatC->color(FL_FOREGROUND_COLOR);
          formatC->selection_color(FL_SELECTION_COLOR);
          formatC->labeltype(FL_NORMAL_LABEL);
          formatC->labelfont(0);
          formatC->labelsize(10);
          formatC->labelcolor(FL_BACKGROUND2_COLOR);
          formatC->textsize(12);
          formatC->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          formatC->align(FL_ALIGN_TOP);
          formatC->when(FL_WHEN_RELEASE);
          formatC->menu(menu_formatC);
        } // Fl_Choice_gfc* formatC
        { Fl_Menu_Button* o = recentButtonC = new Fl_Menu_Button(263, 173, 27, 17, "@2>");
          recentButtonC->box(FL_FLAT_BOX);
          recentButtonC->down_box(FL_FLAT_BOX);
          recentButtonC->color(FL_INACTIVE_COLOR);
          recentButtonC->labelcolor((Fl_Color)31);
          recentButtonC->textcolor(31);
          recentButtonC->callback((Fl_Callback*)loadCB, (void*)(LOADRECENT_ID));
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Menu_Button* recentButtonC
        { Fl_Output* o = new Fl_Output(172, 172, 195, 18, "Sequence");
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
          o->when(FL_WHEN_CHANGED);
          o->hide();
        } // Fl_Output* o
        { Fl_Input* o = fileNameInputC = new Fl_Input(75, 173, 187, 17, "Sequence");
          fileNameInputC->box(FL_FLAT_BOX);
          fileNameInputC->color(FL_INACTIVE_COLOR);
          fileNameInputC->labelsize(12);
          fileNameInputC->labelcolor((Fl_Color)31);
          fileNameInputC->textsize(12);
          fileNameInputC->callback((Fl_Callback*)loadCB, (void*)(LOADFILENAME_ID));
          fileNameInputC->when(FL_WHEN_CHANGED);
          fileNameInputC->deactivate();
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* fileNameInputC
        { Fl_Choice_gfc* o = loadModeC = new Fl_Choice_gfc(169, 272, 64, 15, "Mode");
          loadModeC->tooltip("Specifies how this track will be treated whn you hit the START button. It can\
 replace what was there or it can ignore changes and leave everything the way \
it is");
          loadModeC->box(FL_FLAT_BOX);
          loadModeC->down_box(FL_BORDER_BOX);
          loadModeC->color(FL_FOREGROUND_COLOR);
          loadModeC->selection_color(FL_SELECTION_COLOR);
          loadModeC->labeltype(FL_NORMAL_LABEL);
          loadModeC->labelfont(0);
          loadModeC->labelsize(10);
          loadModeC->labelcolor(FL_BACKGROUND2_COLOR);
          loadModeC->textsize(10);
          loadModeC->align(FL_ALIGN_LEFT);
          loadModeC->when(FL_WHEN_RELEASE);
          loadModeC->hide();
          loadModeC->menu(menu_loadModeC);
          o->value(0);
        } // Fl_Choice_gfc* loadModeC
        { Fl_Output* o = estimatesC = new Fl_Output(225, 195, 140, 55);
          estimatesC->tooltip("Shows information on memory usage and load times");
          estimatesC->type(12);
          estimatesC->box(FL_BORDER_BOX);
          estimatesC->color(FL_INACTIVE_COLOR);
          estimatesC->selection_color(FL_FOREGROUND_COLOR);
          estimatesC->labelsize(10);
          estimatesC->labelcolor(FL_BACKGROUND2_COLOR);
          estimatesC->textsize(10);
          estimatesC->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Output* estimatesC
        { unloadAndClearC = new Fl_Button_gfc(250, 255, 27, 27, "@3+");
          unloadAndClearC->box(FL_UP_BOX);
          unloadAndClearC->color(FL_FOREGROUND_COLOR);
          unloadAndClearC->selection_color(FL_BACKGROUND_COLOR);
          unloadAndClearC->labeltype(FL_NORMAL_LABEL);
          unloadAndClearC->labelfont(0);
          unloadAndClearC->labelsize(12);
          unloadAndClearC->labelcolor((Fl_Color)1);
          unloadAndClearC->callback((Fl_Callback*)loadCB, (void*)(LOADUNLOADANDCLEAR_ID));
          unloadAndClearC->align(FL_ALIGN_CENTER);
          unloadAndClearC->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* unloadAndClearC
        { channelsChoiceC = new Fl_Choice_gfc(59, 272, 100, 15, "Channels");
          channelsChoiceC->tooltip("When working with multi channel images (such as OpenEXR), you can choose what\
 channel to load");
          channelsChoiceC->box(FL_FLAT_BOX);
          channelsChoiceC->down_box(FL_BORDER_BOX);
          channelsChoiceC->color(FL_FOREGROUND_COLOR);
          channelsChoiceC->selection_color(FL_SELECTION_COLOR);
          channelsChoiceC->labeltype(FL_NORMAL_LABEL);
          channelsChoiceC->labelfont(0);
          channelsChoiceC->labelsize(10);
          channelsChoiceC->labelcolor(FL_BACKGROUND2_COLOR);
          channelsChoiceC->textsize(12);
          channelsChoiceC->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          channelsChoiceC->align(FL_ALIGN_LEFT);
          channelsChoiceC->when(FL_WHEN_RELEASE);
        } // Fl_Choice_gfc* channelsChoiceC
        { startC = new Fl_Button_gfc(287, 254, 75, 31, "START");
          startC->box(FL_UP_BOX);
          startC->color(FL_FOREGROUND_COLOR);
          startC->selection_color(FL_BACKGROUND_COLOR);
          startC->labeltype(FL_NORMAL_LABEL);
          startC->labelfont(0);
          startC->labelsize(12);
          startC->labelcolor(FL_BACKGROUND2_COLOR);
          startC->callback((Fl_Callback*)loadCB, (void*)(LOADSTART_ID));
          startC->align(FL_ALIGN_CENTER);
          startC->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* startC
        groupC->end();
      } // Fl_Group* groupC
      { groupD = new Fl_Group(377, 163, 365, 130);
        groupD->box(FL_BORDER_FRAME);
        groupD->color(FL_INACTIVE_COLOR);
        groupD->labelcolor(FL_BACKGROUND2_COLOR);
        groupD->callback((Fl_Callback*)loadCB);
        { loadFromSpinnerD = new gfcSliderInput(408, 198, 180, 15, "In");
          loadFromSpinnerD->type(5);
          loadFromSpinnerD->box(FL_DOWN_BOX);
          loadFromSpinnerD->color(FL_FOREGROUND_COLOR);
          loadFromSpinnerD->selection_color(FL_BACKGROUND_COLOR);
          loadFromSpinnerD->labeltype(FL_NORMAL_LABEL);
          loadFromSpinnerD->labelfont(0);
          loadFromSpinnerD->labelsize(12);
          loadFromSpinnerD->labelcolor((Fl_Color)31);
          loadFromSpinnerD->step(1);
          loadFromSpinnerD->textsize(9);
          loadFromSpinnerD->callback((Fl_Callback*)loadCB, (void*)(LOADFROM_ID));
          loadFromSpinnerD->align(FL_ALIGN_LEFT);
          loadFromSpinnerD->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadFromSpinnerD
        { loadToSpinnerD = new gfcSliderInput(408, 214, 180, 15, "Out");
          loadToSpinnerD->type(5);
          loadToSpinnerD->box(FL_DOWN_BOX);
          loadToSpinnerD->color(FL_FOREGROUND_COLOR);
          loadToSpinnerD->selection_color(FL_BACKGROUND_COLOR);
          loadToSpinnerD->labeltype(FL_NORMAL_LABEL);
          loadToSpinnerD->labelfont(0);
          loadToSpinnerD->labelsize(12);
          loadToSpinnerD->labelcolor((Fl_Color)31);
          loadToSpinnerD->step(1);
          loadToSpinnerD->textsize(9);
          loadToSpinnerD->callback((Fl_Callback*)loadCB, (void*)(LOADTO_ID));
          loadToSpinnerD->align(FL_ALIGN_LEFT);
          loadToSpinnerD->when(FL_WHEN_CHANGED);
        } // gfcSliderInput* loadToSpinnerD
        { filterChooserD = new Fl_Choice_gfc(443, 246, 91, 18, "Filter");
          filterChooserD->tooltip("Filter to apply on the scaled images");
          filterChooserD->box(FL_FLAT_BOX);
          filterChooserD->down_box(FL_BORDER_BOX);
          filterChooserD->color(FL_FOREGROUND_COLOR);
          filterChooserD->selection_color(FL_SELECTION_COLOR);
          filterChooserD->labeltype(FL_NORMAL_LABEL);
          filterChooserD->labelfont(0);
          filterChooserD->labelsize(10);
          filterChooserD->labelcolor(FL_BACKGROUND2_COLOR);
          filterChooserD->textsize(10);
          filterChooserD->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          filterChooserD->align(FL_ALIGN_TOP);
          filterChooserD->when(FL_WHEN_RELEASE);
          filterChooserD->menu(menu_filterChooserD);
        } // Fl_Choice_gfc* filterChooserD
        { browseButtonD = new Fl_Button_gfc(662, 172, 70, 20, "Browse");
          browseButtonD->box(FL_UP_BOX);
          browseButtonD->color(FL_FOREGROUND_COLOR);
          browseButtonD->selection_color(FL_BACKGROUND_COLOR);
          browseButtonD->labeltype(FL_NORMAL_LABEL);
          browseButtonD->labelfont(0);
          browseButtonD->labelsize(11);
          browseButtonD->labelcolor(FL_BACKGROUND2_COLOR);
          browseButtonD->callback((Fl_Callback*)loadCB, (void*)(LOADBROWSE_ID));
          browseButtonD->align(FL_ALIGN_CENTER);
          browseButtonD->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* browseButtonD
        { Fl_Input_Choice_gfc* o = scaleChooserD = new Fl_Input_Choice_gfc(382, 246, 53, 18, "Scale");
          scaleChooserD->tooltip("Loaded images will be scaled down to this percent");
          scaleChooserD->box(FL_DOWN_BOX);
          scaleChooserD->down_box(FL_BORDER_BOX);
          scaleChooserD->color((Fl_Color)37);
          scaleChooserD->selection_color(FL_BACKGROUND_COLOR);
          scaleChooserD->labeltype(FL_NORMAL_LABEL);
          scaleChooserD->labelfont(0);
          scaleChooserD->labelsize(10);
          scaleChooserD->labelcolor(FL_BACKGROUND2_COLOR);
          scaleChooserD->textsize(12);
          scaleChooserD->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          scaleChooserD->align(FL_ALIGN_TOP);
          scaleChooserD->when(FL_WHEN_RELEASE);
          scaleChooserD->menu(menu_scaleChooserD);
          o->value(0);
          o->textcolor(fl_rgb_color(85,85,85));
        } // Fl_Input_Choice_gfc* scaleChooserD
        { reloadButtonD = new Fl_Button(632, 199, 24, 25);
          reloadButtonD->color(FL_FOREGROUND_COLOR);
          reloadButtonD->labelsize(12);
          reloadButtonD->labelcolor(FL_BACKGROUND2_COLOR);
          reloadButtonD->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATE_ID));
          reloadButtonD->hide();
        } // Fl_Button* reloadButtonD
        { Fl_Check_Button* o = cropD = new Fl_Check_Button(570, 234, 18, 18, "Crop");
          cropD->tooltip("Enable cropping the image, once enabled, right click and shift+right click on\
 the preview to select the Area of Interest to load");
          cropD->down_box(FL_FLAT_BOX);
          cropD->color(FL_INACTIVE_COLOR);
          cropD->selection_color((Fl_Color)31);
          cropD->labelsize(10);
          cropD->labelcolor((Fl_Color)31);
          cropD->callback((Fl_Callback*)loadCB);
          cropD->align(FL_ALIGN_LEFT);
          o->labelcolor(fl_rgb_color(160,160,160));
        } // Fl_Check_Button* cropD
        { gammaSliderD = new Fl_Value_Input(592, 206, 27, 20, "Gamma");
          gammaSliderD->labelsize(12);
          gammaSliderD->labelcolor(FL_BACKGROUND2_COLOR);
          gammaSliderD->maximum(3);
          gammaSliderD->step(0.1);
          gammaSliderD->value(1);
          gammaSliderD->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          gammaSliderD->when(FL_WHEN_RELEASE);
          gammaSliderD->hide();
        } // Fl_Value_Input* gammaSliderD
        { formatD = new Fl_Choice_gfc(542, 272, 54, 16, "Bit Depth");
          formatD->tooltip("Special Formats can determine the quality/memory ratio.");
          formatD->box(FL_FLAT_BOX);
          formatD->down_box(FL_BORDER_BOX);
          formatD->color(FL_FOREGROUND_COLOR);
          formatD->selection_color(FL_SELECTION_COLOR);
          formatD->labeltype(FL_NORMAL_LABEL);
          formatD->labelfont(0);
          formatD->labelsize(10);
          formatD->labelcolor(FL_BACKGROUND2_COLOR);
          formatD->textsize(12);
          formatD->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          formatD->align(FL_ALIGN_TOP);
          formatD->when(FL_WHEN_RELEASE);
          formatD->menu(menu_formatD);
        } // Fl_Choice_gfc* formatD
        { Fl_Menu_Button* o = recentButtonD = new Fl_Menu_Button(633, 174, 27, 17, "@2>");
          recentButtonD->box(FL_FLAT_BOX);
          recentButtonD->down_box(FL_FLAT_BOX);
          recentButtonD->color(FL_INACTIVE_COLOR);
          recentButtonD->labelcolor((Fl_Color)31);
          recentButtonD->textcolor(31);
          recentButtonD->callback((Fl_Callback*)loadCB, (void*)(LOADRECENT_ID));
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Menu_Button* recentButtonD
        { Fl_Output* o = new Fl_Output(542, 173, 195, 18, "Sequence");
          o->labelsize(12);
          o->labelcolor(FL_BACKGROUND2_COLOR);
          o->textsize(12);
          o->when(FL_WHEN_CHANGED);
          o->hide();
        } // Fl_Output* o
        { Fl_Input* o = fileNameInputD = new Fl_Input(445, 174, 187, 17, "Sequence");
          fileNameInputD->box(FL_FLAT_BOX);
          fileNameInputD->color(FL_INACTIVE_COLOR);
          fileNameInputD->labelsize(12);
          fileNameInputD->labelcolor((Fl_Color)31);
          fileNameInputD->textsize(12);
          fileNameInputD->callback((Fl_Callback*)loadCB, (void*)(LOADFILENAME_ID));
          fileNameInputD->when(FL_WHEN_CHANGED);
          fileNameInputD->deactivate();
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* fileNameInputD
        { Fl_Choice_gfc* o = loadModeD = new Fl_Choice_gfc(539, 273, 64, 15, "Mode");
          loadModeD->tooltip("Specifies how this track will be treated whn you hit the START button. It can\
 replace what was there or it can ignore changes and leave everything the way \
it is");
          loadModeD->box(FL_FLAT_BOX);
          loadModeD->down_box(FL_BORDER_BOX);
          loadModeD->color(FL_FOREGROUND_COLOR);
          loadModeD->selection_color(FL_SELECTION_COLOR);
          loadModeD->labeltype(FL_NORMAL_LABEL);
          loadModeD->labelfont(0);
          loadModeD->labelsize(10);
          loadModeD->labelcolor(FL_BACKGROUND2_COLOR);
          loadModeD->textsize(10);
          loadModeD->align(FL_ALIGN_LEFT);
          loadModeD->when(FL_WHEN_RELEASE);
          loadModeD->hide();
          loadModeD->menu(menu_loadModeD);
          o->value(0);
        } // Fl_Choice_gfc* loadModeD
        { Fl_Output* o = estimatesD = new Fl_Output(595, 196, 140, 55);
          estimatesD->tooltip("Shows information on memory usage and load times");
          estimatesD->type(12);
          estimatesD->box(FL_BORDER_BOX);
          estimatesD->color(FL_INACTIVE_COLOR);
          estimatesD->selection_color(FL_FOREGROUND_COLOR);
          estimatesD->labelsize(10);
          estimatesD->labelcolor(FL_BACKGROUND2_COLOR);
          estimatesD->textsize(10);
          estimatesD->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Output* estimatesD
        { unloadAndClearD = new Fl_Button_gfc(621, 255, 27, 27, "@3+");
          unloadAndClearD->box(FL_UP_BOX);
          unloadAndClearD->color(FL_FOREGROUND_COLOR);
          unloadAndClearD->selection_color(FL_BACKGROUND_COLOR);
          unloadAndClearD->labeltype(FL_NORMAL_LABEL);
          unloadAndClearD->labelfont(0);
          unloadAndClearD->labelsize(12);
          unloadAndClearD->labelcolor((Fl_Color)1);
          unloadAndClearD->callback((Fl_Callback*)loadCB, (void*)(LOADUNLOADANDCLEAR_ID));
          unloadAndClearD->align(FL_ALIGN_CENTER);
          unloadAndClearD->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* unloadAndClearD
        { channelsChoiceD = new Fl_Choice_gfc(430, 272, 100, 15, "Channels");
          channelsChoiceD->tooltip("When working with multi channel images (such as OpenEXR), you can choose what\
 channel to load");
          channelsChoiceD->box(FL_FLAT_BOX);
          channelsChoiceD->down_box(FL_BORDER_BOX);
          channelsChoiceD->color(FL_FOREGROUND_COLOR);
          channelsChoiceD->selection_color(FL_SELECTION_COLOR);
          channelsChoiceD->labeltype(FL_NORMAL_LABEL);
          channelsChoiceD->labelfont(0);
          channelsChoiceD->labelsize(10);
          channelsChoiceD->labelcolor(FL_BACKGROUND2_COLOR);
          channelsChoiceD->textsize(12);
          channelsChoiceD->callback((Fl_Callback*)loadCB, (void*)(LOADUPDATEPREVIEW_ID));
          channelsChoiceD->align(FL_ALIGN_LEFT);
          channelsChoiceD->when(FL_WHEN_RELEASE);
        } // Fl_Choice_gfc* channelsChoiceD
        { startD = new Fl_Button_gfc(659, 254, 75, 31, "START");
          startD->box(FL_UP_BOX);
          startD->color(FL_FOREGROUND_COLOR);
          startD->selection_color(FL_BACKGROUND_COLOR);
          startD->labeltype(FL_NORMAL_LABEL);
          startD->labelfont(0);
          startD->labelsize(12);
          startD->labelcolor(FL_BACKGROUND2_COLOR);
          startD->callback((Fl_Callback*)loadCB, (void*)(LOADSTART_ID));
          startD->align(FL_ALIGN_CENTER);
          startD->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* startD
        groupD->end();
      } // Fl_Group* groupD
      { Fl_Box* o = new Fl_Box(19, 2, 24, 26, "A");
        o->box(FL_FLAT_BOX);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(24);
        o->labelcolor((Fl_Color)31);
        o->align(FL_ALIGN_TOP|FL_ALIGN_INSIDE);
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(386, 3, 24, 26, "B");
        o->box(FL_FLAT_BOX);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(24);
        o->labelcolor((Fl_Color)31);
        o->align(FL_ALIGN_TOP|FL_ALIGN_INSIDE);
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(16, 148, 22, 25, "C");
        o->box(FL_FLAT_BOX);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(24);
        o->labelcolor((Fl_Color)31);
        o->align(FL_ALIGN_TOP|FL_ALIGN_INSIDE);
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(386, 150, 22, 25, "D");
        o->box(FL_FLAT_BOX);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(24);
        o->labelcolor((Fl_Color)31);
        o->align(FL_ALIGN_TOP|FL_ALIGN_INSIDE);
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
        o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
      } // Fl_Box* o
      { addToQueueButton = new Fl_Button_gfc(266, 300, 48, 29);
        addToQueueButton->tooltip("Start Loading!");
        addToQueueButton->box(FL_UP_BOX);
        addToQueueButton->down_box(FL_DOWN_BOX);
        addToQueueButton->color(FL_GRAY0);
        addToQueueButton->selection_color(FL_BACKGROUND_COLOR);
        addToQueueButton->image(image_AddToPlaylistIcon);
        addToQueueButton->labeltype(FL_NORMAL_LABEL);
        addToQueueButton->labelfont(1);
        addToQueueButton->labelsize(14);
        addToQueueButton->labelcolor(FL_INACTIVE_COLOR);
        addToQueueButton->callback((Fl_Callback*)loadCB, (void*)(LOADADDTOQUEUE_ID));
        addToQueueButton->align(FL_ALIGN_CENTER);
        addToQueueButton->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* addToQueueButton
      { openPlayListButton = new Fl_Button_gfc(531, 304, 75, 22, "Playlist...");
        openPlayListButton->tooltip("Start Loading!");
        openPlayListButton->box(FL_UP_BOX);
        openPlayListButton->down_box(FL_DOWN_BOX);
        openPlayListButton->color(FL_GRAY0);
        openPlayListButton->selection_color(FL_BACKGROUND_COLOR);
        openPlayListButton->labeltype(FL_NORMAL_LABEL);
        openPlayListButton->labelfont(1);
        openPlayListButton->labelsize(12);
        openPlayListButton->labelcolor(FL_INACTIVE_COLOR);
        openPlayListButton->callback((Fl_Callback*)loadCB, (void*)(LOADOPENPLAYLIST_ID));
        openPlayListButton->align(FL_ALIGN_CENTER);
        openPlayListButton->when(FL_WHEN_RELEASE);
        openPlayListButton->hide();
      } // Fl_Button_gfc* openPlayListButton
      frame->end();
    } // Fl_Group* frame
    { reduceButton = new Fl_Button(420, 282, 30, 18, "@8UpArrow");
      reduceButton->shortcut(0x6d);
      reduceButton->color(FL_FOREGROUND_COLOR);
      reduceButton->callback((Fl_Callback*)loadCB, (void*)(LOADREDUCE_ID));
      reduceButton->hide();
    } // Fl_Button* reduceButton
    loadWindow->set_non_modal();
    loadWindow->clear_border();
    loadWindow->size_range(750, 335, 750, 335);
    loadWindow->end();
  } // Fl_Double_Window* loadWindow
}
