// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef loadWindow_h
#define loadWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
extern void loadCB(Fl_Group*, void*);
#include "gfcSliderInput.h"
extern void loadCB(gfcSliderInput*, void*);
#include "Fl_Choice_gfc.h"
extern void loadCB(Fl_Choice_gfc*, long);
#include "Fl_Button_gfc.h"
extern void loadCB(Fl_Button_gfc*, long);
#include "Fl_Input_Choice_gfc.h"
extern void loadCB(Fl_Input_Choice_gfc*, void*);
#include <FL/Fl_Button.H>
extern void loadCB(Fl_Button*, long);
#include <FL/Fl_Check_Button.H>
extern void loadCB(Fl_Check_Button*, void*);
#include <FL/Fl_Value_Input.H>
extern void loadCB(Fl_Value_Input*, void*);
extern void loadCB(Fl_Choice_gfc*, void*);
#include <FL/Fl_Menu_Button.H>
extern void loadCB(Fl_Menu_Button*, long);
#include <FL/Fl_Output.H>
#include <FL/Fl_Input.H>
extern void loadCB(Fl_Input*, long);
extern void loadCB(Fl_Button_gfc*, void*);
extern void loadCB(Fl_Button*, void*);

class LoadWindow : public Fl_Double_Window {
public:
  LoadWindow(int x, int y, int wi, int height,const char* l) ;
  Fl_Double_Window *loadWindow;
  Fl_Box *bgBOX;
  Fl_Group *frame;
  Fl_Group *groupA;
  gfcSliderInput *loadFromSpinnerA;
  gfcSliderInput *loadToSpinnerA;
  Fl_Choice_gfc *filterChooserA;
  static Fl_Menu_Item menu_filterChooserA[];
  Fl_Button_gfc *browseButtonA;
  Fl_Input_Choice_gfc *scaleChooserA;
  static Fl_Menu_Item menu_scaleChooserA[];
  Fl_Button *reloadButtonA;
  Fl_Check_Button *cropA;
  Fl_Value_Input *gammaSliderA;
  Fl_Choice_gfc *formatA;
  static Fl_Menu_Item menu_formatA[];
  Fl_Menu_Button *recentButtonA;
  Fl_Input *fileNameInputA;
  Fl_Choice_gfc *loadModeA;
  static Fl_Menu_Item menu_loadModeA[];
  Fl_Output *estimatesA;
  Fl_Button_gfc *unloadAndClearA;
  Fl_Choice_gfc *channelsChoiceA;
  Fl_Button_gfc *startA;
  Fl_Button_gfc *startButton;
  Fl_Group *groupB;
  gfcSliderInput *loadFromSpinnerB;
  gfcSliderInput *loadToSpinnerB;
  Fl_Choice_gfc *filterChooserB;
  static Fl_Menu_Item menu_filterChooserB[];
  Fl_Button_gfc *browseButtonB;
  Fl_Input_Choice_gfc *scaleChooserB;
  static Fl_Menu_Item menu_scaleChooserB[];
  Fl_Button *reloadButtonB;
  Fl_Check_Button *cropB;
  Fl_Value_Input *gammaSliderB;
  Fl_Choice_gfc *formatB;
  static Fl_Menu_Item menu_formatB[];
  Fl_Menu_Button *recentButtonB;
  Fl_Input *fileNameInputB;
  Fl_Choice_gfc *loadModeB;
  static Fl_Menu_Item menu_loadModeB[];
  Fl_Output *estimatesB;
  Fl_Button_gfc *unloadAndClearB;
  Fl_Choice_gfc *channelsChoiceB;
  Fl_Button_gfc *startB;
  Fl_Group *groupC;
  gfcSliderInput *loadFromSpinnerC;
  gfcSliderInput *loadToSpinnerC;
  Fl_Choice_gfc *filterChooserC;
  static Fl_Menu_Item menu_filterChooserC[];
  Fl_Button_gfc *browseButtonC;
  Fl_Input_Choice_gfc *scaleChooserC;
  static Fl_Menu_Item menu_scaleChooserC[];
  Fl_Button *reloadButtonC;
  Fl_Check_Button *cropC;
  Fl_Value_Input *gammaSliderC;
  Fl_Choice_gfc *formatC;
  static Fl_Menu_Item menu_formatC[];
  Fl_Menu_Button *recentButtonC;
  Fl_Input *fileNameInputC;
  Fl_Choice_gfc *loadModeC;
  static Fl_Menu_Item menu_loadModeC[];
  Fl_Output *estimatesC;
  Fl_Button_gfc *unloadAndClearC;
  Fl_Choice_gfc *channelsChoiceC;
  Fl_Button_gfc *startC;
  Fl_Group *groupD;
  gfcSliderInput *loadFromSpinnerD;
  gfcSliderInput *loadToSpinnerD;
  Fl_Choice_gfc *filterChooserD;
  static Fl_Menu_Item menu_filterChooserD[];
  Fl_Button_gfc *browseButtonD;
  Fl_Input_Choice_gfc *scaleChooserD;
  static Fl_Menu_Item menu_scaleChooserD[];
  Fl_Button *reloadButtonD;
  Fl_Check_Button *cropD;
  Fl_Value_Input *gammaSliderD;
  Fl_Choice_gfc *formatD;
  static Fl_Menu_Item menu_formatD[];
  Fl_Menu_Button *recentButtonD;
  Fl_Input *fileNameInputD;
  Fl_Choice_gfc *loadModeD;
  static Fl_Menu_Item menu_loadModeD[];
  Fl_Output *estimatesD;
  Fl_Button_gfc *unloadAndClearD;
  Fl_Choice_gfc *channelsChoiceD;
  Fl_Button_gfc *startD;
  Fl_Button_gfc *addToQueueButton;
  Fl_Button_gfc *openPlayListButton;
  Fl_Button *reduceButton;
};
#endif
