// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef lutWindow_h
#define lutWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "gfclutmanager.h"
extern void lutManagerCB_OTHERS(Fl_Double_Window*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
extern void loadCB(Fl_Group*, void*);
#include <FL/Fl_File_Input.H>
extern void loadCB(Fl_File_Input*, long);
#include "Fl_Button_gfc.h"
extern void lutManagerCB_OTHERS(Fl_Button_gfc*, long);
#include <FL/Fl_Progress.H>
extern void lutManagerCB_OTHERS(Fl_Button_gfc*, void*);
#include "Fl_Choice_gfc.h"
extern void lutManagerCB_OTHERS(Fl_Choice_gfc*, void*);
#include <FL/Fl_Check_Button.H>
extern void lutManagerCB_OTHERS(Fl_Check_Button*, void*);
#include <FL/Fl_Scroll.H>

class LutWindow : public Fl_Double_Window {
public:
  LutWindow(int x, int y, int wi, int height,const char* l) ;
  Fl_Double_Window *lutWindow;
  Fl_File_Input *fileNameInput;
  Fl_Button_gfc *browseButton;
  Fl_Progress *progress;
  Fl_Button_gfc *doneButton;
  Fl_Choice_gfc *loadedLuts;
  Fl_Check_Button *preview;
  Fl_Check_Button *uniform;
  Fl_Scroll *scrollLoaded;
  Fl_Check_Button *autoLoadAllButton;
  Fl_Choice_gfc *defaultLUT;
};
#endif
