// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "lutWindow.h"
#include "UIConstants.h"
#include "UICallbacks.h"

LutWindow::LutWindow(int x, int y, int wi, int height,const char* l) : Fl_Double_Window(300, 300, 300, 300, "Load Window") {
  { lutWindow = new Fl_Double_Window(510, 595, "LUT Manager");
    lutWindow->box(FL_NO_BOX);
    lutWindow->color(FL_BLACK);
    lutWindow->labelcolor((Fl_Color)17);
    lutWindow->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(this));
    { Fl_Box* o = new Fl_Box(0, -4, 1675, 982, "label");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(0, -5, 1542, 1121);
      o->labelcolor((Fl_Color)19);
      { Fl_Group* o = new Fl_Group(3, 31, 497, 38, "Load");
        o->box(FL_BORDER_FRAME);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(18);
        o->labelcolor(FL_INACTIVE_COLOR);
        o->callback((Fl_Callback*)loadCB);
        o->align(FL_ALIGN_TOP_LEFT);
        { fileNameInput = new Fl_File_Input(35, 35, 395, 24, "File");
          fileNameInput->color(FL_FOREGROUND_COLOR);
          fileNameInput->labelsize(12);
          fileNameInput->labelcolor((Fl_Color)19);
          fileNameInput->callback((Fl_Callback*)loadCB, (void*)(LOADFILENAME_ID));
          fileNameInput->when(FL_WHEN_CHANGED);
          fileNameInput->hide();
          fileNameInput->deactivate();
        } // Fl_File_Input* fileNameInput
        { browseButton = new Fl_Button_gfc(435, 36, 58, 27, "Browse");
          browseButton->box(FL_UP_BOX);
          browseButton->color(FL_FOREGROUND_COLOR);
          browseButton->selection_color(FL_BACKGROUND_COLOR);
          browseButton->labeltype(FL_NORMAL_LABEL);
          browseButton->labelfont(0);
          browseButton->labelsize(12);
          browseButton->labelcolor(FL_FOREGROUND_COLOR);
          browseButton->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTBROWSE_ID));
          browseButton->align(FL_ALIGN_CENTER);
          browseButton->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* browseButton
        { progress = new Fl_Progress(9, 37, 422, 25);
          progress->box(FL_FLAT_BOX);
          progress->color(FL_FOREGROUND_COLOR);
          progress->selection_color((Fl_Color)58);
          progress->labelcolor((Fl_Color)31);
        } // Fl_Progress* progress
        o->end();
      } // Fl_Group* o
      { doneButton = new Fl_Button_gfc(410, 558, 95, 27, "Done");
        doneButton->tooltip("Start Loading!");
        doneButton->box(FL_UP_BOX);
        doneButton->down_box(FL_DOWN_BOX);
        doneButton->color(FL_INACTIVE_COLOR);
        doneButton->selection_color(FL_BACKGROUND_COLOR);
        doneButton->labeltype(FL_NORMAL_LABEL);
        doneButton->labelfont(1);
        doneButton->labelsize(21);
        doneButton->labelcolor(FL_BACKGROUND2_COLOR);
        doneButton->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTDONE_ID));
        doneButton->align(FL_ALIGN_CENTER);
        doneButton->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* doneButton
      { Fl_Group* o = new Fl_Group(10, 483, 485, 52, "Visualize");
        o->box(FL_BORDER_FRAME);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(18);
        o->labelcolor(FL_INACTIVE_COLOR);
        o->align(FL_ALIGN_TOP_LEFT);
        { loadedLuts = new Fl_Choice_gfc(52, 497, 288, 21, "LUT");
          loadedLuts->box(FL_FLAT_BOX);
          loadedLuts->down_box(FL_BORDER_BOX);
          loadedLuts->color(FL_BACKGROUND_COLOR);
          loadedLuts->selection_color(FL_SELECTION_COLOR);
          loadedLuts->labeltype(FL_NORMAL_LABEL);
          loadedLuts->labelfont(1);
          loadedLuts->labelsize(14);
          loadedLuts->labelcolor(FL_INACTIVE_COLOR);
          loadedLuts->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTCHANGEPREVIEW_ID));
          loadedLuts->align(FL_ALIGN_LEFT);
          loadedLuts->when(FL_WHEN_RELEASE);
        } // Fl_Choice_gfc* loadedLuts
        { preview = new Fl_Check_Button(345, 493, 55, 15, "On");
          preview->down_box(FL_FLAT_BOX);
          preview->color(FL_INACTIVE_COLOR);
          preview->selection_color((Fl_Color)31);
          preview->labelcolor((Fl_Color)25);
          preview->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTPREVIEW_ID));
        } // Fl_Check_Button* preview
        { uniform = new Fl_Check_Button(345, 512, 90, 16, "Uniform");
          uniform->down_box(FL_FLAT_BOX);
          uniform->color(FL_INACTIVE_COLOR);
          uniform->selection_color((Fl_Color)31);
          uniform->labelcolor((Fl_Color)25);
          uniform->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTPREVIEW_ID));
        } // Fl_Check_Button* uniform
        o->end();
      } // Fl_Group* o
      { scrollLoaded = new Fl_Scroll(7, 97, 497, 269, "Loaded");
        scrollLoaded->box(FL_BORDER_FRAME);
        scrollLoaded->color(FL_INACTIVE_COLOR);
        scrollLoaded->labelfont(1);
        scrollLoaded->labelsize(18);
        scrollLoaded->labelcolor(FL_INACTIVE_COLOR);
        scrollLoaded->align(FL_ALIGN_TOP_LEFT);
        scrollLoaded->end();
      } // Fl_Scroll* scrollLoaded
      { autoLoadAllButton = new Fl_Check_Button(373, 80, 64, 15, "Auto-Load All");
        autoLoadAllButton->down_box(FL_FLAT_BOX);
        autoLoadAllButton->color(FL_INACTIVE_COLOR);
        autoLoadAllButton->selection_color((Fl_Color)31);
        autoLoadAllButton->labelcolor(FL_LIGHT1);
        autoLoadAllButton->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTAUTOLOADALL_ID));
      } // Fl_Check_Button* autoLoadAllButton
      { Fl_Group* o = new Fl_Group(9, 401, 496, 44, "Default LUT");
        o->box(FL_BORDER_FRAME);
        o->color(FL_INACTIVE_COLOR);
        o->labelfont(1);
        o->labelsize(18);
        o->labelcolor(FL_INACTIVE_COLOR);
        o->align(FL_ALIGN_TOP_LEFT);
        { defaultLUT = new Fl_Choice_gfc(51, 415, 288, 21, "LUT");
          defaultLUT->tooltip("This is the LUT that will be applied by default on all viewports. Can be over\
riden by setting  the environment variable JEFECHECK_DEFAULT_LUT to the LUT\'s\
 filename (without the file path)");
          defaultLUT->box(FL_FLAT_BOX);
          defaultLUT->down_box(FL_BORDER_BOX);
          defaultLUT->color(FL_BACKGROUND_COLOR);
          defaultLUT->selection_color(FL_SELECTION_COLOR);
          defaultLUT->labeltype(FL_NORMAL_LABEL);
          defaultLUT->labelfont(1);
          defaultLUT->labelsize(14);
          defaultLUT->labelcolor(FL_INACTIVE_COLOR);
          defaultLUT->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTDEFAULTLUT_ID));
          defaultLUT->align(FL_ALIGN_LEFT);
          defaultLUT->when(FL_WHEN_RELEASE);
        } // Fl_Choice_gfc* defaultLUT
        o->end();
      } // Fl_Group* o
      { Fl_Button_gfc* o = new Fl_Button_gfc(292, 75, 78, 20, "Unload All");
        o->box(FL_UP_BOX);
        o->color(FL_BACKGROUND_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(FL_FOREGROUND_COLOR);
        o->callback((Fl_Callback*)lutManagerCB_OTHERS, (void*)(LUTUNLOADALL_ID));
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      } // Fl_Button_gfc* o
      o->end();
    } // Fl_Group* o
    lutWindow->set_non_modal();
    lutWindow->size_range(510, 595, 510, 595);
    lutWindow->end();
  } // Fl_Double_Window* lutWindow
}
