// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef mainWindowTest_h
#define mainWindowTest_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Light_Button.H>
extern void controlBarCB(Fl_Light_Button*, long);
#include "trackwidget.h"
#include <FL/Fl_Slider.H>
extern void controlBarCB(Fl_Slider*, void*);
#include <FL/Fl_Button.H>
extern void controlBarCB(Fl_Button*, long);
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Round_Button.H>
extern void controlBarCB(Fl_Round_Button*, long);
#include <FL/Fl_Value_Input.H>
extern void controlBarCB(Fl_Value_Input*, void*);
#include <FL/Fl_Menu_Button.H>
extern void menuCB(Fl_Menu_*, void*);
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Counter.H>
extern void controlBarCB(Fl_Counter*, long);
#include <FL/Fl_Choice.H>
extern void controlBarCB(Fl_Choice*, void*);
#include <FL/Fl_Input_Choice.H>
extern void controlBarCB(Fl_Input_Choice*, long);
extern void controlBarCB(Fl_Button*, void*);
#include "GlViewport.h"
extern void controlBarCB(GlViewport*, void*);
#include <FL/Fl_Menu_Bar.H>
extern void controlBarCB(Fl_Menu_*, void*);

class MainWindow {
public:
  MainWindow(int x, int y, int wi, int height, const char* l);
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  Fl_Box *bgBox;
  Fl_Group *controlBarGroup;
  Fl_Light_Button *trackAActiveTogle;
  Fl_Light_Button *trackBActiveTogle;
  Fl_Light_Button *trackCActiveTogle;
  Fl_Light_Button *trackDActiveTogle;
  TrackWidget *trackABar;
  TrackWidget *trackBBar;
  TrackWidget *trackCBar;
  TrackWidget *trackDBar;
  Fl_Box *bgBoxForTimeline;
  Fl_Slider *timeLine;
  Fl_Button *rewindButton;
  Fl_Button *backOneButton;
  Fl_Button *playButton;
  Fl_Button *forwardOneButton;
  Fl_Button *ffButton;
  Fl_Value_Output *currentFPSOutput;
  Fl_Output *timeCodeOutput;
  Fl_Round_Button *frameModeSingleRadio;
  Fl_Round_Button *frameModeDoubleRadio;
  Fl_Round_Button *frameModeQuadRadio;
  Fl_Round_Button *loopOnceRadio;
  Fl_Round_Button *loopLoopRadio;
  Fl_Round_Button *loopBounceRadio;
  Fl_Value_Input *playUpToInput;
  Fl_Value_Input *playFromInput;
  static Fl_Menu_Item menu_BG[];
  Fl_Check_Button *infinitePlaybackToggle;
  Fl_Button *abortA;
  Fl_Button *abortB;
  Fl_Button *abortC;
  Fl_Button *abortD;
  Fl_Counter *timeLineInput;
  Fl_Group *layouts1;
  Fl_Choice *q1Choice;
  static Fl_Menu_Item menu_q1Choice[];
  Fl_Input_Choice *q1AspectChoice;
  static Fl_Menu_Item menu_q1AspectChoice[];
  Fl_Button *q1CropPos;
  Fl_Value_Input *q1Scale;
  Fl_Value_Input *q1X;
  Fl_Value_Input *q1Y;
  Fl_Value_Input *q1rZ;
  Fl_Button *q1Flip;
  Fl_Button *q1Crop;
  Fl_Button *q1Flop;
  Fl_Button *channelRButton1;
  Fl_Button *channelGButton1;
  Fl_Button *channelBButton1;
  Fl_Button *channelAButton1;
  Fl_Button *menuA;
  Fl_Button *menuB;
  Fl_Button *menuC;
  Fl_Button *menuD;
  Fl_Group *layouts2;
  Fl_Choice *q2Choice;
  static Fl_Menu_Item menu_q2Choice[];
  Fl_Input_Choice *q2AspectChoice;
  static Fl_Menu_Item menu_q2AspectChoice[];
  Fl_Button *q2CropPos;
  Fl_Value_Input *q2Scale;
  Fl_Value_Input *q2X;
  Fl_Value_Input *q2Y;
  Fl_Value_Input *q2rZ;
  Fl_Button *q2Flip;
  Fl_Button *q2Crop;
  Fl_Button *q2Flop;
  Fl_Button *channelRButton2;
  Fl_Button *channelGButton2;
  Fl_Button *channelBButton2;
  Fl_Button *channelAButton2;
  Fl_Group *layouts3;
  Fl_Choice *q3Choice;
  static Fl_Menu_Item menu_q3Choice[];
  Fl_Input_Choice *q3AspectChoice;
  static Fl_Menu_Item menu_q3AspectChoice[];
  Fl_Button *q3CropPos;
  Fl_Value_Input *q3Scale;
  Fl_Value_Input *q3X;
  Fl_Value_Input *q3Y;
  Fl_Value_Input *q3rZ;
  Fl_Button *q3Flip;
  Fl_Button *q3Crop;
  Fl_Button *q3Flop;
  Fl_Button *channelRButton3;
  Fl_Button *channelGButton3;
  Fl_Button *channelBButton3;
  Fl_Button *channelAButton3;
  Fl_Group *layouts4;
  Fl_Choice *q4Choice;
  static Fl_Menu_Item menu_q4Choice[];
  Fl_Input_Choice *q4AspectChoice;
  static Fl_Menu_Item menu_q4AspectChoice[];
  Fl_Button *q4CropPos;
  Fl_Value_Input *q4Scale;
  Fl_Value_Input *q4X;
  Fl_Value_Input *q4Y;
  Fl_Value_Input *q4rZ;
  Fl_Button *q4Flip;
  Fl_Button *q4Crop;
  Fl_Button *q4Flop;
  Fl_Button *channelRButton4;
  Fl_Button *channelGButton4;
  Fl_Button *channelBButton4;
  Fl_Button *channelAButton4;
  Fl_Button *fxButton1;
  Fl_Input_Choice *targetFPSInput;
  static Fl_Menu_Item menu_targetFPSInput[];
  GlViewport *vp;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
  Fl_Box *LogoOllinGray;
  Fl_Box *LogoOllin;
};
#endif
