// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef mainWindow_h
#define mainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Round_Button.H>
extern void controlBarCB(Fl_Round_Button*, long);
#include "Fl_Choice_gfc.h"
extern void controlBarCB(Fl_Choice_gfc*, void*);
#include "Fl_Input_Choice_gfc.h"
extern void controlBarCB(Fl_Input_Choice_gfc*, long);
#include <FL/Fl_Button.H>
extern void controlBarCB(Fl_Button*, void*);
#include <FL/Fl_Value_Input.H>
extern void controlBarCB(Fl_Value_Input*, void*);
#include "Fl_Button_gfc.h"
extern void controlBarCB(Fl_Button_gfc*, void*);
#include "Fl_Button_RGBA_gfc.h"
extern void controlBarCB(Fl_Button_RGBA_gfc*, void*);
extern void controlBarCB(Fl_Button_gfc*, long);
extern void controlBarCB(Fl_Button*, long);
#include "trackwidget.h"
extern void tracksBarCB(TrackWidget*, void*);
#include "Fl_Slider_Timeline_gfc.h"
extern void controlBarCB(Fl_Slider_Timeline_gfc*, void*);
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Menu_Bar.H>
extern void menuCB(Fl_Menu_*, void*);
extern void controlBarCB(Fl_Menu_*, void*);
#include "GlViewport.h"
extern void controlBarCB(GlViewport*, void*);
extern void controlBarCB(Fl_Group*, void*);

class MainWindow {
#include "Fl_Choice_gfc.h"
#include "Fl_Input_Choice_gfc.h"
public:
  MainWindow(int x, int y, int wi, int height, const char* l);
private:
  bool controlsHidden; 
  int fullscreenActive; 
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  Fl_Box *bgBox;
  Fl_Group *controlBarGroup;
  Fl_Group *nonResizable;
  Fl_Output *timeCodeOutput;
  Fl_Group *framingModes;
  Fl_Round_Button *frameModeSingleRadio;
  Fl_Round_Button *frameModeDoubleRadio;
  Fl_Round_Button *frameModeDoubleVertRadio;
  Fl_Round_Button *frameModeQuadRadio;
  Fl_Group *layoutsGroup;
  Fl_Group *layouts1;
  Fl_Choice_gfc *q1Choice;
  static Fl_Menu_Item menu_q1Choice[];
  Fl_Input_Choice_gfc *q1AspectChoice;
  static Fl_Menu_Item menu_q1AspectChoice[];
  Fl_Button *q1CropPos;
  Fl_Value_Input *q1Scale;
  Fl_Value_Input *q1X;
  Fl_Value_Input *q1Y;
  Fl_Button_gfc *q1Crop;
  Fl_Value_Input *q1Gamma;
  Fl_Value_Input *q1Contrast;
  Fl_Value_Input *q1Brightness;
  Fl_Value_Input *q1Saturation;
  Fl_Value_Input *q1Exposure;
  Fl_Choice_gfc *q1LUT;
  static Fl_Menu_Item menu_q1LUT[];
  Fl_Value_Input *q1rZ;
  Fl_Button_RGBA_gfc *q1RGBA;
  Fl_Button_gfc *q1Flip;
  Fl_Button_gfc *q1Flop;
  Fl_Group *layouts2;
  Fl_Choice_gfc *q2Choice;
  static Fl_Menu_Item menu_q2Choice[];
  Fl_Input_Choice_gfc *q2AspectChoice;
  static Fl_Menu_Item menu_q2AspectChoice[];
  Fl_Button *q2CropPos;
  Fl_Value_Input *q2Scale;
  Fl_Value_Input *q2X;
  Fl_Value_Input *q2Y;
  Fl_Button_gfc *q2Crop;
  Fl_Value_Input *q2Gamma;
  Fl_Value_Input *q2Contrast;
  Fl_Value_Input *q2Brightness;
  Fl_Value_Input *q2Saturation;
  Fl_Value_Input *q2Exposure;
  Fl_Choice_gfc *q2LUT;
  static Fl_Menu_Item menu_q2LUT[];
  Fl_Value_Input *q2rZ;
  Fl_Button_RGBA_gfc *q2RGBA;
  Fl_Button_gfc *q2Flip;
  Fl_Button_gfc *q2Flop;
  Fl_Group *layouts3;
  Fl_Choice_gfc *q3Choice;
  static Fl_Menu_Item menu_q3Choice[];
  Fl_Input_Choice_gfc *q3AspectChoice;
  static Fl_Menu_Item menu_q3AspectChoice[];
  Fl_Button *q3CropPos;
  Fl_Value_Input *q3Scale;
  Fl_Value_Input *q3X;
  Fl_Value_Input *q3Y;
  Fl_Button_gfc *q3Crop;
  Fl_Value_Input *q3Gamma;
  Fl_Value_Input *q3Contrast;
  Fl_Value_Input *q3Brightness;
  Fl_Value_Input *q3Saturation;
  Fl_Value_Input *q3Exposure;
  Fl_Choice_gfc *q3LUT;
  static Fl_Menu_Item menu_q3LUT[];
  Fl_Value_Input *q3rZ;
  Fl_Button_RGBA_gfc *q3RGBA;
  Fl_Button_gfc *q3Flip;
  Fl_Button_gfc *q3Flop;
  Fl_Group *layouts4;
  Fl_Choice_gfc *q4Choice;
  static Fl_Menu_Item menu_q4Choice[];
  Fl_Input_Choice_gfc *q4AspectChoice;
  static Fl_Menu_Item menu_q4AspectChoice[];
  Fl_Button *q4CropPos;
  Fl_Value_Input *q4Scale;
  Fl_Value_Input *q4X;
  Fl_Value_Input *q4Y;
  Fl_Button_gfc *q4Crop;
  Fl_Value_Input *q4Gamma;
  Fl_Value_Input *q4Contrast;
  Fl_Value_Input *q4Brightness;
  Fl_Value_Input *q4Saturation;
  Fl_Value_Input *q4Exposure;
  Fl_Choice_gfc *q4LUT;
  static Fl_Menu_Item menu_q4LUT[];
  Fl_Value_Input *q4rZ;
  Fl_Button_RGBA_gfc *q4RGBA;
  Fl_Button_gfc *q4Flip;
  Fl_Button_gfc *q4Flop;
  Fl_Group *activeViewportGroup;
  Fl_Round_Button *activeViewport0;
  Fl_Round_Button *activeViewport1;
  Fl_Round_Button *activeViewport2;
  Fl_Round_Button *activeViewport3;
  Fl_Value_Input *playUpToInput;
  Fl_Value_Input *playFromInput;
  Fl_Button_gfc *abortA;
  Fl_Button_gfc *abortB;
  Fl_Button_gfc *abortC;
  Fl_Button_gfc *abortD;
  Fl_Button *menuA;
  Fl_Button *menuB;
  Fl_Button *menuC;
  Fl_Button *menuD;
  Fl_Value_Input *timeLineInput;
  Fl_Button *fxButton1;
  Fl_Choice_gfc *loopPriorityChoice;
  static Fl_Menu_Item menu_loopPriorityChoice[];
  Fl_Value_Input *outPointInput;
  Fl_Value_Input *inPointInput;
  Fl_Choice_gfc *viewportLayoutChoice;
  static Fl_Menu_Item menu_viewportLayoutChoice[];
  Fl_Group *Resizable;
  Fl_Group *tracksAndTimeline;
  TrackWidget *trackABar;
  TrackWidget *trackBBar;
  TrackWidget *trackCBar;
  TrackWidget *trackDBar;
  Fl_Slider_Timeline_gfc *timeLine;
  Fl_Group *buttonsAndLogo;
  Fl_Group *Logos;
  Fl_Box *LogoOllinGray;
  Fl_Box *LogoOllin;
  Fl_Group *buttons;
  Fl_Button_gfc *rewindButton;
  Fl_Button_gfc *backOneButton;
  Fl_Button_gfc *playRevButton;
  Fl_Button_gfc *playPauseButton;
  Fl_Button_gfc *playFwdButton;
  Fl_Button_gfc *forwardOneButton;
  Fl_Button_gfc *ffButton;
  Fl_Round_Button *loopOnceRadio;
  Fl_Round_Button *loopLoopRadio;
  Fl_Round_Button *loopBounceRadio;
  Fl_Value_Output *currentFPSOutput;
  Fl_Input_Choice_gfc *targetFPSInput;
  static Fl_Menu_Item menu_targetFPSInput[];
  Fl_Group *logoButtonsSpacer;
  Fl_Button_gfc *addToPlaylistButton;
  Fl_Button_gfc *playlistButton;
  Fl_Button_gfc *fxButton;
  Fl_Button_gfc *remoteButton;
  Fl_Button_gfc *renderButton;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
  static Fl_Menu_Item *menuLayoutSingle;
  GlViewport *vp;
  Fl_Group *menuLogos;
  void toggleFullscreen();
  void toggleHideControls(int force=-1);
};
#endif
