// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "minSpecsWindow.h"
#include "UIConstants.h"
#include "UICallbacks.h"

MinSpecsWindow::MinSpecsWindow(int x, int y, int wi, int height, const char* l) {
}

Fl_Double_Window* MinSpecsWindow::make_window() {
  { minSpecsWindow = new Fl_Double_Window(281, 353, "JefeCheck Host System Specs");
    minSpecsWindow->color(FL_FOREGROUND_COLOR);
    minSpecsWindow->selection_color(FL_FOREGROUND_COLOR);
    minSpecsWindow->labelcolor(FL_BACKGROUND2_COLOR);
    minSpecsWindow->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, -8, 619, 553, "label");
      o->box(FL_FLAT_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_Box* o
    { versionLabel = new Fl_Box(5, 4, 265, 16, "JefeCheck Video Card Check");
      versionLabel->labelfont(1);
      versionLabel->labelsize(16);
      versionLabel->labelcolor((Fl_Color)31);
      versionLabel->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    } // Fl_Box* versionLabel
    { Fl_Pack* o = new Fl_Pack(0, 25, 315, 340);
      o->type(1);
      { Fl_Scroll* o = new Fl_Scroll(0, 25, 315, 340);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        { Fl_Pack* o = new Fl_Pack(0, 25, 315, 330);
          { glVersion = new Fl_Box(20, 32, 270, 16, "label");
            glVersion->labelsize(12);
            glVersion->labelcolor((Fl_Color)31);
            glVersion->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* glVersion
          { glVendor = new Fl_Box(20, 49, 270, 16, "label");
            glVendor->labelsize(12);
            glVendor->labelcolor((Fl_Color)31);
            glVendor->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* glVendor
          { glRenderer = new Fl_Box(20, 65, 270, 16, "label");
            glRenderer->labelsize(12);
            glRenderer->labelcolor((Fl_Color)31);
            glRenderer->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* glRenderer
          { maxTexSize = new Fl_Box(20, 84, 270, 16, "label");
            maxTexSize->labelsize(12);
            maxTexSize->labelcolor((Fl_Color)31);
            maxTexSize->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* maxTexSize
          { maxViewportSize = new Fl_Box(20, 101, 270, 16, "label");
            maxViewportSize->labelsize(12);
            maxViewportSize->labelcolor((Fl_Color)31);
            maxViewportSize->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* maxViewportSize
          { glewVersion = new Fl_Box(20, 122, 270, 16, "label");
            glewVersion->labelsize(12);
            glewVersion->labelcolor((Fl_Color)31);
            glewVersion->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* glewVersion
          { Fl_Box* o = new Fl_Box(5, 141, 270, 19, "Required for Basic Playback");
            o->labelfont(1);
            o->labelsize(12);
            o->labelcolor((Fl_Color)31);
            o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* o
          { textureRectangle = new Fl_Check_Button(20, 160, 105, 15, "Texture Rectangle");
            textureRectangle->down_box(FL_DOWN_BOX);
            textureRectangle->labelsize(11);
            textureRectangle->labelcolor((Fl_Color)1);
            textureRectangle->deactivate();
          } // Fl_Check_Button* textureRectangle
          { Fl_Box* o = new Fl_Box(5, 176, 270, 19, "Required for FX Processing");
            o->labelfont(1);
            o->labelsize(12);
            o->labelcolor((Fl_Color)31);
            o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* o
          { shaderObjects = new Fl_Check_Button(20, 195, 64, 15, "Shader Objects");
            shaderObjects->down_box(FL_DOWN_BOX);
            shaderObjects->labelsize(11);
            shaderObjects->labelcolor((Fl_Color)1);
            shaderObjects->deactivate();
          } // Fl_Check_Button* shaderObjects
          { glsl = new Fl_Check_Button(20, 211, 64, 15, "GL Shading Language");
            glsl->down_box(FL_DOWN_BOX);
            glsl->labelsize(11);
            glsl->labelcolor((Fl_Color)1);
            glsl->deactivate();
          } // Fl_Check_Button* glsl
          { fbo = new Fl_Check_Button(20, 230, 60, 15, "Frame Buffer Objects");
            fbo->down_box(FL_DOWN_BOX);
            fbo->labelsize(11);
            fbo->labelcolor((Fl_Color)1);
            fbo->deactivate();
          } // Fl_Check_Button* fbo
          { Fl_Box* o = new Fl_Box(4, 245, 270, 19, "Required for HDR Processing");
            o->labelfont(1);
            o->labelsize(12);
            o->labelcolor((Fl_Color)31);
            o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* o
          { textureFloat = new Fl_Check_Button(20, 265, 64, 15, "Texture Float");
            textureFloat->down_box(FL_DOWN_BOX);
            textureFloat->labelsize(11);
            textureFloat->labelcolor((Fl_Color)1);
            textureFloat->deactivate();
          } // Fl_Check_Button* textureFloat
          { textureHalf = new Fl_Check_Button(20, 280, 64, 15, "Texture Half");
            textureHalf->down_box(FL_DOWN_BOX);
            textureHalf->labelsize(11);
            textureHalf->labelcolor((Fl_Color)1);
            textureHalf->deactivate();
          } // Fl_Check_Button* textureHalf
          { Fl_Box* o = new Fl_Box(5, 298, 270, 17, "Optional Extensions");
            o->labelfont(1);
            o->labelsize(12);
            o->labelcolor((Fl_Color)31);
            o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          } // Fl_Box* o
          { PBO = new Fl_Check_Button(20, 330, 64, 15, "Pixel Buffer Objects");
            PBO->down_box(FL_DOWN_BOX);
            PBO->labelsize(11);
            PBO->labelcolor((Fl_Color)1);
            PBO->deactivate();
          } // Fl_Check_Button* PBO
          { s3tc = new Fl_Check_Button(20, 315, 64, 15, "S3TC Texture Compression");
            s3tc->down_box(FL_DOWN_BOX);
            s3tc->labelsize(11);
            s3tc->labelcolor((Fl_Color)1);
            s3tc->deactivate();
          } // Fl_Check_Button* s3tc
          o->end();
        } // Fl_Pack* o
        o->end();
        Fl_Group::current()->resizable(o);
      } // Fl_Scroll* o
      o->end();
    } // Fl_Pack* o
    minSpecsWindow->size_range(281, 355, 281, 355);
    minSpecsWindow->end();
    minSpecsWindow->resizable(minSpecsWindow);
  } // Fl_Double_Window* minSpecsWindow
  return minSpecsWindow;
}
