// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef minSpecsWindow_h
#define minSpecsWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Check_Button.H>

class MinSpecsWindow {
public:
  MinSpecsWindow(int x, int y, int wi, int height, const char* l);
  Fl_Double_Window* make_window();
  Fl_Double_Window *minSpecsWindow;
  Fl_Box *versionLabel;
  Fl_Box *glVersion;
  Fl_Box *glVendor;
  Fl_Box *glRenderer;
  Fl_Box *maxTexSize;
  Fl_Box *maxViewportSize;
  Fl_Box *glewVersion;
  Fl_Check_Button *textureRectangle;
  Fl_Check_Button *shaderObjects;
  Fl_Check_Button *glsl;
  Fl_Check_Button *fbo;
  Fl_Check_Button *textureFloat;
  Fl_Check_Button *textureHalf;
  Fl_Check_Button *PBO;
  Fl_Check_Button *s3tc;
};
#endif
