// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "moreOptionWindow.h"

Fl_Menu_Item moreOptionsPopup::menu_holdFrame[] = {
 {"none", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"current", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {"edge", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};
#include "UIConstants.h"
#include <FL/Fl_Menu_Window.h>
#include "Fl_Choice_gfc.h"
#include "UICallbacks.h"

moreOptionsPopup::moreOptionsPopup(int x, int y, int wi, int height, const char* l) {
  { moreOptions = new Fl_Menu_Window(160, 100, "Track Options");
    moreOptions->box(FL_FLAT_BOX);
    moreOptions->color(FL_DARK_GREEN);
    moreOptions->selection_color(FL_BACKGROUND_COLOR);
    moreOptions->labeltype(FL_NO_LABEL);
    moreOptions->labelfont(0);
    moreOptions->labelsize(14);
    moreOptions->labelcolor((Fl_Color)17);
    moreOptions->user_data((void*)(this));
    moreOptions->align(FL_ALIGN_TOP);
    moreOptions->when(FL_WHEN_RELEASE);
    { Fl_Box* o = bgBox = new Fl_Box(-2, 0, 260, 220, "TrackA Options");
      bgBox->box(FL_DOWN_BOX);
      bgBox->color(FL_FOREGROUND_COLOR);
      bgBox->labelfont(1);
      bgBox->labelcolor((Fl_Color)31);
      bgBox->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_Box* bgBox
    { Fl_Value_Input* o = frameOffset = new Fl_Value_Input(75, 23, 50, 18, "Frame Offset");
      frameOffset->box(FL_FLAT_BOX);
      frameOffset->color(FL_INACTIVE_COLOR);
      frameOffset->labelfont(1);
      frameOffset->labelsize(10);
      frameOffset->labelcolor(FL_INACTIVE_COLOR);
      frameOffset->minimum(-999999);
      frameOffset->maximum(1e+007);
      frameOffset->step(1);
      frameOffset->textcolor(31);
      frameOffset->callback((Fl_Callback*)moreOptionsCB, (void*)(MOFRAMEOFFSET_ID));
      o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
    } // Fl_Value_Input* frameOffset
    { Fl_Button_gfc* o = new Fl_Button_gfc(135, 4, 20, 14, "x");
      o->box(FL_THIN_UP_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(1);
      o->labelsize(14);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->callback((Fl_Callback*)moreOptionsCB, (void*)(MOCLOSE_ID));
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    } // Fl_Button_gfc* o
    { unload = new Fl_Button_gfc(5, 76, 80, 20, "Unload Track");
      unload->box(FL_UP_BOX);
      unload->color(FL_FOREGROUND_COLOR);
      unload->selection_color(FL_BACKGROUND_COLOR);
      unload->labeltype(FL_NORMAL_LABEL);
      unload->labelfont(1);
      unload->labelsize(10);
      unload->labelcolor(FL_BACKGROUND2_COLOR);
      unload->callback((Fl_Callback*)moreOptionsCB, (void*)(MOUNLOADTRACK_ID));
      unload->align(FL_ALIGN_CENTER);
      unload->when(FL_WHEN_RELEASE);
    } // Fl_Button_gfc* unload
    { holdFrame = new Fl_Choice_gfc(74, 47, 55, 18, "Hold Frame");
      holdFrame->box(FL_FLAT_BOX);
      holdFrame->down_box(FL_BORDER_BOX);
      holdFrame->color(FL_BACKGROUND_COLOR);
      holdFrame->selection_color(FL_SELECTION_COLOR);
      holdFrame->labeltype(FL_NORMAL_LABEL);
      holdFrame->labelfont(1);
      holdFrame->labelsize(10);
      holdFrame->labelcolor(FL_INACTIVE_COLOR);
      holdFrame->callback((Fl_Callback*)moreOptionsCB, (void*)(MOHOLDFRAME_ID));
      holdFrame->align(FL_ALIGN_LEFT);
      holdFrame->when(FL_WHEN_RELEASE);
      holdFrame->menu(menu_holdFrame);
    } // Fl_Choice_gfc* holdFrame
    moreOptions->set_non_modal();
    moreOptions->clear_border();
    moreOptions->size_range(160, 100, 160, 100);
    moreOptions->end();
  } // Fl_Menu_Window* moreOptions
}

void moreOptionsPopup::popup() {
  moreOptions->position(Fl::event_x_root(), Fl::event_y_root());       // position window at cursor
        moreOptions->show();
}
