// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef moreOptionWindow_h
#define moreOptionWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Menu_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
extern void moreOptionsCB(Fl_Value_Input*, void*);
#include "Fl_Button_gfc.h"
extern void moreOptionsCB(Fl_Button_gfc*, void*);
#include "Fl_Choice_gfc.h"
extern void moreOptionsCB(Fl_Choice_gfc*, void*);

class moreOptionsPopup {
public:
  moreOptionsPopup(int x, int y, int wi, int height, const char* l);
  Fl_Menu_Window *moreOptions;
  Fl_Box *bgBox;
  Fl_Value_Input *frameOffset;
  Fl_Button_gfc *unload;
  Fl_Choice_gfc *holdFrame;
  static Fl_Menu_Item menu_holdFrame[];
  void popup();
  char ID; 
};
#endif
