// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef preferencesWindow_h
#define preferencesWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
extern void PreferencesCB(Fl_Round_Button*, void*);
#include <FL/Fl_Input.H>
#include "Fl_Button_gfc.h"
extern void PreferencesCB(Fl_Button_gfc*, void*);
#include <FL/Fl_Value_Slider.H>
extern void PreferencesCB(Fl_Value_Slider*, void*);
#include <FL/Fl_Check_Button.H>
extern void PreferencesCB(Fl_Check_Button*, void*);
#include <FL/Fl_Value_Input.H>
extern void PreferencesCB(Fl_Value_Input*, void*);
#include "Fl_Spinner_gfc.h"
extern void PreferencesCB(Fl_Spinner_gfc*, void*);
#include <FL/Fl_Browser.H>
extern void PreferencesCB(Fl_Browser*, void*);

class PreferencesWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *preferencesWindow;
  Fl_Box *bg;
  Fl_Tabs *tabs;
  Fl_Round_Button *startFullscreenCheckBox;
  Fl_Round_Button *loadWindowOnStartupCheckBox;
  Fl_Input *defaultBrowsePath;
  Fl_Round_Button *attemptToRecoverFromCrashCheckBox;
  Fl_Value_Slider *bgColor;
  Fl_Value_Slider *percentageOfRam;
  Fl_Check_Button *forceGFLLoading;
  Fl_Check_Button *frawProxiesAtFullResolution;
  Fl_Check_Button *dontUseInactiveMemory;
  Fl_Check_Button *forceSingleBufferedFXs;
  Fl_Check_Button *continueLoadingOnError;
  Fl_Check_Button *vsync;
  Fl_Value_Input *maximumFramesInQueue;
  Fl_Check_Button *balanceReads;
  Fl_Value_Slider *histogramQuality;
  Fl_Check_Button *processorPriority;
  Fl_Value_Input *textDisplayFontSize;
  Fl_Value_Input *textDisplayOpacity;
  Fl_Value_Input *textDisplayColor;
  Fl_Value_Input *ActionFeedbackSize;
  Fl_Value_Input *ActionFeedbackFadeDelay;
  Fl_Group *formatsTab;
  Fl_Check_Button *exrIgnoreDisplayWindow;
  Fl_Check_Button *exrIgnoreHeadersAspectRatio;
  Fl_Check_Button *exrEnableExposureTransformOnLoad;
  Fl_Value_Input *exrExposure;
  Fl_Value_Input *exrDefog;
  Fl_Value_Input *exrKneeLow;
  Fl_Value_Input *exrKneeHigh;
  Fl_Value_Input *exrGamma;
  Fl_Group *remoteSessionTab;
  Fl_Value_Input *fontSize;
  Fl_Value_Input *fadeDelay;
  Fl_Value_Input *opacity;
  Fl_Check_Button *autoFade;
  Fl_Check_Button *textBG;
  Fl_Value_Input *chatLines;
  Fl_Value_Input *remotePointerFontSize;
  Fl_Value_Input *remotePointerFadeDelay;
  Fl_Value_Input *remotePointerTrailLenght;
  Fl_Check_Button *remotePointerFade;
  Fl_Value_Input *remotePointerSize;
  Fl_Check_Button *remotePointerTrail;
  Fl_Box *remotePointerColorSample;
  Fl_Spinner_gfc *remotePointerColor;
  Fl_Value_Input *remoteTransformationsFrequency;
  Fl_Value_Input *remoteFXFrequency;
  Fl_Value_Input *remoteOthersFrequency;
  Fl_Check_Button *remoteSendLoadRequests;
  Fl_Check_Button *remoteAutoAcceptLoadRequests;
  Fl_Group *pathsTab;
  Fl_Check_Button *searchPathsRecursive;
  Fl_Browser *searchPaths;
  Fl_Button_gfc *searchPathBrowse;
  Fl_Button_gfc *searchPathDelete;
  Fl_Check_Button *useSearchPaths;
  // License tab removed for open-source release
};
#endif
