// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "preferencesWindow.h"
#include "UICallbacks.h"
#include "UIConstants.h"
#include "Fl_Button_gfc.h"
#include "Fl_Spinner_gfc.h"

Fl_Double_Window* PreferencesWindow::make_window() {
  { preferencesWindow = new Fl_Double_Window(600, 500, "JefeCheck -Preferences");
    preferencesWindow->user_data((void*)(this));
    { Fl_Box* o = bg = new Fl_Box(0, -1, 600, 501);
      bg->box(FL_FLAT_BOX);
      bg->color(FL_FOREGROUND_COLOR);
      bg->selection_color(FL_DARK3);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
      o->color(fl_rgb_color(32,32,32));
    } // Fl_Box* bg

    // Sidebar
    { sectionList = new Fl_Hold_Browser(5, 5, 120, 450);
      sectionList->box(FL_FLAT_BOX);
      sectionList->color(fl_rgb_color(38,38,38));
      sectionList->textcolor(fl_rgb_color(200,200,200));
      sectionList->textsize(13);
      sectionList->selection_color(fl_rgb_color(60,60,60));
      sectionList->add("General");
      sectionList->add("Text");
      sectionList->add("Engine");
      sectionList->add("Formats");
      sectionList->add("Remote");
      sectionList->add("Paths");
      sectionList->value(1);
      sectionList->callback([](Fl_Widget* w, void* data) {
        PreferencesWindow* pw = (PreferencesWindow*)data;
        int sel = pw->sectionList->value();
        if (sel >= 1 && sel <= 6) pw->showPanel(sel - 1);
      }, (void*)this);
    }

    // === Panel 0: General ===
    { panels[0] = new Fl_Group(130, 5, 465, 450);
      panels[0]->box(FL_FLAT_BOX);
      panels[0]->color(fl_rgb_color(38,38,38));

      { Fl_Flex* col = new Fl_Flex(130, 5, 465, 450, Fl_Flex::COLUMN);
        col->margin(10, 10, 10, 10);
        col->gap(6);

        // -- Section: Startup --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Startup");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 18);
        }

        // Open Load window on startup
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(6);
          { loadWindowOnStartupCheckBox = new Fl_Round_Button(0,0,0,0, "Open Load window on startup");
            loadWindowOnStartupCheckBox->down_box(FL_FLAT_BOX);
            loadWindowOnStartupCheckBox->value(1);
            loadWindowOnStartupCheckBox->color(FL_INACTIVE_COLOR);
            loadWindowOnStartupCheckBox->selection_color((Fl_Color)31);
            loadWindowOnStartupCheckBox->labelcolor((Fl_Color)31);
            loadWindowOnStartupCheckBox->labelsize(12);
            loadWindowOnStartupCheckBox->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 22);
        }

        // Start in fullscreen mode
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(6);
          { startFullscreenCheckBox = new Fl_Round_Button(0,0,0,0, "Start in fullscreen mode");
            startFullscreenCheckBox->down_box(FL_FLAT_BOX);
            startFullscreenCheckBox->color(FL_INACTIVE_COLOR);
            startFullscreenCheckBox->selection_color((Fl_Color)31);
            startFullscreenCheckBox->labelcolor((Fl_Color)31);
            startFullscreenCheckBox->labelsize(12);
            startFullscreenCheckBox->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 22);
        }

        // Attempt to recover from crash
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(6);
          { attemptToRecoverFromCrashCheckBox = new Fl_Round_Button(0,0,0,0, "Attempt to recover from crash");
            attemptToRecoverFromCrashCheckBox->down_box(FL_FLAT_BOX);
            attemptToRecoverFromCrashCheckBox->value(1);
            attemptToRecoverFromCrashCheckBox->color(FL_INACTIVE_COLOR);
            attemptToRecoverFromCrashCheckBox->selection_color((Fl_Color)31);
            attemptToRecoverFromCrashCheckBox->labelcolor((Fl_Color)31);
            attemptToRecoverFromCrashCheckBox->labelsize(12);
            attemptToRecoverFromCrashCheckBox->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 22);
        }

        // Default Browse Path
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(6);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Browse Path");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Input* o = defaultBrowsePath = new Fl_Input(0,0,0,0);
            defaultBrowsePath->tooltip("When browsing for sequences, this will be the default folder the browser opens. Set it to point to the project folder you are currently working on to make browsing easier! This value is overriden by the environment variable JEFECHECK_DEFAULT_BROWSE_PATH");
            defaultBrowsePath->box(FL_FLAT_BOX);
            defaultBrowsePath->color(FL_INACTIVE_COLOR);
            defaultBrowsePath->textcolor(31);
            defaultBrowsePath->textsize(12);
            defaultBrowsePath->when(FL_WHEN_CHANGED);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          }
          { Fl_Button_gfc* o = new Fl_Button_gfc(0,0,0,0, "browse");
            o->box(FL_FLAT_BOX);
            o->color(FL_INACTIVE_COLOR);
            o->selection_color(FL_BACKGROUND_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(14);
            o->labelcolor((Fl_Color)31);
            o->callback((Fl_Callback*)PreferencesCB, (void*)(PATHBROWSEBUTTON_ID));
            o->align(FL_ALIGN_CENTER);
            o->when(FL_WHEN_RELEASE);
            row->fixed(o, 68);
          }
          row->end();
          col->fixed(row, 22);
        }

        // -- Section: Background Color --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Background Color");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Value");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Slider* o = bgColor = new Fl_Value_Slider(0,0,0,0);
            bgColor->tooltip("Set the Value of the gray background color to suit your taste and pupils.");
            bgColor->type(1);
            bgColor->box(FL_FLAT_BOX);
            bgColor->color(FL_INACTIVE_COLOR);
            bgColor->labelcolor((Fl_Color)31);
            bgColor->maximum(127);
            bgColor->step(1);
            bgColor->value(38);
            bgColor->textsize(14);
            bgColor->textcolor(31);
            bgColor->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            o->selection_color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          }
          row->end();
          col->fixed(row, 22);
        }

        // -- Section: Action Feedback --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Action Feedback");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Size");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = ActionFeedbackSize = new Fl_Value_Input(0,0,0,0);
            ActionFeedbackSize->tooltip("Font Size of the Action Feedback Display");
            ActionFeedbackSize->box(FL_FLAT_BOX);
            ActionFeedbackSize->color(FL_INACTIVE_COLOR);
            ActionFeedbackSize->selection_color(FL_FOREGROUND_COLOR);
            ActionFeedbackSize->labelsize(12);
            ActionFeedbackSize->labelcolor((Fl_Color)31);
            ActionFeedbackSize->minimum(8);
            ActionFeedbackSize->maximum(48);
            ActionFeedbackSize->step(1);
            ActionFeedbackSize->value(12);
            ActionFeedbackSize->textsize(12);
            ActionFeedbackSize->textcolor(31);
            ActionFeedbackSize->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 50);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Fade");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 40);
          }
          { Fl_Value_Input* o = ActionFeedbackFadeDelay = new Fl_Value_Input(0,0,0,0);
            ActionFeedbackFadeDelay->tooltip("How long the Action Feedback is displayed in seconds (set to 0 to turn display Off)");
            ActionFeedbackFadeDelay->box(FL_FLAT_BOX);
            ActionFeedbackFadeDelay->color(FL_INACTIVE_COLOR);
            ActionFeedbackFadeDelay->selection_color(FL_FOREGROUND_COLOR);
            ActionFeedbackFadeDelay->labelsize(12);
            ActionFeedbackFadeDelay->labelcolor((Fl_Color)31);
            ActionFeedbackFadeDelay->maximum(10);
            ActionFeedbackFadeDelay->step(0.01);
            ActionFeedbackFadeDelay->value(1);
            ActionFeedbackFadeDelay->textsize(12);
            ActionFeedbackFadeDelay->textcolor(31);
            ActionFeedbackFadeDelay->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 60);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        col->end();
      }

      panels[0]->end();
    } // panels[0] General

    // === Panel 1: Text ===
    { panels[1] = new Fl_Group(130, 5, 465, 450);
      panels[1]->box(FL_FLAT_BOX);
      panels[1]->color(fl_rgb_color(38,38,38));
      panels[1]->hide();
      textTab = panels[1];

      { Fl_Flex* col = new Fl_Flex(130, 5, 465, 450, Fl_Flex::COLUMN);
        col->margin(10, 10, 10, 10);
        col->gap(6);

        // Font row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Font");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Choice* o = textDisplayFont = new Fl_Choice(0,0,0,0);
            textDisplayFont->tooltip("TrueType font for viewport text");
            textDisplayFont->box(FL_FLAT_BOX);
            textDisplayFont->down_box(FL_FLAT_BOX);
            textDisplayFont->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            textDisplayFont->selection_color(FL_INACTIVE_COLOR);
            textDisplayFont->labelsize(12);
            textDisplayFont->labelcolor((Fl_Color)31);
            textDisplayFont->textsize(12);
            textDisplayFont->textcolor(31);
            textDisplayFont->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 25);
        }

        // Size, Color, Opacity row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Size");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = textDisplayFontSize = new Fl_Value_Input(0,0,0,0);
            textDisplayFontSize->tooltip("Font size in points (8-48)");
            textDisplayFontSize->box(FL_FLAT_BOX);
            textDisplayFontSize->labelsize(12);
            textDisplayFontSize->labelcolor((Fl_Color)31);
            textDisplayFontSize->minimum(8);
            textDisplayFontSize->maximum(48);
            textDisplayFontSize->step(1);
            textDisplayFontSize->value(15);
            textDisplayFontSize->textsize(12);
            textDisplayFontSize->textcolor(31);
            textDisplayFontSize->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 60);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Color");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 50);
          }
          { Fl_Value_Input* o = textDisplayColor = new Fl_Value_Input(0,0,0,0);
            textDisplayColor->tooltip("Text brightness (0-1)");
            textDisplayColor->box(FL_FLAT_BOX);
            textDisplayColor->labelsize(12);
            textDisplayColor->labelcolor((Fl_Color)31);
            textDisplayColor->minimum(0.0);
            textDisplayColor->maximum(1.0);
            textDisplayColor->step(0.01);
            textDisplayColor->value(1);
            textDisplayColor->textsize(12);
            textDisplayColor->textcolor(31);
            textDisplayColor->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 60);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Opacity");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 60);
          }
          { Fl_Value_Input* o = textDisplayOpacity = new Fl_Value_Input(0,0,0,0);
            textDisplayOpacity->tooltip("Text opacity (0-1)");
            textDisplayOpacity->box(FL_FLAT_BOX);
            textDisplayOpacity->labelsize(12);
            textDisplayOpacity->labelcolor((Fl_Color)31);
            textDisplayOpacity->minimum(0.0);
            textDisplayOpacity->maximum(1.0);
            textDisplayOpacity->step(0.01);
            textDisplayOpacity->value(1);
            textDisplayOpacity->textsize(12);
            textDisplayOpacity->textcolor(31);
            textDisplayOpacity->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 60);
          }
          row->end();
          col->fixed(row, 25);
        }

        // Drop Shadow checkbox
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(6);
          { textDisplayShadow = new Fl_Check_Button(0,0,0,0, "Drop Shadow");
            textDisplayShadow->tooltip("Enable drop shadow behind viewport text");
            textDisplayShadow->down_box(FL_FLAT_BOX);
            textDisplayShadow->color(FL_INACTIVE_COLOR);
            textDisplayShadow->selection_color((Fl_Color)31);
            textDisplayShadow->labelcolor((Fl_Color)31);
            textDisplayShadow->labelsize(12);
            textDisplayShadow->value(1);
            textDisplayShadow->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 22);
        }

        // Hinting and Filter row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Hinting");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Choice* o = textDisplayHinting = new Fl_Choice(0,0,0,0);
            textDisplayHinting->tooltip("Light (smooth diagonals), Normal (sharp stems), Auto (FreeType auto-hinter)");
            textDisplayHinting->box(FL_FLAT_BOX);
            textDisplayHinting->down_box(FL_FLAT_BOX);
            textDisplayHinting->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            textDisplayHinting->labelsize(12);
            textDisplayHinting->labelcolor((Fl_Color)31);
            textDisplayHinting->textsize(12);
            textDisplayHinting->textcolor(31);
            textDisplayHinting->add("Light");
            textDisplayHinting->add("Normal");
            textDisplayHinting->add("Auto");
            textDisplayHinting->value(0);
            textDisplayHinting->callback((Fl_Callback*)PreferencesCB);
            row->fixed(o, 120);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Filter");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 50);
          }
          { Fl_Choice* o = textDisplayFilter = new Fl_Choice(0,0,0,0);
            textDisplayFilter->tooltip("Nearest (pixel-perfect), Linear (smooth)");
            textDisplayFilter->box(FL_FLAT_BOX);
            textDisplayFilter->down_box(FL_FLAT_BOX);
            textDisplayFilter->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            textDisplayFilter->labelsize(12);
            textDisplayFilter->labelcolor((Fl_Color)31);
            textDisplayFilter->textsize(12);
            textDisplayFilter->textcolor(31);
            textDisplayFilter->add("Nearest");
            textDisplayFilter->add("Linear");
            textDisplayFilter->value(0);
            textDisplayFilter->callback((Fl_Callback*)PreferencesCB);
            row->fixed(o, 120);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        // Gamma row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Gamma");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = textDisplayGamma = new Fl_Value_Input(0,0,0,0);
            textDisplayGamma->tooltip("Gamma correction for text edges (lower = bolder, 0.3-1.0)");
            textDisplayGamma->box(FL_FLAT_BOX);
            textDisplayGamma->labelsize(12);
            textDisplayGamma->labelcolor((Fl_Color)31);
            textDisplayGamma->minimum(0.3);
            textDisplayGamma->maximum(1.0);
            textDisplayGamma->step(0.05);
            textDisplayGamma->value(1.0);
            textDisplayGamma->textsize(12);
            textDisplayGamma->textcolor(31);
            textDisplayGamma->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 60);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        col->end();
      }

      panels[1]->end();
    } // panels[1] Text

    // === Panel 2: Engine ===
    { panels[2] = new Fl_Group(130, 5, 465, 450);
      panels[2]->box(FL_FLAT_BOX);
      panels[2]->color(fl_rgb_color(38,38,38));
      panels[2]->hide();

      { Fl_Flex* col = new Fl_Flex(130, 5, 465, 450, Fl_Flex::COLUMN);
        col->margin(10, 10, 10, 10);
        col->gap(6);

        // -- Section: Memory --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Memory");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 18);
        }

        // % of RAM
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "% of RAM");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Slider* o = percentageOfRam = new Fl_Value_Slider(0,0,0,0);
            percentageOfRam->tooltip("The engine will load frames until this amount of system RAM is used up. Recommended values are between 80 and 95.");
            percentageOfRam->type(3);
            percentageOfRam->box(FL_FLAT_BOX);
            percentageOfRam->color(FL_INACTIVE_COLOR);
            percentageOfRam->selection_color(FL_INACTIVE_COLOR);
            percentageOfRam->labelcolor((Fl_Color)31);
            percentageOfRam->minimum(10);
            percentageOfRam->maximum(95);
            percentageOfRam->step(0.5);
            percentageOfRam->value(85);
            percentageOfRam->textsize(14);
            percentageOfRam->textcolor(31);
            percentageOfRam->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            o->selection_color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          }
          row->end();
          col->fixed(row, 25);
        }

        // Max frames in queue
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Max Queue");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { maximumFramesInQueue = new Fl_Value_Input(0,0,0,0);
            maximumFramesInQueue->tooltip("If some frames show up black, try setting this to 1.");
            maximumFramesInQueue->box(FL_FLAT_BOX);
            maximumFramesInQueue->color(FL_INACTIVE_COLOR);
            maximumFramesInQueue->labelsize(12);
            maximumFramesInQueue->labelcolor((Fl_Color)31);
            maximumFramesInQueue->maximum(99999);
            maximumFramesInQueue->step(1);
            maximumFramesInQueue->value(5);
            maximumFramesInQueue->textsize(12);
            maximumFramesInQueue->textcolor(31);
            maximumFramesInQueue->callback((Fl_Callback*)PreferencesCB);
            maximumFramesInQueue->when(3);
            maximumFramesInQueue->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(maximumFramesInQueue, 50);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        // -- Section: Options --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Options");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }

        // Force GFL Loading Engine
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { forceGFLLoading = new Fl_Check_Button(0,0,0,0, "Force GFL Loading Engine");
            forceGFLLoading->down_box(FL_FLAT_BOX);
            forceGFLLoading->color(FL_INACTIVE_COLOR);
            forceGFLLoading->selection_color((Fl_Color)31);
            forceGFLLoading->labelcolor((Fl_Color)31);
            forceGFLLoading->labelsize(12);
            forceGFLLoading->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Don't use Inactive Memory
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { dontUseInactiveMemory = new Fl_Check_Button(0,0,0,0, "Don't use Inactive Memory (OS X only)");
            dontUseInactiveMemory->down_box(FL_FLAT_BOX);
            dontUseInactiveMemory->color(FL_INACTIVE_COLOR);
            dontUseInactiveMemory->selection_color((Fl_Color)31);
            dontUseInactiveMemory->labelcolor((Fl_Color)31);
            dontUseInactiveMemory->labelsize(12);
            dontUseInactiveMemory->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Force Single Buffered FXs
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { forceSingleBufferedFXs = new Fl_Check_Button(0,0,0,0, "Force Single Buffered FXs");
            forceSingleBufferedFXs->down_box(FL_FLAT_BOX);
            forceSingleBufferedFXs->color(FL_INACTIVE_COLOR);
            forceSingleBufferedFXs->selection_color((Fl_Color)31);
            forceSingleBufferedFXs->labelcolor((Fl_Color)31);
            forceSingleBufferedFXs->labelsize(12);
            forceSingleBufferedFXs->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Continue loading on error
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { continueLoadingOnError = new Fl_Check_Button(0,0,0,0, "Continue loading sequence after load error");
            continueLoadingOnError->down_box(FL_FLAT_BOX);
            continueLoadingOnError->value(1);
            continueLoadingOnError->color(FL_INACTIVE_COLOR);
            continueLoadingOnError->selection_color((Fl_Color)31);
            continueLoadingOnError->labelcolor((Fl_Color)31);
            continueLoadingOnError->labelsize(12);
            continueLoadingOnError->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // VSync
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { vsync = new Fl_Check_Button(0,0,0,0, "Enable Vertical Redraw Sync (vsync)");
            vsync->down_box(FL_FLAT_BOX);
            vsync->color(FL_INACTIVE_COLOR);
            vsync->selection_color((Fl_Color)31);
            vsync->labelcolor((Fl_Color)31);
            vsync->labelsize(12);
            vsync->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Balance Reads
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { balanceReads = new Fl_Check_Button(0,0,0,0, "Balance Reads");
            balanceReads->tooltip("Makes all tracks load at the same rate.");
            balanceReads->down_box(FL_FLAT_BOX);
            balanceReads->value(1);
            balanceReads->color(FL_INACTIVE_COLOR);
            balanceReads->selection_color((Fl_Color)31);
            balanceReads->labelcolor((Fl_Color)31);
            balanceReads->labelsize(12);
            balanceReads->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Processor Priority
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { processorPriority = new Fl_Check_Button(0,0,0,0, "Try hard to maintain FPS (More CPU use)");
            processorPriority->down_box(FL_FLAT_BOX);
            processorPriority->color(FL_INACTIVE_COLOR);
            processorPriority->selection_color((Fl_Color)31);
            processorPriority->labelcolor((Fl_Color)31);
            processorPriority->labelsize(12);
            processorPriority->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Draw Proxies at full Resolution (hidden)
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { Fl_Check_Button* o = frawProxiesAtFullResolution = new Fl_Check_Button(0,0,0,0, "Draw Proxies at full Resolution");
            frawProxiesAtFullResolution->down_box(FL_FLAT_BOX);
            frawProxiesAtFullResolution->color(FL_INACTIVE_COLOR);
            frawProxiesAtFullResolution->selection_color((Fl_Color)31);
            frawProxiesAtFullResolution->labelcolor((Fl_Color)31);
            frawProxiesAtFullResolution->labelsize(12);
            frawProxiesAtFullResolution->callback((Fl_Callback*)PreferencesCB);
            frawProxiesAtFullResolution->hide();
            o->color(fl_rgb_color(32,32,32));
          }
          row->end();
          col->fixed(row, 20);
        }

        // Histogram Subsampling
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Histogram");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Slider* o = histogramQuality = new Fl_Value_Slider(0,0,0,0);
            histogramQuality->type(1);
            histogramQuality->box(FL_FLAT_BOX);
            histogramQuality->color(FL_INACTIVE_COLOR);
            histogramQuality->selection_color(FL_INACTIVE_COLOR);
            histogramQuality->labelcolor((Fl_Color)31);
            histogramQuality->minimum(1);
            histogramQuality->maximum(64);
            histogramQuality->step(1);
            histogramQuality->value(16);
            histogramQuality->textsize(14);
            histogramQuality->textcolor(31);
            histogramQuality->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            o->selection_color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          }
          row->end();
          col->fixed(row, 25);
        }

        col->end();
      }

      panels[2]->end();
    } // panels[2] Engine

    // === Panel 3: Formats ===
    { panels[3] = new Fl_Group(130, 5, 465, 450);
      panels[3]->box(FL_FLAT_BOX);
      panels[3]->color(fl_rgb_color(38,38,38));
      panels[3]->hide();
      formatsTab = panels[3];

      { Fl_Flex* col = new Fl_Flex(130, 5, 465, 450, Fl_Flex::COLUMN);
        col->margin(10, 10, 10, 10);
        col->gap(6);

        // -- Section: OpenEXR --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "OpenEXR");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 18);
        }

        // Ignore Display Window
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { exrIgnoreDisplayWindow = new Fl_Check_Button(0,0,0,0, "Ignore Display Window");
            exrIgnoreDisplayWindow->tooltip("Use only the Data Window in the openEXR file to determine image properties");
            exrIgnoreDisplayWindow->down_box(FL_FLAT_BOX);
            exrIgnoreDisplayWindow->color(FL_INACTIVE_COLOR);
            exrIgnoreDisplayWindow->selection_color((Fl_Color)31);
            exrIgnoreDisplayWindow->labelcolor((Fl_Color)31);
            exrIgnoreDisplayWindow->labelsize(12);
            exrIgnoreDisplayWindow->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Ignore Header's Aspect Ratio
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { exrIgnoreHeadersAspectRatio = new Fl_Check_Button(0,0,0,0, "Ignore Header's Aspect Ratio");
            exrIgnoreHeadersAspectRatio->tooltip("Use only the Data Window in the openEXR file to determine image properties");
            exrIgnoreHeadersAspectRatio->down_box(FL_FLAT_BOX);
            exrIgnoreHeadersAspectRatio->color(FL_INACTIVE_COLOR);
            exrIgnoreHeadersAspectRatio->selection_color((Fl_Color)31);
            exrIgnoreHeadersAspectRatio->labelcolor((Fl_Color)31);
            exrIgnoreHeadersAspectRatio->labelsize(12);
            exrIgnoreHeadersAspectRatio->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // -- Sub-section: Float > Integer transformation --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Float > Integer Transformation");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }

        // Enable Exposure Transform on Load
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { exrEnableExposureTransformOnLoad = new Fl_Check_Button(0,0,0,0, "Enable Exposure Transform on Load");
            exrEnableExposureTransformOnLoad->tooltip("Perform the reference Float to Integer color transformation when loading to an Integer buffer (8bpc, 16bpc, 4bpc, S3TC)");
            exrEnableExposureTransformOnLoad->down_box(FL_FLAT_BOX);
            exrEnableExposureTransformOnLoad->color(FL_INACTIVE_COLOR);
            exrEnableExposureTransformOnLoad->selection_color((Fl_Color)31);
            exrEnableExposureTransformOnLoad->labelcolor((Fl_Color)31);
            exrEnableExposureTransformOnLoad->labelsize(12);
            exrEnableExposureTransformOnLoad->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Exposure, Defog, Gamma row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Exposure");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = exrExposure = new Fl_Value_Input(0,0,0,0);
            exrExposure->box(FL_FLAT_BOX);
            exrExposure->color(FL_INACTIVE_COLOR);
            exrExposure->selection_color(FL_FOREGROUND_COLOR);
            exrExposure->labelsize(12);
            exrExposure->labelcolor((Fl_Color)31);
            exrExposure->minimum(-10);
            exrExposure->maximum(10);
            exrExposure->step(0.01);
            exrExposure->textsize(12);
            exrExposure->textcolor(31);
            exrExposure->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 50);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Defog");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 50);
          }
          { Fl_Value_Input* o = exrDefog = new Fl_Value_Input(0,0,0,0);
            exrDefog->box(FL_FLAT_BOX);
            exrDefog->color(FL_INACTIVE_COLOR);
            exrDefog->selection_color(FL_FOREGROUND_COLOR);
            exrDefog->labelsize(12);
            exrDefog->labelcolor((Fl_Color)31);
            exrDefog->step(0.0001);
            exrDefog->textsize(12);
            exrDefog->textcolor(31);
            exrDefog->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 60);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Gamma");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 55);
          }
          { Fl_Value_Input* o = exrGamma = new Fl_Value_Input(0,0,0,0);
            exrGamma->box(FL_FLAT_BOX);
            exrGamma->color(FL_INACTIVE_COLOR);
            exrGamma->selection_color(FL_FOREGROUND_COLOR);
            exrGamma->labelsize(12);
            exrGamma->labelcolor((Fl_Color)31);
            exrGamma->minimum(0.01);
            exrGamma->maximum(10);
            exrGamma->step(0.01);
            exrGamma->value(2.2);
            exrGamma->textsize(12);
            exrGamma->textcolor(31);
            exrGamma->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 50);
          }
          row->end();
          col->fixed(row, 25);
        }

        // Knee Low, Knee High row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Knee Low");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = exrKneeLow = new Fl_Value_Input(0,0,0,0);
            exrKneeLow->box(FL_FLAT_BOX);
            exrKneeLow->color(FL_INACTIVE_COLOR);
            exrKneeLow->selection_color(FL_FOREGROUND_COLOR);
            exrKneeLow->labelsize(12);
            exrKneeLow->labelcolor((Fl_Color)31);
            exrKneeLow->minimum(-3);
            exrKneeLow->maximum(3);
            exrKneeLow->step(0.01);
            exrKneeLow->textsize(12);
            exrKneeLow->textcolor(31);
            exrKneeLow->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 50);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Knee High");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 70);
          }
          { Fl_Value_Input* o = exrKneeHigh = new Fl_Value_Input(0,0,0,0);
            exrKneeHigh->box(FL_FLAT_BOX);
            exrKneeHigh->color(FL_INACTIVE_COLOR);
            exrKneeHigh->selection_color(FL_FOREGROUND_COLOR);
            exrKneeHigh->labelsize(12);
            exrKneeHigh->labelcolor((Fl_Color)31);
            exrKneeHigh->minimum(3.5);
            exrKneeHigh->maximum(7.5);
            exrKneeHigh->step(0.01);
            exrKneeHigh->value(5);
            exrKneeHigh->textsize(12);
            exrKneeHigh->textcolor(31);
            exrKneeHigh->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 50);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        // Defaults button row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          { Fl_Button_gfc* o = new Fl_Button_gfc(0,0,0,0, "Defaults");
            o->box(FL_FLAT_BOX);
            o->color(FL_INACTIVE_COLOR);
            o->selection_color(FL_BACKGROUND_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(12);
            o->labelcolor((Fl_Color)31);
            o->callback((Fl_Callback*)PreferencesCB, (void*)(EXRPREFSDEFAULTSBUTTON_ID));
            o->align(FL_ALIGN_CENTER);
            o->when(FL_WHEN_RELEASE);
            row->fixed(o, 70);
          }
          row->end();
          col->fixed(row, 25);
        }

        col->end();
      }

      panels[3]->end();
    } // panels[3] Formats

    // === Panel 4: Remote ===
    { panels[4] = new Fl_Group(130, 5, 465, 450);
      panels[4]->box(FL_FLAT_BOX);
      panels[4]->color(fl_rgb_color(38,38,38));
      panels[4]->hide();
      remoteSessionTab = panels[4];

      { Fl_Flex* col = new Fl_Flex(130, 5, 465, 450, Fl_Flex::COLUMN);
        col->margin(10, 10, 10, 10);
        col->gap(6);

        // -- Section: Chat Options --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Chat Options");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 18);
        }

        // Font Size, Text Background, Opacity row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Font Size");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = fontSize = new Fl_Value_Input(0,0,0,0);
            fontSize->box(FL_FLAT_BOX);
            fontSize->color(FL_INACTIVE_COLOR);
            fontSize->labelsize(12);
            fontSize->labelcolor((Fl_Color)31);
            fontSize->minimum(8);
            fontSize->maximum(24);
            fontSize->step(1);
            fontSize->value(16);
            fontSize->textsize(12);
            fontSize->textcolor(31);
            fontSize->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 35);
          }
          { textBG = new Fl_Check_Button(0,0,0,0, "Text Background");
            textBG->tooltip("Show a gray backdrop behind the chat display to improve readability");
            textBG->down_box(FL_FLAT_BOX);
            textBG->value(1);
            textBG->color(FL_INACTIVE_COLOR);
            textBG->selection_color((Fl_Color)31);
            textBG->labelsize(12);
            textBG->labelcolor((Fl_Color)31);
            textBG->callback((Fl_Callback*)PreferencesCB);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Opacity");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 55);
          }
          { Fl_Value_Input* o = opacity = new Fl_Value_Input(0,0,0,0);
            opacity->tooltip("Set the opacity of the chat display over the viewport");
            opacity->box(FL_FLAT_BOX);
            opacity->color(FL_INACTIVE_COLOR);
            opacity->labelsize(12);
            opacity->labelcolor((Fl_Color)31);
            opacity->minimum(0.1);
            opacity->step(0.01);
            opacity->value(0.75);
            opacity->textsize(12);
            opacity->textcolor(31);
            opacity->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 45);
          }
          row->end();
          col->fixed(row, 25);
        }

        // History Lines, Auto Fade, Delay row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "History");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = chatLines = new Fl_Value_Input(0,0,0,0);
            chatLines->tooltip("Set how many lines of chat history to show");
            chatLines->box(FL_FLAT_BOX);
            chatLines->color(FL_INACTIVE_COLOR);
            chatLines->labelsize(12);
            chatLines->labelcolor((Fl_Color)31);
            chatLines->minimum(1);
            chatLines->maximum(30);
            chatLines->step(1);
            chatLines->value(8);
            chatLines->textsize(12);
            chatLines->textcolor(31);
            chatLines->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 35);
          }
          { autoFade = new Fl_Check_Button(0,0,0,0, "Auto Fade");
            autoFade->tooltip("When not in chat mode, the chat display will fade away automatically after a short delay if this is enabled.");
            autoFade->down_box(FL_FLAT_BOX);
            autoFade->value(1);
            autoFade->color(FL_INACTIVE_COLOR);
            autoFade->selection_color((Fl_Color)31);
            autoFade->labelsize(12);
            autoFade->labelcolor((Fl_Color)31);
            autoFade->callback((Fl_Callback*)PreferencesCB);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Delay");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 45);
          }
          { Fl_Value_Input* o = fadeDelay = new Fl_Value_Input(0,0,0,0);
            fadeDelay->tooltip("How long before the chat display fades away when not in chat mode");
            fadeDelay->box(FL_FLAT_BOX);
            fadeDelay->color(FL_INACTIVE_COLOR);
            fadeDelay->labelsize(12);
            fadeDelay->labelcolor((Fl_Color)31);
            fadeDelay->minimum(1);
            fadeDelay->maximum(999999);
            fadeDelay->step(1);
            fadeDelay->value(8);
            fadeDelay->textsize(12);
            fadeDelay->textcolor(31);
            fadeDelay->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 35);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        // -- Section: Remote Pointers Options --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Remote Pointers");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }

        // Font Size, Pointer Size, Fade, Delay row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Font Size");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = remotePointerFontSize = new Fl_Value_Input(0,0,0,0);
            remotePointerFontSize->box(FL_FLAT_BOX);
            remotePointerFontSize->color(FL_INACTIVE_COLOR);
            remotePointerFontSize->labelsize(12);
            remotePointerFontSize->labelcolor((Fl_Color)31);
            remotePointerFontSize->minimum(8);
            remotePointerFontSize->maximum(24);
            remotePointerFontSize->step(1);
            remotePointerFontSize->value(14);
            remotePointerFontSize->textsize(12);
            remotePointerFontSize->textcolor(31);
            remotePointerFontSize->callback((Fl_Callback*)PreferencesCB);
            remotePointerFontSize->when(FL_WHEN_RELEASE);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 35);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Ptr Size");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 55);
          }
          { Fl_Value_Input* o = remotePointerSize = new Fl_Value_Input(0,0,0,0);
            remotePointerSize->tooltip("Set how many lines of chat history to show");
            remotePointerSize->box(FL_FLAT_BOX);
            remotePointerSize->color(FL_INACTIVE_COLOR);
            remotePointerSize->labelsize(12);
            remotePointerSize->labelcolor((Fl_Color)31);
            remotePointerSize->minimum(1);
            remotePointerSize->maximum(30);
            remotePointerSize->step(1);
            remotePointerSize->value(5);
            remotePointerSize->textsize(12);
            remotePointerSize->textcolor(31);
            remotePointerSize->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 35);
          }
          { remotePointerFade = new Fl_Check_Button(0,0,0,0, "Fade");
            remotePointerFade->tooltip("When not in chat mode, the chat display will fade away automatically after a short delay if this is enabled.");
            remotePointerFade->down_box(FL_FLAT_BOX);
            remotePointerFade->value(1);
            remotePointerFade->color(FL_INACTIVE_COLOR);
            remotePointerFade->selection_color((Fl_Color)31);
            remotePointerFade->labelsize(12);
            remotePointerFade->labelcolor((Fl_Color)31);
            remotePointerFade->callback((Fl_Callback*)PreferencesCB);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Delay");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 45);
          }
          { Fl_Value_Input* o = remotePointerFadeDelay = new Fl_Value_Input(0,0,0,0);
            remotePointerFadeDelay->tooltip("How long before the chat display fades away when not in chat mode");
            remotePointerFadeDelay->box(FL_FLAT_BOX);
            remotePointerFadeDelay->color(FL_INACTIVE_COLOR);
            remotePointerFadeDelay->labelsize(12);
            remotePointerFadeDelay->labelcolor((Fl_Color)31);
            remotePointerFadeDelay->minimum(1);
            remotePointerFadeDelay->maximum(999999);
            remotePointerFadeDelay->step(1);
            remotePointerFadeDelay->value(10);
            remotePointerFadeDelay->textsize(12);
            remotePointerFadeDelay->textcolor(31);
            remotePointerFadeDelay->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 35);
          }
          row->end();
          col->fixed(row, 25);
        }

        // Trail, Trail Length, Color row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { remotePointerTrail = new Fl_Check_Button(0,0,0,0, "Trail");
            remotePointerTrail->tooltip("When not in chat mode, the chat display will fade away automatically after a short delay if this is enabled.");
            remotePointerTrail->down_box(FL_FLAT_BOX);
            remotePointerTrail->value(1);
            remotePointerTrail->color(FL_INACTIVE_COLOR);
            remotePointerTrail->selection_color((Fl_Color)31);
            remotePointerTrail->labelsize(12);
            remotePointerTrail->labelcolor((Fl_Color)31);
            remotePointerTrail->callback((Fl_Callback*)PreferencesCB);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Length");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 50);
          }
          { Fl_Value_Input* o = remotePointerTrailLenght = new Fl_Value_Input(0,0,0,0);
            remotePointerTrailLenght->tooltip("Set the opacity of the chat display over the viewport");
            remotePointerTrailLenght->box(FL_FLAT_BOX);
            remotePointerTrailLenght->color(FL_INACTIVE_COLOR);
            remotePointerTrailLenght->labelsize(12);
            remotePointerTrailLenght->labelcolor((Fl_Color)31);
            remotePointerTrailLenght->minimum(1);
            remotePointerTrailLenght->maximum(1000);
            remotePointerTrailLenght->step(1);
            remotePointerTrailLenght->value(80);
            remotePointerTrailLenght->textsize(12);
            remotePointerTrailLenght->textcolor(31);
            remotePointerTrailLenght->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 45);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Color");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 45);
          }
          { Fl_Spinner_gfc* o = remotePointerColor = new Fl_Spinner_gfc(0,0,0,0);
            remotePointerColor->box(FL_FLAT_BOX);
            remotePointerColor->color(FL_INACTIVE_COLOR);
            remotePointerColor->selection_color(FL_FOREGROUND_COLOR);
            remotePointerColor->labeltype(FL_NORMAL_LABEL);
            remotePointerColor->labelfont(0);
            remotePointerColor->labelsize(12);
            remotePointerColor->labelcolor((Fl_Color)31);
            remotePointerColor->minimum(0);
            remotePointerColor->maximum(7);
            remotePointerColor->value(7);
            remotePointerColor->textsize(12);
            remotePointerColor->callback((Fl_Callback*)PreferencesCB);
            remotePointerColor->when(FL_WHEN_CHANGED);
            o->textcolor((Fl_Color)31);
            row->fixed(o, 35);
          }
          { remotePointerColorSample = new Fl_Box(0,0,0,0);
            remotePointerColorSample->box(FL_FLAT_BOX);
            remotePointerColorSample->color(FL_BACKGROUND2_COLOR);
            row->fixed(remotePointerColorSample, 18);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        // -- Section: Remote Loading Options --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Remote Loading Options");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }

        // Send Remote Loading Requests
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { remoteSendLoadRequests = new Fl_Check_Button(0,0,0,0, "Send Remote Loading Requests");
            remoteSendLoadRequests->tooltip("When you load a playlist item locally, a request to load that item will be sent to all other participants in the session");
            remoteSendLoadRequests->down_box(FL_FLAT_BOX);
            remoteSendLoadRequests->value(1);
            remoteSendLoadRequests->color(FL_INACTIVE_COLOR);
            remoteSendLoadRequests->selection_color((Fl_Color)31);
            remoteSendLoadRequests->labelsize(12);
            remoteSendLoadRequests->labelcolor((Fl_Color)31);
            remoteSendLoadRequests->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Auto accept remote loading requests
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { remoteAutoAcceptLoadRequests = new Fl_Check_Button(0,0,0,0, "Auto accept remote loading requests");
            remoteAutoAcceptLoadRequests->tooltip("Choose if a request to load a sequence from another participant is accepted automaticaly without confirmation");
            remoteAutoAcceptLoadRequests->down_box(FL_FLAT_BOX);
            remoteAutoAcceptLoadRequests->value(1);
            remoteAutoAcceptLoadRequests->color(FL_INACTIVE_COLOR);
            remoteAutoAcceptLoadRequests->selection_color((Fl_Color)31);
            remoteAutoAcceptLoadRequests->labelsize(12);
            remoteAutoAcceptLoadRequests->labelcolor((Fl_Color)31);
            remoteAutoAcceptLoadRequests->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // -- Section: Update Frequency --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Update Frequency (per second)");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 22);
        }

        // Transformations, FX Parameters, Others row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 25);
          row->gap(8);
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Transforms");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 80);
          }
          { Fl_Value_Input* o = remoteTransformationsFrequency = new Fl_Value_Input(0,0,0,0);
            remoteTransformationsFrequency->box(FL_FLAT_BOX);
            remoteTransformationsFrequency->color(FL_INACTIVE_COLOR);
            remoteTransformationsFrequency->labelsize(12);
            remoteTransformationsFrequency->labelcolor((Fl_Color)31);
            remoteTransformationsFrequency->minimum(1);
            remoteTransformationsFrequency->maximum(3000);
            remoteTransformationsFrequency->step(1);
            remoteTransformationsFrequency->value(60);
            remoteTransformationsFrequency->textsize(12);
            remoteTransformationsFrequency->textcolor(31);
            remoteTransformationsFrequency->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 40);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "FX");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 30);
          }
          { Fl_Value_Input* o = remoteFXFrequency = new Fl_Value_Input(0,0,0,0);
            remoteFXFrequency->box(FL_FLAT_BOX);
            remoteFXFrequency->color(FL_INACTIVE_COLOR);
            remoteFXFrequency->labelsize(12);
            remoteFXFrequency->labelcolor((Fl_Color)31);
            remoteFXFrequency->minimum(1);
            remoteFXFrequency->maximum(3000);
            remoteFXFrequency->step(1);
            remoteFXFrequency->value(60);
            remoteFXFrequency->textsize(12);
            remoteFXFrequency->textcolor(31);
            remoteFXFrequency->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 40);
          }
          { Fl_Box* label = new Fl_Box(0,0,0,0, "Others");
            label->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
            label->labelsize(12);
            label->labelcolor((Fl_Color)31);
            row->fixed(label, 50);
          }
          { Fl_Value_Input* o = remoteOthersFrequency = new Fl_Value_Input(0,0,0,0);
            remoteOthersFrequency->box(FL_FLAT_BOX);
            remoteOthersFrequency->color(FL_INACTIVE_COLOR);
            remoteOthersFrequency->labelsize(12);
            remoteOthersFrequency->labelcolor((Fl_Color)31);
            remoteOthersFrequency->minimum(1);
            remoteOthersFrequency->maximum(3000);
            remoteOthersFrequency->step(1);
            remoteOthersFrequency->value(60);
            remoteOthersFrequency->textsize(12);
            remoteOthersFrequency->textcolor(31);
            remoteOthersFrequency->callback((Fl_Callback*)PreferencesCB);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            row->fixed(o, 40);
          }
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          row->end();
          col->fixed(row, 25);
        }

        col->end();
      }

      panels[4]->end();
    } // panels[4] Remote

    // === Panel 5: Paths ===
    { panels[5] = new Fl_Group(130, 5, 465, 450);
      panels[5]->box(FL_FLAT_BOX);
      panels[5]->color(fl_rgb_color(38,38,38));
      panels[5]->hide();
      pathsTab = panels[5];

      { Fl_Flex* col = new Fl_Flex(130, 5, 465, 450, Fl_Flex::COLUMN);
        col->margin(10, 10, 10, 10);
        col->gap(6);

        // -- Section: Sequence Search Paths --
        { Fl_Box* hdr = new Fl_Box(0,0,0,0, "Sequence Search Paths");
          hdr->labelfont(1);
          hdr->labelcolor((Fl_Color)31);
          hdr->labelsize(12);
          hdr->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
          col->fixed(hdr, 18);
        }

        // Use search paths checkbox
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 20);
          row->gap(6);
          { useSearchPaths = new Fl_Check_Button(0,0,0,0, "Use search paths");
            useSearchPaths->tooltip("When a file loaded from a saved or remote session is not found, Jefecheck will try to resolve the filename in any of the search paths. This allows you to share sessions across computers with different filesystem structures.");
            useSearchPaths->down_box(FL_FLAT_BOX);
            useSearchPaths->color(FL_INACTIVE_COLOR);
            useSearchPaths->selection_color((Fl_Color)31);
            useSearchPaths->labelcolor((Fl_Color)31);
            useSearchPaths->labelsize(12);
            useSearchPaths->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 20);
        }

        // Browse button + Include Subfolders checkbox row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(8);
          { searchPathBrowse = new Fl_Button_gfc(0,0,0,0, "Browse");
            searchPathBrowse->box(FL_FLAT_BOX);
            searchPathBrowse->down_box(FL_FLAT_BOX);
            searchPathBrowse->color(FL_INACTIVE_COLOR);
            searchPathBrowse->selection_color(FL_BACKGROUND_COLOR);
            searchPathBrowse->labeltype(FL_NORMAL_LABEL);
            searchPathBrowse->labelfont(0);
            searchPathBrowse->labelsize(12);
            searchPathBrowse->labelcolor((Fl_Color)31);
            searchPathBrowse->callback((Fl_Callback*)PreferencesCB, (void*)(PATHSEARCHBROWSEBUTTON_ID));
            searchPathBrowse->align(FL_ALIGN_CENTER);
            searchPathBrowse->when(FL_WHEN_RELEASE);
            row->fixed(searchPathBrowse, 64);
          }
          { searchPathsRecursive = new Fl_Check_Button(0,0,0,0, "Include Subfolders");
            searchPathsRecursive->down_box(FL_FLAT_BOX);
            searchPathsRecursive->color(FL_INACTIVE_COLOR);
            searchPathsRecursive->selection_color((Fl_Color)31);
            searchPathsRecursive->labelsize(12);
            searchPathsRecursive->labelcolor((Fl_Color)31);
            searchPathsRecursive->callback((Fl_Callback*)PreferencesCB);
          }
          row->end();
          col->fixed(row, 22);
        }

        // Search paths browser (stretches to fill available space)
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 0);
          row->gap(6);
          { Fl_Browser* o = searchPaths = new Fl_Browser(0,0,0,0);
            searchPaths->type(3);
            searchPaths->box(FL_FLAT_BOX);
            searchPaths->color(FL_INACTIVE_COLOR);
            searchPaths->selection_color((Fl_Color)31);
            searchPaths->textcolor(31);
            searchPaths->callback((Fl_Callback*)PreferencesCB, (void*)(PATHSEARCHBROWSER_ID));
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          }
          row->end();
          // Don't fix this row - let it stretch to fill remaining space
        }

        // Delete button row
        { Fl_Flex* row = new Fl_Flex(0, 0, 0, 22);
          row->gap(8);
          { Fl_Box* spacer = new Fl_Box(0,0,0,0); (void)spacer; }
          { searchPathDelete = new Fl_Button_gfc(0,0,0,0, "@9+");
            searchPathDelete->box(FL_FLAT_BOX);
            searchPathDelete->down_box(FL_FLAT_BOX);
            searchPathDelete->color(FL_INACTIVE_COLOR);
            searchPathDelete->selection_color(FL_BACKGROUND_COLOR);
            searchPathDelete->labeltype(FL_NORMAL_LABEL);
            searchPathDelete->labelfont(0);
            searchPathDelete->labelsize(10);
            searchPathDelete->labelcolor((Fl_Color)31);
            searchPathDelete->callback((Fl_Callback*)PreferencesCB, (void*)(PATHSEARCHDELETEBUTTON_ID));
            searchPathDelete->align(FL_ALIGN_CENTER);
            searchPathDelete->when(FL_WHEN_RELEASE);
            row->fixed(searchPathDelete, 39);
          }
          row->end();
          col->fixed(row, 22);
        }

        col->end();
      }

      panels[5]->end();
    } // panels[5] Paths

    // License tab removed for open-source release

    { Fl_Button_gfc* o = new Fl_Button_gfc(460, 460, 130, 35, "Save and Close");
      o->tooltip("Closes this window without saving preferences for next session");
      o->box(FL_FLAT_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color(FL_INACTIVE_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor((Fl_Color)31);
      o->callback((Fl_Callback*)PreferencesCB, (void*)(PREFERENCESDONE_ID));
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    } // Fl_Button_gfc* o
    preferencesWindow->set_non_modal();
    preferencesWindow->size_range(600, 500, 600, 500);
    preferencesWindow->end();
  } // Fl_Double_Window* preferencesWindow
  return preferencesWindow;
}

void PreferencesWindow::showPanel(int index) {
  for (int i = 0; i < 6; i++) {
    if (i == index) panels[i]->show();
    else panels[i]->hide();
  }
}
