// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "remoteWindow.h"
#include "UICallbacks.h"
#include "UIConstants.h"
#include "Fl_Button_gfc.h"
#include "Fl_Spinner_gfc.h"

Fl_Double_Window* RemoteWindow::make_window() {
  { remoteWindow = new Fl_Double_Window(472, 500, "JefeCheck - Remote Session Manager");
    remoteWindow->user_data((void*)(this));
    { Fl_Box* o = bg = new Fl_Box(0, -19, 490, 859);
      bg->box(FL_FLAT_BOX);
      bg->color((Fl_Color)64);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_Box* bg
    { Fl_Text_Display* o = log = new Fl_Text_Display(10, 369, 460, 121, "Connection Log");
      log->box(FL_FLAT_BOX);
      log->color(FL_INACTIVE_COLOR);
      log->selection_color(FL_FOREGROUND_COLOR);
      log->labelfont(1);
      log->labelcolor((Fl_Color)31);
      log->textcolor(31);
      Fl_Group::current()->resizable(log);
      o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
    } // Fl_Text_Display* log
    { Fl_Output* o = status = new Fl_Output(54, 318, 411, 22, "Status");
      status->box(FL_FLAT_BOX);
      status->color(FL_INACTIVE_COLOR);
      status->labelcolor((Fl_Color)31);
      status->textcolor(31);
      o->value("Offline");
      o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
    } // Fl_Output* status
    { Fl_Group* o = new Fl_Group(-20, -1, 490, 311);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      { Fl_Group* o = new Fl_Group(4, 10, 458, 87, "Connect to Server");
        o->box(FL_BORDER_FRAME);
        o->color((Fl_Color)31);
        o->labelfont(1);
        o->labelsize(15);
        o->labelcolor((Fl_Color)31);
        o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
        { Fl_Input* o = ip = new Fl_Input(29, 36, 115, 20, "IP");
          ip->tooltip("Set the IP address or DNS  name of the Session Server you whish to connect to");
          ip->box(FL_FLAT_BOX);
          ip->color(FL_INACTIVE_COLOR);
          ip->labelsize(10);
          ip->labelcolor((Fl_Color)31);
          ip->textsize(10);
          ip->textcolor(31);
          ip->when(FL_WHEN_CHANGED);
          o->value("127.0.0.1");
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* ip
        { Fl_Value_Input* o = port = new Fl_Value_Input(168, 36, 45, 21, "port");
          port->tooltip("Set the port where the Session Server you are trying to connect to is listeni\
ng");
          port->box(FL_FLAT_BOX);
          port->color(FL_INACTIVE_COLOR);
          port->labelsize(10);
          port->labelcolor((Fl_Color)31);
          port->minimum(32000);
          port->maximum(60000);
          port->value(4430);
          port->textsize(10);
          port->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Value_Input* port
        { Fl_Input* o = nickname = new Fl_Input(62, 64, 180, 20, "Nickname");
          nickname->tooltip("Enter a name that will identify you in the Session.");
          nickname->box(FL_FLAT_BOX);
          nickname->color(FL_INACTIVE_COLOR);
          nickname->labelsize(10);
          nickname->labelcolor((Fl_Color)31);
          nickname->textsize(10);
          nickname->textcolor(31);
          o->value("Annonymous");
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* nickname
        { connectButton = new Fl_Button_gfc(372, 67, 80, 20, "Connect");
          connectButton->tooltip("Click to connet to the server!");
          connectButton->box(FL_FLAT_BOX);
          connectButton->color(FL_INACTIVE_COLOR);
          connectButton->selection_color(FL_BACKGROUND_COLOR);
          connectButton->labeltype(FL_NORMAL_LABEL);
          connectButton->labelfont(0);
          connectButton->labelsize(10);
          connectButton->labelcolor(FL_FOREGROUND_COLOR);
          connectButton->callback((Fl_Callback*)remoteCB, (void*)(REMOTE_CONNECT_ID));
          connectButton->align(FL_ALIGN_CENTER);
          connectButton->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* connectButton
        { Fl_Input* o = password = new Fl_Input(319, 34, 135, 20, "password");
          password->tooltip("If the Session Sserver you are trying to connect has a password, enter it her\
e");
          password->type(5);
          password->box(FL_FLAT_BOX);
          password->color(FL_INACTIVE_COLOR);
          password->labelsize(10);
          password->labelcolor((Fl_Color)31);
          password->textsize(10);
          password->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* password
        { Fl_Menu_Button* o = remoteRecent = new Fl_Menu_Button(218, 36, 26, 20);
          remoteRecent->box(FL_FLAT_BOX);
          remoteRecent->color(FL_INACTIVE_COLOR);
          remoteRecent->labelcolor((Fl_Color)31);
          remoteRecent->textcolor(31);
          remoteRecent->callback((Fl_Callback*)remoteCB, (void*)(REMOTE_RECENT_ID));
          remoteRecent->align(FL_ALIGN_TOP);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Menu_Button* remoteRecent
        { remotePointerColorSample = new Fl_Box(315, 67, 15, 19);
          remotePointerColorSample->box(FL_FLAT_BOX);
          remotePointerColorSample->color(FL_BACKGROUND2_COLOR);
          remotePointerColorSample->labelsize(10);
          remotePointerColorSample->labelcolor(FL_BACKGROUND2_COLOR);
          remotePointerColorSample->align(FL_ALIGN_LEFT);
        } // Fl_Box* remotePointerColorSample
        { Fl_Spinner_gfc* o = remotePointerColor = new Fl_Spinner_gfc(285, 67, 29, 18, "Color");
          remotePointerColor->box(FL_NO_BOX);
          remotePointerColor->color(FL_BACKGROUND_COLOR);
          remotePointerColor->selection_color(FL_BACKGROUND_COLOR);
          remotePointerColor->labeltype(FL_NORMAL_LABEL);
          remotePointerColor->labelfont(0);
          remotePointerColor->labelsize(10);
          remotePointerColor->labelcolor(FL_BACKGROUND2_COLOR);
          remotePointerColor->minimum(0);
          remotePointerColor->maximum(7);
          remotePointerColor->value(7);
          remotePointerColor->textsize(10);
          remotePointerColor->callback((Fl_Callback*)remoteCB, (void*)(REMOTE_SELECTCOLOR_ID));
          remotePointerColor->align(FL_ALIGN_LEFT);
          remotePointerColor->when(FL_WHEN_CHANGED);
          o->textcolor((Fl_Color)31);
        } // Fl_Spinner_gfc* remotePointerColor
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(4, 108, 459, 82, "Start Server");
        o->box(FL_BORDER_FRAME);
        o->color((Fl_Color)31);
        o->labelfont(1);
        o->labelsize(15);
        o->labelcolor((Fl_Color)31);
        o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
        { Fl_Input* o = serverName = new Fl_Input(39, 133, 85, 20, "Name");
          serverName->tooltip("Type in the server (this will be the servers nickname in chat and other sessi\
on functions).");
          serverName->box(FL_FLAT_BOX);
          serverName->color(FL_INACTIVE_COLOR);
          serverName->labelsize(10);
          serverName->labelcolor((Fl_Color)31);
          serverName->textsize(10);
          serverName->textcolor(31);
          serverName->when(FL_WHEN_CHANGED);
          o->value("JefeServer1");
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* serverName
        { Fl_Value_Input* o = serverPort = new Fl_Value_Input(154, 133, 45, 21, "port");
          serverPort->tooltip("Set the port to listen for clients on. Anything over 32000 should be ok.");
          serverPort->box(FL_FLAT_BOX);
          serverPort->color(FL_INACTIVE_COLOR);
          serverPort->labelsize(10);
          serverPort->labelcolor((Fl_Color)31);
          serverPort->minimum(32000);
          serverPort->maximum(60000);
          serverPort->value(4430);
          serverPort->textsize(10);
          serverPort->textcolor(31);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Value_Input* serverPort
        { startButton = new Fl_Button_gfc(394, 132, 60, 20, "Start");
          startButton->tooltip("Start the Session Server!");
          startButton->box(FL_FLAT_BOX);
          startButton->color(FL_INACTIVE_COLOR);
          startButton->selection_color(FL_BACKGROUND_COLOR);
          startButton->labeltype(FL_NORMAL_LABEL);
          startButton->labelfont(0);
          startButton->labelsize(10);
          startButton->labelcolor((Fl_Color)31);
          startButton->callback((Fl_Callback*)remoteCB, (void*)(REMOTE_START_ID));
          startButton->align(FL_ALIGN_CENTER);
          startButton->when(FL_WHEN_RELEASE);
        } // Fl_Button_gfc* startButton
        { Fl_Input* o = serverPassword = new Fl_Input(254, 132, 135, 20, "password");
          serverPassword->tooltip("Set a password to restrict access to your session.");
          serverPassword->type(5);
          serverPassword->box(FL_FLAT_BOX);
          serverPassword->color(FL_INACTIVE_COLOR);
          serverPassword->labelsize(10);
          serverPassword->labelcolor((Fl_Color)31);
          serverPassword->textsize(10);
          serverPassword->textcolor(31);
          serverPassword->when(FL_WHEN_CHANGED);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Input* serverPassword
        { Fl_Output* o = serverIP = new Fl_Output(83, 162, 162, 20, "Server IP:Port");
          serverIP->tooltip("This is the IP address:port that your clients should use when connecting to y\
ou.");
          serverIP->box(FL_FLAT_BOX);
          serverIP->color(FL_INACTIVE_COLOR);
          serverIP->labelsize(10);
          serverIP->labelcolor((Fl_Color)31);
          serverIP->textcolor(31);
          o->value("");
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Output* serverIP
        o->end();
      } // Fl_Group* o
      { peersInSessionGroup = new Fl_Group(6, 199, 458, 80);
        peersInSessionGroup->tooltip("Shows the number and nicknames of peers of the session you are connected to.");
        peersInSessionGroup->box(FL_BORDER_FRAME);
        peersInSessionGroup->color((Fl_Color)31);
        peersInSessionGroup->labelfont(1);
        peersInSessionGroup->labelsize(15);
        peersInSessionGroup->labelcolor((Fl_Color)31);
        peersInSessionGroup->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
        { Fl_Browser* o = peersInSession = new Fl_Browser(11, 219, 445, 52, "Peers in Session");
          peersInSession->box(FL_FLAT_BOX);
          peersInSession->color(FL_INACTIVE_COLOR);
          peersInSession->labelfont(1);
          peersInSession->labelsize(15);
          peersInSession->labelcolor((Fl_Color)31);
          peersInSession->textsize(10);
          peersInSession->textcolor(31);
          peersInSession->align(FL_ALIGN_TOP_LEFT);
          o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        } // Fl_Browser* peersInSession
        peersInSessionGroup->end();
      } // Fl_Group* peersInSessionGroup
      { Fl_Button_gfc* o = preferencesButton = new Fl_Button_gfc(305, 290, 160, 20, "Remote Session Preferences...");
        preferencesButton->tooltip("Open Remote Session Preferences");
        preferencesButton->box(FL_FLAT_BOX);
        preferencesButton->color(FL_INACTIVE_COLOR);
        preferencesButton->selection_color(FL_BACKGROUND_COLOR);
        preferencesButton->labeltype(FL_NORMAL_LABEL);
        preferencesButton->labelfont(0);
        preferencesButton->labelsize(10);
        preferencesButton->labelcolor((Fl_Color)31);
        preferencesButton->callback((Fl_Callback*)remoteCB, (void*)(REMOTE_PREFERENCES_ID));
        preferencesButton->align(FL_ALIGN_CENTER);
        preferencesButton->when(FL_WHEN_RELEASE);
        o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
      } // Fl_Button_gfc* preferencesButton
      o->end();
    } // Fl_Group* o
    remoteWindow->set_non_modal();
    remoteWindow->size_range(470, 500, 470, 1500);
    remoteWindow->end();
  } // Fl_Double_Window* remoteWindow
  return remoteWindow;
}
