// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef remoteWindow_h
#define remoteWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Value_Input.H>
#include "Fl_Button_gfc.h"
extern void remoteCB(Fl_Button_gfc*, void*);
#include <FL/Fl_Menu_Button.H>
extern void remoteCB(Fl_Menu_Button*, void*);
#include "Fl_Spinner_gfc.h"
extern void remoteCB(Fl_Spinner_gfc*, void*);
#include <FL/Fl_Browser.H>

class RemoteWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *remoteWindow;
  Fl_Box *bg;
  Fl_Text_Display *log;
  Fl_Output *status;
  Fl_Input *ip;
  Fl_Value_Input *port;
  Fl_Input *nickname;
  Fl_Button_gfc *connectButton;
  Fl_Input *password;
  Fl_Menu_Button *remoteRecent;
  Fl_Box *remotePointerColorSample;
  Fl_Spinner_gfc *remotePointerColor;
  Fl_Input *serverName;
  Fl_Value_Input *serverPort;
  Fl_Button_gfc *startButton;
  Fl_Input *serverPassword;
  Fl_Output *serverIP;
  Fl_Group *peersInSessionGroup;
  Fl_Browser *peersInSession;
  Fl_Button_gfc *preferencesButton;
};
#endif
