// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "renderWindow.h"

Fl_Menu_Item RenderWindow::menu_formatChoice[] = {
 {"jpeg", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"exr", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"tiff", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"tga", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"bmp", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"png", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item RenderWindow::menu_quadrantChoice[] = {
 {"q1", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"q2", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"q3", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"q4", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item RenderWindow::menu_tiffCompression[] = {
 {"none", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"LZW", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item RenderWindow::menu_openEXRDepth[] = {
 {"Half (16bit floating point)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Float (32bit floating point)", 0,  0, 0, 1, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item RenderWindow::menu_openEXRCompression[] = {
 {"none", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"RLE  (Lossless)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"ZIP (per scanline)  (lossless)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"ZIP (16 scanline blocks)  (lossless)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"PIZ (lossless)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"PXR24 (lossy)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"B44 (Fixed Rate) (lossy)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"B44  (lossy)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item RenderWindow::menu_codecChoice[] = {
 {"msmpeg4", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"mpeg4", 0,  0, 0, 1, FL_NORMAL_LABEL, 0, 14, 0},
 {"mjpeg", 0,  0, 0, 1, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
#include "Fl_Choice_gfc.h"
#include "Fl_Button_gfc.h"
#include "UICallbacks.h"
#include "UIConstants.h"

Fl_Double_Window* RenderWindow::make_window() {
  { renderWindow = new Fl_Double_Window(470, 495, "JefeCheck -Render");
    renderWindow->user_data((void*)(this));
    { Fl_Box* o = bg = new Fl_Box(0, -3, 490, 591);
      bg->box(FL_FLAT_BOX);
      bg->color((Fl_Color)30);
      o->color(fl_rgb_color(GFC_BG_COLOR,GFC_BG_COLOR,GFC_BG_COLOR));
    } // Fl_Box* bg
    { render = new Fl_Button_gfc(110, 443, 95, 40, "Render");
      render->tooltip("Start Render");
      render->box(FL_FLAT_BOX);
      render->down_box(FL_PLASTIC_DOWN_BOX);
      render->color(FL_INACTIVE_COLOR);
      render->selection_color(FL_BACKGROUND_COLOR);
      render->labeltype(FL_NORMAL_LABEL);
      render->labelfont(0);
      render->labelsize(14);
      render->labelcolor((Fl_Color)31);
      render->callback((Fl_Callback*)RenderCB, (void*)(RENDERRENDER_ID));
      render->align(FL_ALIGN_CENTER);
      render->when(FL_WHEN_RELEASE);
    } // Fl_Button_gfc* render
    { done = new Fl_Button_gfc(365, 443, 95, 40, "Done");
      done->tooltip("Closes this window");
      done->box(FL_FLAT_BOX);
      done->down_box(FL_PLASTIC_DOWN_BOX);
      done->color(FL_INACTIVE_COLOR);
      done->selection_color(FL_BACKGROUND_COLOR);
      done->labeltype(FL_NORMAL_LABEL);
      done->labelfont(0);
      done->labelsize(14);
      done->labelcolor((Fl_Color)31);
      done->callback((Fl_Callback*)RenderCB, (void*)(RENDERDONE_ID));
      done->align(FL_ALIGN_CENTER);
      done->when(FL_WHEN_RELEASE);
    } // Fl_Button_gfc* done
    { Fl_Progress* o = progress = new Fl_Progress(10, 418, 455, 20, "Render Progress");
      progress->box(FL_FLAT_BOX);
      progress->color(FL_INACTIVE_COLOR);
      progress->selection_color((Fl_Color)59);
      o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
    } // Fl_Progress* progress
    { openWhenDone = new Fl_Check_Button(10, 396, 445, 15, "Open rendered frames when done (clears FXs and loaded frames)");
      openWhenDone->down_box(FL_FLAT_BOX);
      openWhenDone->color(FL_INACTIVE_COLOR);
      openWhenDone->selection_color((Fl_Color)31);
      openWhenDone->labelcolor((Fl_Color)31);
    } // Fl_Check_Button* openWhenDone
    { Fl_Tabs* o = new Fl_Tabs(0, 6, 470, 382);
      o->box(FL_BORDER_FRAME);
      o->color(FL_FOREGROUND_COLOR);
      o->selection_color(FL_INACTIVE_COLOR);
      o->labelcolor((Fl_Color)31);
      { Fl_Group* o = new Fl_Group(0, 22, 470, 360, "General");
        o->color(FL_FOREGROUND_COLOR);
        o->selection_color(FL_INACTIVE_COLOR);
        o->labelcolor(FL_INACTIVE_COLOR);
        { Fl_Group* o = new Fl_Group(6, 95, 459, 287, "Output Files");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { browse = new Fl_Button_gfc(382, 136, 63, 27, "Browse");
            browse->box(FL_UP_BOX);
            browse->color(FL_BACKGROUND_COLOR);
            browse->selection_color(FL_BACKGROUND_COLOR);
            browse->labeltype(FL_NORMAL_LABEL);
            browse->labelfont(0);
            browse->labelsize(14);
            browse->labelcolor(FL_FOREGROUND_COLOR);
            browse->callback((Fl_Callback*)RenderCB, (void*)(RENDERBROWSE_ID));
            browse->align(FL_ALIGN_CENTER);
            browse->when(FL_WHEN_RELEASE);
          } // Fl_Button_gfc* browse
          { Fl_Input* o = prefix = new Fl_Input(15, 191, 151, 20, "Prefix");
            prefix->box(FL_FLAT_BOX);
            prefix->color(FL_INACTIVE_COLOR);
            prefix->selection_color(FL_FOREGROUND_COLOR);
            prefix->labelcolor((Fl_Color)31);
            prefix->textcolor(31);
            prefix->callback((Fl_Callback*)RenderCB, (void*)(RENDERPREFIX_ID));
            prefix->align(FL_ALIGN_TOP);
            prefix->when(FL_WHEN_CHANGED);
            o->value("render");
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Input* prefix
          { Fl_Value_Input* o = padding = new Fl_Value_Input(177, 191, 25, 20, "Padding");
            padding->box(FL_FLAT_BOX);
            padding->color(FL_INACTIVE_COLOR);
            padding->selection_color(FL_FOREGROUND_COLOR);
            padding->labelcolor((Fl_Color)31);
            padding->maximum(10);
            padding->step(1);
            padding->value(4);
            padding->textcolor(31);
            padding->callback((Fl_Callback*)RenderCB, (void*)(RENDERPADDING_ID));
            padding->align(FL_ALIGN_TOP);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Input* padding
          { Fl_Text_Display* o = example = new Fl_Text_Display(13, 295, 440, 72, "Example");
            example->box(FL_FLAT_BOX);
            example->color(FL_INACTIVE_COLOR);
            example->selection_color(FL_FOREGROUND_COLOR);
            example->labelcolor((Fl_Color)31);
            example->textcolor(31);
            example->align(FL_ALIGN_TOP_LEFT);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Text_Display* example
          { formatChoice = new Fl_Choice_gfc(369, 189, 66, 23, "Format");
            formatChoice->box(FL_FLAT_BOX);
            formatChoice->down_box(FL_BORDER_BOX);
            formatChoice->color(FL_BACKGROUND_COLOR);
            formatChoice->selection_color(FL_SELECTION_COLOR);
            formatChoice->labeltype(FL_NORMAL_LABEL);
            formatChoice->labelfont(0);
            formatChoice->labelsize(14);
            formatChoice->labelcolor(FL_BACKGROUND2_COLOR);
            formatChoice->callback((Fl_Callback*)RenderCB, (void*)(RENDERFORMAT_ID));
            formatChoice->align(FL_ALIGN_TOP);
            formatChoice->when(FL_WHEN_RELEASE);
            formatChoice->menu(menu_formatChoice);
          } // Fl_Choice_gfc* formatChoice
          { createMovie = new Fl_Check_Button(251, 236, 175, 20, "create movie (linux only)");
            createMovie->down_box(FL_FLAT_BOX);
            createMovie->color(FL_INACTIVE_COLOR);
            createMovie->selection_color((Fl_Color)31);
            createMovie->labelcolor((Fl_Color)31);
            createMovie->callback((Fl_Callback*)RenderCB, (void*)(RENDERCREATEMOVIE_ID));
          } // Fl_Check_Button* createMovie
          { deleteFramesAfterMovie = new Fl_Check_Button(268, 257, 197, 20, "delete frames when done");
            deleteFramesAfterMovie->down_box(FL_FLAT_BOX);
            deleteFramesAfterMovie->color(FL_INACTIVE_COLOR);
            deleteFramesAfterMovie->selection_color((Fl_Color)31);
            deleteFramesAfterMovie->labelcolor((Fl_Color)31);
            deleteFramesAfterMovie->deactivate();
          } // Fl_Check_Button* deleteFramesAfterMovie
          { Fl_Value_Input* o = startFrame = new Fl_Value_Input(49, 236, 40, 24, "Start");
            startFrame->box(FL_FLAT_BOX);
            startFrame->color(FL_INACTIVE_COLOR);
            startFrame->selection_color(FL_FOREGROUND_COLOR);
            startFrame->labelcolor((Fl_Color)31);
            startFrame->maximum(99999);
            startFrame->step(1);
            startFrame->value(1);
            startFrame->textcolor(31);
            startFrame->callback((Fl_Callback*)RenderCB, (void*)(RENDERSTART_ID));
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Input* startFrame
          { Fl_Value_Input* o = endFrame = new Fl_Value_Input(124, 236, 40, 24, "End");
            endFrame->box(FL_FLAT_BOX);
            endFrame->color(FL_INACTIVE_COLOR);
            endFrame->selection_color(FL_FOREGROUND_COLOR);
            endFrame->labelcolor((Fl_Color)31);
            endFrame->maximum(99999);
            endFrame->step(1);
            endFrame->value(1);
            endFrame->textcolor(31);
            endFrame->callback((Fl_Callback*)RenderCB, (void*)(RENDEREND_ID));
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Input* endFrame
          { Fl_Input* o = postfix = new Fl_Input(213, 191, 151, 20, "Postfix");
            postfix->box(FL_FLAT_BOX);
            postfix->color(FL_INACTIVE_COLOR);
            postfix->selection_color(FL_FOREGROUND_COLOR);
            postfix->labelcolor((Fl_Color)31);
            postfix->textcolor(31);
            postfix->callback((Fl_Callback*)RenderCB, (void*)(RENDERPREFIX_ID));
            postfix->align(FL_ALIGN_TOP);
            postfix->when(FL_WHEN_CHANGED);
            o->value("");
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Input* postfix
          { autoRange = new Fl_Button_gfc(169, 236, 45, 25, "auto");
            autoRange->box(FL_UP_BOX);
            autoRange->color(FL_BACKGROUND_COLOR);
            autoRange->selection_color(FL_BACKGROUND_COLOR);
            autoRange->labeltype(FL_NORMAL_LABEL);
            autoRange->labelfont(0);
            autoRange->labelsize(14);
            autoRange->labelcolor(FL_FOREGROUND_COLOR);
            autoRange->callback((Fl_Callback*)RenderCB, (void*)(RENDERAUTORANGE_ID));
            autoRange->align(FL_ALIGN_CENTER);
            autoRange->when(FL_WHEN_RELEASE);
          } // Fl_Button_gfc* autoRange
          { Fl_Output* o = path = new Fl_Output(15, 138, 365, 24, "Path");
            path->box(FL_FLAT_BOX);
            path->color(FL_INACTIVE_COLOR);
            path->selection_color(FL_FOREGROUND_COLOR);
            path->labelcolor((Fl_Color)31);
            path->textcolor(31);
            path->callback((Fl_Callback*)RenderCB, (void*)(RENDERPREFIX_ID));
            path->align(FL_ALIGN_TOP_LEFT);
            path->when(FL_WHEN_CHANGED);
            path->deactivate();
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Output* path
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(6, 28, 453, 57, "Source");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { quadrantChoice = new Fl_Choice_gfc(82, 51, 101, 23, "Viewport: ");
            quadrantChoice->box(FL_FLAT_BOX);
            quadrantChoice->down_box(FL_BORDER_BOX);
            quadrantChoice->color(FL_BACKGROUND_COLOR);
            quadrantChoice->selection_color(FL_SELECTION_COLOR);
            quadrantChoice->labeltype(FL_NORMAL_LABEL);
            quadrantChoice->labelfont(0);
            quadrantChoice->labelsize(14);
            quadrantChoice->labelcolor(FL_BACKGROUND2_COLOR);
            quadrantChoice->callback((Fl_Callback*)RenderCB, (void*)(RENDERQUADRANT_ID));
            quadrantChoice->align(FL_ALIGN_LEFT);
            quadrantChoice->when(FL_WHEN_RELEASE);
            quadrantChoice->menu(menu_quadrantChoice);
          } // Fl_Choice_gfc* quadrantChoice
          { Fl_Value_Input* o = scale = new Fl_Value_Input(243, 51, 40, 24, "Scale");
            scale->box(FL_FLAT_BOX);
            scale->color(FL_INACTIVE_COLOR);
            scale->selection_color(FL_FOREGROUND_COLOR);
            scale->labelcolor((Fl_Color)31);
            scale->minimum(0.01);
            scale->maximum(4);
            scale->step(0.01);
            scale->value(1);
            scale->textcolor(31);
            scale->callback((Fl_Callback*)RenderCB, (void*)(RENDERSCALE_ID));
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Input* scale
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(6, 28, 454, 360, "Image Options");
        o->color(FL_FOREGROUND_COLOR);
        o->selection_color(FL_INACTIVE_COLOR);
        o->labelcolor(FL_INACTIVE_COLOR);
        o->hide();
        { Fl_Group* o = new Fl_Group(6, 29, 453, 57, "jpeg");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { Fl_Value_Slider* o = jpegQuality = new Fl_Value_Slider(62, 56, 212, 20, "Quality");
            jpegQuality->type(3);
            jpegQuality->box(FL_FLAT_BOX);
            jpegQuality->color(FL_INACTIVE_COLOR);
            jpegQuality->selection_color(FL_INACTIVE_COLOR);
            jpegQuality->labelcolor(FL_INACTIVE_COLOR);
            jpegQuality->minimum(1);
            jpegQuality->maximum(100);
            jpegQuality->step(1);
            jpegQuality->value(85);
            jpegQuality->textsize(14);
            jpegQuality->textcolor(31);
            jpegQuality->align(FL_ALIGN_LEFT);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            o->selection_color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Slider* jpegQuality
          { jpegProgressive = new Fl_Check_Button(284, 39, 78, 15, "Progressive");
            jpegProgressive->down_box(FL_FLAT_BOX);
            jpegProgressive->color(FL_INACTIVE_COLOR);
            jpegProgressive->selection_color((Fl_Color)31);
            jpegProgressive->labelcolor((Fl_Color)31);
          } // Fl_Check_Button* jpegProgressive
          { jpegOptimize = new Fl_Check_Button(285, 60, 78, 15, "Optimized");
            jpegOptimize->down_box(FL_FLAT_BOX);
            jpegOptimize->color(FL_INACTIVE_COLOR);
            jpegOptimize->selection_color((Fl_Color)31);
            jpegOptimize->labelcolor((Fl_Color)31);
            jpegOptimize->deactivate();
          } // Fl_Check_Button* jpegOptimize
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(6, 89, 453, 57, "png");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { Fl_Value_Slider* o = pngCompression = new Fl_Value_Slider(103, 116, 343, 20, "Compression");
            pngCompression->type(3);
            pngCompression->box(FL_FLAT_BOX);
            pngCompression->color(FL_INACTIVE_COLOR);
            pngCompression->selection_color(FL_INACTIVE_COLOR);
            pngCompression->labelcolor(FL_INACTIVE_COLOR);
            pngCompression->minimum(1);
            pngCompression->maximum(7);
            pngCompression->step(1);
            pngCompression->value(5);
            pngCompression->textsize(14);
            pngCompression->textcolor(31);
            pngCompression->align(FL_ALIGN_LEFT);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            o->selection_color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Slider* pngCompression
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(6, 149, 453, 57, "tiff");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { Fl_Choice_gfc* o = tiffCompression = new Fl_Choice_gfc(103, 176, 127, 20, "Compression");
            tiffCompression->box(FL_FLAT_BOX);
            tiffCompression->down_box(FL_BORDER_BOX);
            tiffCompression->color(FL_BACKGROUND_COLOR);
            tiffCompression->selection_color(FL_SELECTION_COLOR);
            tiffCompression->labeltype(FL_NORMAL_LABEL);
            tiffCompression->labelfont(0);
            tiffCompression->labelsize(14);
            tiffCompression->labelcolor(FL_INACTIVE_COLOR);
            tiffCompression->textsize(10);
            tiffCompression->align(FL_ALIGN_LEFT);
            tiffCompression->when(FL_WHEN_RELEASE);
            tiffCompression->menu(menu_tiffCompression);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Choice_gfc* tiffCompression
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(6, 208, 454, 84, "exr");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { openEXRDepth = new Fl_Choice_gfc(99, 238, 180, 20, "Depth");
            openEXRDepth->box(FL_FLAT_BOX);
            openEXRDepth->down_box(FL_BORDER_BOX);
            openEXRDepth->color(FL_BACKGROUND_COLOR);
            openEXRDepth->selection_color(FL_SELECTION_COLOR);
            openEXRDepth->labeltype(FL_NORMAL_LABEL);
            openEXRDepth->labelfont(0);
            openEXRDepth->labelsize(14);
            openEXRDepth->labelcolor(FL_BACKGROUND2_COLOR);
            openEXRDepth->textsize(10);
            openEXRDepth->align(FL_ALIGN_LEFT);
            openEXRDepth->when(FL_WHEN_RELEASE);
            openEXRDepth->menu(menu_openEXRDepth);
          } // Fl_Choice_gfc* openEXRDepth
          { openEXRCompression = new Fl_Choice_gfc(99, 265, 180, 20, "Compression");
            openEXRCompression->box(FL_FLAT_BOX);
            openEXRCompression->down_box(FL_BORDER_BOX);
            openEXRCompression->color(FL_BACKGROUND_COLOR);
            openEXRCompression->selection_color(FL_SELECTION_COLOR);
            openEXRCompression->labeltype(FL_NORMAL_LABEL);
            openEXRCompression->labelfont(0);
            openEXRCompression->labelsize(14);
            openEXRCompression->labelcolor(FL_BACKGROUND2_COLOR);
            openEXRCompression->textsize(10);
            openEXRCompression->align(FL_ALIGN_LEFT);
            openEXRCompression->when(FL_WHEN_RELEASE);
            openEXRCompression->menu(menu_openEXRCompression);
          } // Fl_Choice_gfc* openEXRCompression
          o->end();
        } // Fl_Group* o
        o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(1, 29, 469, 358, "movie options");
        o->color(FL_FOREGROUND_COLOR);
        o->selection_color(FL_INACTIVE_COLOR);
        o->labelcolor(FL_INACTIVE_COLOR);
        o->hide();
        { Fl_Group* o = new Fl_Group(6, 36, 453, 104, "Mencoder Options (linux only)");
          o->box(FL_BORDER_FRAME);
          o->color((Fl_Color)31);
          o->labelfont(1);
          o->labelcolor((Fl_Color)31);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
          { Fl_Value_Slider* o = aviQuality = new Fl_Value_Slider(16, 78, 433, 20, "Kbits/second");
            aviQuality->type(3);
            aviQuality->box(FL_FLAT_BOX);
            aviQuality->color(FL_INACTIVE_COLOR);
            aviQuality->selection_color(FL_INACTIVE_COLOR);
            aviQuality->labelcolor(FL_INACTIVE_COLOR);
            aviQuality->minimum(200);
            aviQuality->maximum(5000);
            aviQuality->step(1);
            aviQuality->value(800);
            aviQuality->textsize(14);
            aviQuality->textcolor(31);
            aviQuality->align(FL_ALIGN_TOP_LEFT);
            o->color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
            o->selection_color(fl_rgb_color(GFC_WIDGET_COLOR,GFC_WIDGET_COLOR,GFC_WIDGET_COLOR));
          } // Fl_Value_Slider* aviQuality
          { codecChoice = new Fl_Choice_gfc(66, 105, 96, 23, "Codec");
            codecChoice->box(FL_FLAT_BOX);
            codecChoice->down_box(FL_BORDER_BOX);
            codecChoice->color(FL_BACKGROUND_COLOR);
            codecChoice->selection_color(FL_SELECTION_COLOR);
            codecChoice->labeltype(FL_NORMAL_LABEL);
            codecChoice->labelfont(0);
            codecChoice->labelsize(14);
            codecChoice->labelcolor((Fl_Color)31);
            codecChoice->align(FL_ALIGN_LEFT);
            codecChoice->when(FL_WHEN_RELEASE);
            codecChoice->menu(menu_codecChoice);
          } // Fl_Choice_gfc* codecChoice
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { cancel = new Fl_Button_gfc(10, 443, 95, 40, "Cancel");
      cancel->tooltip("Start Render");
      cancel->box(FL_FLAT_BOX);
      cancel->down_box(FL_PLASTIC_DOWN_BOX);
      cancel->color(FL_INACTIVE_COLOR);
      cancel->selection_color(FL_BACKGROUND_COLOR);
      cancel->labeltype(FL_NORMAL_LABEL);
      cancel->labelfont(0);
      cancel->labelsize(14);
      cancel->labelcolor((Fl_Color)31);
      cancel->callback((Fl_Callback*)RenderCB, (void*)(RENDERCANCEL_ID));
      cancel->align(FL_ALIGN_CENTER);
      cancel->when(FL_WHEN_RELEASE);
      cancel->deactivate();
    } // Fl_Button_gfc* cancel
    renderWindow->set_non_modal();
    renderWindow->size_range(470, 495, 470, 495);
    renderWindow->end();
  } // Fl_Double_Window* renderWindow
  return renderWindow;
}
