// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef renderWindow_h
#define renderWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include "Fl_Button_gfc.h"
extern void RenderCB(Fl_Button_gfc*, void*);
#include <FL/Fl_Progress.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern void RenderCB(Fl_Input*, void*);
#include <FL/Fl_Value_Input.H>
extern void RenderCB(Fl_Value_Input*, void*);
#include <FL/Fl_Text_Display.H>
#include "Fl_Choice_gfc.h"
extern void RenderCB(Fl_Choice_gfc*, void*);
extern void RenderCB(Fl_Check_Button*, void*);
#include <FL/Fl_Output.H>
extern void RenderCB(Fl_Output*, void*);
#include <FL/Fl_Value_Slider.H>

class RenderWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *renderWindow;
  Fl_Box *bg;
  Fl_Button_gfc *render;
  Fl_Button_gfc *done;
  Fl_Progress *progress;
  Fl_Check_Button *openWhenDone;
  Fl_Button_gfc *browse;
  Fl_Input *prefix;
  Fl_Value_Input *padding;
  Fl_Text_Display *example;
  Fl_Choice_gfc *formatChoice;
  static Fl_Menu_Item menu_formatChoice[];
  Fl_Check_Button *createMovie;
  Fl_Check_Button *deleteFramesAfterMovie;
  Fl_Value_Input *startFrame;
  Fl_Value_Input *endFrame;
  Fl_Input *postfix;
  Fl_Button_gfc *autoRange;
  Fl_Output *path;
  Fl_Choice_gfc *quadrantChoice;
  static Fl_Menu_Item menu_quadrantChoice[];
  Fl_Value_Input *scale;
  Fl_Value_Slider *jpegQuality;
  Fl_Check_Button *jpegProgressive;
  Fl_Check_Button *jpegOptimize;
  Fl_Value_Slider *pngCompression;
  Fl_Choice_gfc *tiffCompression;
  static Fl_Menu_Item menu_tiffCompression[];
  Fl_Choice_gfc *openEXRDepth;
  static Fl_Menu_Item menu_openEXRDepth[];
  Fl_Choice_gfc *openEXRCompression;
  static Fl_Menu_Item menu_openEXRCompression[];
  Fl_Value_Slider *aviQuality;
  Fl_Choice_gfc *codecChoice;
  static Fl_Menu_Item menu_codecChoice[];
  Fl_Button_gfc *cancel;
};
#endif
