// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef splashWindow_h
#define splashWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>

class SplashScreen {
public:
  SplashScreen(int x, int y, int wi, int height, const char* l);
  Fl_Double_Window* make_window();
  Fl_Double_Window *splashScreen;
};
#endif
