// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "splashWindow.h"
#include "UIConstants.h"
#include "UICallbacks.h"

SplashScreen::SplashScreen(int x, int y, int wi, int height, const char* l) {
}

Fl_Double_Window* SplashScreen::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = splashScreen = new Fl_Double_Window(685, 530, "splashScreen");
    w = o;
    o->color(FL_BLACK);
    o->labelcolor((Fl_Color)17);
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(166, 478, 605, 17, "JefeCheck by Daniel Goll\341s for Ollin Studio");
      o->labelcolor((Fl_Color)29);
    }
    { Fl_Box* o = new Fl_Box(174, 496, 605, 17, "2006  All Rights Reserved     version 1.0 RC1");
      o->labelcolor((Fl_Color)29);
    }
    o->clear_border();
    o->size_range(685, 530, 685, 530);
    o->end();
  }
  return w;
}
