// // Defined constants for UI callback arguments

#ifndef UICONSTANTS_H
#define UICONSTANTS_H

#define GFC_BG_COLOR 32
#define GFC_WIDGET_COLOR 42
#define GFC_WIDGET_LIGHT_TEXT_COLOR 160
#define GFC_WIDGET_DARK_TEXT_COLOR 85


enum LoadModes{
GFC_SEQREPLACE,
GFC_SEQLEAVE,
GFC_SEQSTREAM,
GFC_SEQAPPEND,
GFC_SEQERASE
};

enum CompressionModes{
GFC_8BPC,
GFC_16BPC,
GFC_16HALF,
GFC_4BPC,
GFC_S3TCDX1
};

enum NoteTypes{
GFCNOTETYPE_TEXT,
GFCNOTETYPE_DRAWING,
GFCNOTETYPE_ANILINE
};


enum CBArgs{
TARGETFPS_ID=1,
TIMELINEINPUT_ID,
TIMELINE_ID,
PLAY_ID,
PLAYREV_ID,
PLAYFWD_ID,
PLAYPAUSE_ID,
FORWARDONE_ID,
BACKONE_ID,
REWIND_ID,
FF_ID,

ABORTA_ID,
ABORTB_ID,
ABORTC_ID,
ABORTD_ID,

MAINVP_ID,
LOADVP_ID,

TRACKATOGGLE_ID,
TRACKBTOGGLE_ID,
TRACKCTOGGLE_ID,
TRACKDTOGGLE_ID,

LOOPMODEONCE_ID,
LOOPMODELOOP_ID,
LOOPMODEBOUNCE_ID,
LOOPPRIORITY_ID,

ADDTOPLAYLIST_ID,

PLAYFROM_ID,
PLAYTO_ID,

INPOINT_ID,
OUTPOINT_ID,

CHANNELMASKR_ID,
CHANNELMASKG_ID,
CHANNELMASKB_ID,
CHANNELMASKA_ID,


CBMOREOPTIONS_ID,
MOFRAMEOFFSET_ID,
MOCLOSE_ID,
MOUNLOADTRACK_ID,
MOHOLDFRAME_ID,


FRAMINGSINGLE_ID,
FRAMINGDOUBLE_ID,
FRAMINGDOUBLEVERT_ID,
FRAMINGQUAD_ID,
FRAMINGSTEREO_ID,
FRAMINGOVERLAY_ID,

ACTIVEVIEWPORT_ID,

RGBBUTTON00_ID,
RGBBUTTON01_ID,
RGBBUTTON02_ID,
RGBBUTTON03_ID,

CBASPECT_ID,
CBRATIO0_ID,
CBRATIO1_ID,
CBRATIO2_ID,
CBRATIO3_ID,
CBCROP_ID,
CBCROPPOS_ID,
CBFLIP_ID,
CBFLOP_ID,
PLATECONTROLS_ID,
PLATECONTROLSCOLOR_ID,
PLATECONTROLSTRANSFORMATIONS_ID,
PLATEFX_ID,

ABOUTWINDOWCLOSE_ID,
MENUFILELOAD_ID,
MENUFILEPLAYLIST_ID,
MENUFILEPREFERENCES_ID,
MENUFILESAVESESSION_ID,
MENUFILEOPENSESSION_ID,
MENUFILERENDER_ID,
MENUFILEOPENRECENTSESSION_ID,
MENUFILEEXIT_ID,
MENURESETXFORM_ID,
MENURESETXFORMALL_ID,
MENUSAVECCFAVORITE1_ID,
MENUSAVECCFAVORITE2_ID,
MENUSAVECCFAVORITE3_ID,
MENUSAVECCFAVORITE4_ID,
MENUSAVECCFAVORITE5_ID,

MENULOADCCFAVORITE1_ID,
MENULOADCCFAVORITE2_ID,
MENULOADCCFAVORITE3_ID,
MENULOADCCFAVORITE4_ID,
MENULOADCCFAVORITE5_ID,

MENURESETCC_ID,
MENURESETCCALL_ID,
MENUFITTOVIEWPORT_ID,
MENUFITALLTOVIEWPORT_ID,

MENUFLIP_ID,
MENUFLOP_ID,
MENUFLIPALL_ID,
MENUFLOPALL_ID,

MENUHELPABOUT_ID,
MENUHELPUSERGUIDE_ID,
MENUHELPQUICKREFERENCE_ID,
MENUHELPONLINESUPPORT_ID,
MENUHELPQUICKHELP_ID,
MENUHELPREQUIREMENTSCHECK_ID,
MENUHELPVIDEOTUTORIALS_ID,

MENUFULLSCREEN_ID,
MENUHIDECONTROLS_ID,

MENUGAMMA_ID,

MENUSINGLE_ID,
MENUDOUBLE_ID,
MENUQUAD_ID,
MENUDOUBLEVERT_ID,
MENUSTEREO_ID,
MENUOVERLAY_ID,

MENUPLUGINLOADER_ID,
MENULUTLOADER_ID,

MENUREMOTEMANAGER_ID,
MENUREMOTECHATMODE_ID,
MENUREMOTEPASTE_ID,
MENUREMOTESAVECHAT_ID,

MENUHISTOGRAM_ID,
MENUVECTOROSCOPE_ID,

MENUREVIEWTOOLBAR_ID,

BGCOLORGRAY_ID,
BGCOLORBLACK_ID,
FILTERINGMINLINEAR_ID,
FILTERINGMINBILINEAR_ID,
FILTERINGMAGLINEAR_ID,
FILTERINGMAGBILINEAR_ID,

MENUASPECTOPACITY100_ID,
MENUASPECTOPACITY75_ID,
MENUASPECTOPACITY50_ID,
MENUASPECTOPACITY25_ID,

LOADFILENAME_ID,
LOADBROWSE_ID,
LOADRECENT_ID,
LOADLOAD_ID,
LOADADDTOQUEUE_ID,
LOADOPENPLAYLIST_ID,
LOADDONE_ID,
LOADSTART_ID,
LOADCANCEL_ID,
LOADSTOPRESUME_ID,
LOADGAMMA_ID,
LOADFROM_ID,
LOADTO_ID,
LOADCLOSE_ID,
LOADEXR_ID,
EXRTRACKA_ID,
EXRTRACKB_ID,
EXRTRACKC_ID,
EXRTRACKD_ID,
EXRPREVIEW_ID,
LOADUPDATEPREVIEW_ID,
LOADUPDATE_ID,
LOADLUT_ID,
LOADQUEUEA_ID,
LOADREMOVEA_ID,
LOADUNLOADANDCLEAR_ID,

LOADQUEUEB_ID,
LOADREMOVEB_ID,

LOADQUEUEC_ID,
LOADREMOVEC_ID,

LOADQUEUED_ID,
LOADREMOVED_ID,

LOADREDUCE_ID,

FILTERQUICK_ID,
FILTERBILINEAR_ID,
FILTERLANCZOS_ID,
FILTERPOINT_ID,
FILTERBOX_ID,
FILTERTRIANGLE_ID,
FILTERHERMITE_ID,
FILTERHANNING_ID,
FILTERHAMMING_ID,
FILTERBLACKMAN_ID,
FILTERGAUSSIAN_ID,
FILTERQUADRATIC_ID,
FILTERCUBIC_ID,
FILTERCATROM_ID,
FILTERMITCHELL_ID,
FILTERBESELL_ID,
FILTERSINC_ID,

GAMMAGLOBAL_ID,
GAMMADONE_ID,
GAMMABYCOLOR_ID,

PREFSTOTALFRAMESINRAM_ID,
PREFSFORCEPBO_ID,
PREFSNUMBEROFSLICES_ID,
PREFERENCESSLICEPATH_ID,
PATHBROWSEBUTTON_ID,
PATHSEARCHBROWSEBUTTON_ID,
PATHSEARCHDELETEBUTTON_ID,
PATHSEARCHBROWSER_ID,
LICENSEPATHBROWSEBUTTON_ID,
LICENSEREQUESTNEWLICENSEEBUTTON_ID,
EXRPREFSDEFAULTSBUTTON_ID,

ACTIVATORDONEBUTTON_ID,
ACTIVATORCREATEBUTTON_ID,
ACTIVATORSAVEBUTTON_ID,
ACTIVATORBUYBUTTON_ID,
ACTIVATORTRYAGAINBUTTON_ID,

PREFERENCESLOOPPRIORITYSHORTEST_ID,
PREFERENCESLOOPPRIORITYLONGEST_ID,
PREFERENCESSAVE_ID,
PREFERENCESDONE_ID,

LUTBROWSE_ID,
LUTLOAD_ID,
LUTDONE_ID,
LUTPREVIEW_ID,
LUTDELETE_ID,
LUTREFRESH_ID,
LUTAUTOLOAD_ID,
LUTCHANGEPREVIEW_ID,
LUTAUTOLOADALL_ID,
LUTUNLOADALL_ID,
LUTDEFAULTLUT_ID,

FXDONE_ID,
FXBROWSE_ID,
FXAUTOLOADALL_ID,
FXUNLOADALL_ID,
FXLOAD_ID,
FXDELETEFX_ID,
FXAUTOLOAD_ID,
FXDELETECM_ID,

RENDERRENDER_ID,
RENDERDONE_ID,
RENDERCANCEL_ID,
RENDERSTART_ID,
RENDEREND_ID,
RENDERBROWSE_ID,
RENDERPREFIX_ID,
RENDERPADDING_ID,
RENDERFORMAT_ID,
RENDERQUADRANT_ID,
RENDERSCALE_ID,
RENDERAUTORANGE_ID,
RENDERCREATEMOVIE_ID,

REMOTE_CONNECT_ID,
REMOTE_START_ID,
REMOTE_RECENT_ID,
REMOTE_PREFERENCES_ID,
REMOTE_SELECTCOLOR_ID,

REVIEWTOOLSREVIEWTREE_ID,

TESTBUTTON
};

enum GFCCROPMODES{GFCCROPCENTER=0, GFCCROPBOTTOM, GFCCROPTOP};
#endif //#ifndef UICONSTANTS_H

